[Fix] 앱 로그인 조직 인증 버그 수정
DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY pull request #126
Opened 2022-12-03 04:26 UTC by Gobans

## 작업내용

- [x] **Fix** 로그아웃하고 재접속 하면 인증 없음으로 나오는 현상
- [x] **Fix** 조직 인증 안 한 채로 앱 껐켰하면 메인리스트 화면으로 가지지만 조직은 없는 상태

### 두가지 버그의 발생이유

- UserInfoManager.userinfo.**userOrgName** 의 저장이 **DomainSettingViewController** 에서 이메일 인증을 한 후에 이루어지기 때문에 발생한 버그였습니다. 이메일 인증페이지에서 인증을 하지 않는다면, userOrgName 은 갱신되지 않습니다.

### 해결방안

- UserInfoManager에 **fetchOrganizationList** function을 추가하여 
로그아웃하고 재접속을 할 떄 UserDefaults에 userOrgName 이 없다면 통신을 통해 userOrgName을 가져와 다시 저장하는 기능을 만들었습니다.
- SceneDelegate 와 ThirdPartyLoginViewModel 에 userOrgName 이 UserDefaults에 있는지 확인하고 분기처리 하여  fetchOrganizationList 를 실행시켰습니다.
- fetchOrganizationList 는 네트워킹을 통해 비동기로 처리가 됩니다. userOrgName 의 갱신 시점이 PlaceListViewController가 load된 이후이기 떄문에 싱글톤 패턴으로 PassthroughSubject 를 사용하여 PlaceListViewController 에 바인딩 하여 userOrgName 의 갱신을 알려주었습니다.

위의 버그 현상들은 다 고쳤는데 조금 문제가 있습니다.

|UserOrgName을 갱신 안했을때| UserOrgName을 갱신 했을 때|
|:---:|:---:|
|<img width="250" src="https://user-images.githubusercontent.com/56781342/205421186-c6b7cfea-677b-4d20-aa52-a50193e4cedc.png">|<img width="250" src="https://user-images.githubusercontent.com/56781342/205422276-42720b77-6974-48ba-9cbd-7d70c873ffef.png">|

fetchOrganizationList 를 통해 placeTitle을 갱신 해줬을 때 trucation (...으로 문자열이 짤리는 현상)이 발생해서 adjustsFontSizeToFitWidth 를 통해서 조절해봤는데 글자크기가 많이 작아집니다ㅜ

|adjustsFontSizeToFitWidth 를 true 로 변경했을 때|
|:---:|
|<img width="250" src="https://user-images.githubusercontent.com/56781342/205421189-f3d30a4f-dee7-4010-a080-c3ee89585572.png">|

혹시 왜 이런 현상이 발생하는지, 해결방법 아시는분..! @YebinKim 
도움이 필요합니다.

## 리뷰포인트

버그 해결 방안 중 이해가 안되는 부분이 있다면 알려주세요! 
더 좋은 버그 픽스 방법이 있다면 알려주세요.

## Checklist
- [x] 브랜치를 가져와 작업한 경우 이전 브랜치에 PR을 보냈는지 확인
- [x] 빌드를 위해 SceneDelegate 수정한 것 PR로 올리지 않았는지 확인
- [x] 필요없는 주석, 프린트문 제거했는지 확인
- [x] 컨벤션 지켰는지 확인
- [x] final, private 제대로 넣었는지 확인
- [x] 다양한 디바이스에 레이아웃이 대응되는지 확인
  - [x] iPhone SE
  - [x] iPhone 13
  - [x] iPhone 13 Pro Max

2022-12-03 09:45 UTC, chaneeii requested changes
고생하셨습니다! 
몇가지 제안 + 발견사항이 있네요

2022-12-03 09:45 UTC, chaneeii commented on Projects/App/Sources/Domain/User/UserInfoManager.swift
>      }
p3)
현재 서버에서 내려주는 org가 list형식인걸로 알고 있습니다
저희도 추후에 여러조직에 가입하게 할 예정이라면, 이걸 현재 단계에서 미리 확장성을 고려하여 org 배열로 저장해두는건 어떨까요?
(추후 변경 대응에 좋을 것 같습니다!)

2022-12-03 09:45 UTC, chaneeii commented on Projects/App/Sources/UI/Place/PlaceList/View/PlaceListViewController.swift
> +    private func bindResult() {
p2)
논리적으로 이렇게 전개가 되는게 맞을까요..?

`UserInfoManager.shared.fetchOrganizationList(orgID: orgID)`
를 Scenedelegate 가 아닌 오히려 이쪽에서 해주고 
userdefaults의 장점이 있지만
< 1️⃣ 조직이름을 userdefaults에 저장이 되어있을때는 그 값으로 / 2️⃣ 아닐때는 fetch해서 하는 것보다 (갈래가 두갈래)>
- 1️⃣ ```placeTitle.text = UserInfoManager.userInfo?.userOrgName ?? "(인증대학없음)"```
- 2️⃣ 이쪽코드

오히려 (한갈래로) 무조건 로그인되고 이쪽페이지 왔을때 이 사람의 조직에 대한 정보를 fetch 해서 가져와 보여주는게 더 make sense한것같습니다!

일반적인 어플리케이션이 그렇게 돌아가지 않나 싶어요..!

2022-12-03 09:45 UTC, chaneeii commented on Projects/App/Sources/UI/Place/PlaceList/View/PlaceListViewController.swift
> -
p1)
파베 코드를 실수로 날린걸까요?

2022-12-03 09:45 UTC, chaneeii commented on Projects/App/Sources/Domain/User/UserInfoManager.swift
> +                UserInfoManager.userInfo?.userOrgName = orgList.first(where: {$0.id == orgID})?.name ?? "(대학 찾을 수 없음)"
p2)
(대학 찾을 수 없음) 을 "(인증대학없음)" 으로 통일하는게 좋아보입니다

2022-12-03 09:45 UTC, chaneeii commented on Projects/App/Sources/UI/Place/PlaceList/View/PlaceListViewController.swift
>          placeTitle.font = .systemFont(ofSize: 17, weight: .bold)
p1)
고반이 이야기 했던 글자가 잘리는 부분은 초기값인 `(인증대학없음)` 의 width 에 애플디벨로퍼 아카데미가 들어가면 짤려서 그렇게 나오고 처음에 한번 빼고는 다 정상적으로 나오더라구요!

이부분 이름 fetch 하고나서 layout 다시 업데이트 하게 하면 해결될 것 같아보입니다

<img width="656" alt="스크린샷 2022-12-03 오후 6 39 42" src="https://user-images.githubusercontent.com/63157395/205434552-53498e1f-e47e-4c86-b415-a36ee00cbf3a.png">
<img width="200" alt="스크린샷 2022-12-03 오후 6 39 42" src="https://user-images.githubusercontent.com/63157395/205434550-e4b4de07-4c36-4424-87d7-9200a60605f2.png">

2022-12-03 12:45 UTC, Gobans commented on Projects/App/Sources/UI/Place/PlaceList/View/PlaceListViewController.swift
> -
요거는 Bind Function을 extenion으로 빼는 과정에서 위치가 바뀐 코드입니다. 상단에 보면 그대로 있어요

2022-12-03 12:45 UTC, Gobans commented on Projects/App/Sources/Domain/User/UserInfoManager.swift
>      }
추후에 여러조직에 가입하기 위해선 userOrganization 사용 구조개선이 좀 필요한데,
이건 좀 큰작업이라 다른 PR로 올릴 예정입니다!
일단 TODO로 남겨두었습니다.
1520b544fcdee53a47cd9508158516b12360fdf6

2022-12-03 12:45 UTC, Gobans commented on Projects/App/Sources/Domain/User/UserInfoManager.swift
> +                UserInfoManager.userInfo?.userOrgName = orgList.first(where: {$0.id == orgID})?.name ?? "(대학 찾을 수 없음)"
반영완료
2b2c22704b91484bcc1e5c0677e7192fdcd955ef

2022-12-03 12:45 UTC, Gobans commented on Projects/App/Sources/UI/Place/PlaceList/View/PlaceListViewController.swift
> +    private func bindResult() {
버리가 말한 부분이 조금 더 reasonable 한 것 같네요
수정하였습니다.
1520b544fcdee53a47cd9508158516b12360fdf6

2022-12-03 12:45 UTC, Gobans commented on Projects/App/Sources/UI/Place/PlaceList/View/PlaceListViewController.swift
>          placeTitle.font = .systemFont(ofSize: 17, weight: .bold)
버리 말에 힌트를 얻어서 layoutIfNeeded 로 업데이트 하려했는데, 왜인지 안되더라구요..?
일단 UIBarButtonItem 을 다시 생성해주는 방식으로 해결하였습니다.
해결에 결정적인 도움이 됐습니다. 고민해주셔서 감사합니다!
39a9afa046f5af8fae44abb6e637a1935b310280

2022-12-03 12:47 UTC, Gobans commented
@chaneeii 코드리뷰 반영하였습니다! 🚀

2022-12-03 14:09 UTC, Lia316 reviewed
고반 수고하셨어요! 
화면 분기처리가 잘 돼서 이제는 중도 이탈도 잘 방어하는 앱이 되었네요! 😆

지금 조직 추가 여러개 하는 파트가 좀 애매해서 코드 리뷰도 같이 애매해진 감이 없잖아 있지만,,ㅎㅎ
몇 가지 수정 사항 함께 봐주시면 감사하겠습니다~!

2022-12-03 14:09 UTC, Lia316 commented on Projects/App/Sources/UI/User/Login/ViewModel/ThirdPartyLoginViewModel.swift
> +                    if isEmptyOrganization == true {
p5

`if isEmpty~~ == false` 정도는 `if !isEmpty~~ ` 보다 의미 상 명확한 것 같아서 괜찮다고 생각했지만,
true 정도는 변수명으로도 충분히 의미하는 바가 담겨있어서 그냥 `if isEmpty~~`로 조건문을 설정해도 괜찮을 것 같습니다..!

2022-12-03 14:09 UTC, Lia316 commented on Projects/App/Sources/UI/Place/PlaceList/View/PlaceListViewController.swift
> +//  Updated by 고반 on 2022/12/03.
p2

음 이 업데이트의 의미는 사실상 닉이 생성하시긴 했지만, 
맛집리스트 관련 문제가 생기면 제가 담당한다는 의미에서 추가한 주석입니다.

전반적인 UI / 데이터 Fetch 는 여전히 제가 담당한 코드라서, 아예 삭제하기 보다는
조직 관련해서 고반이 담당한 코드에 대한 주석을 추가해서 명시하는 게 더 좋을 것 같습니다

2022-12-03 14:09 UTC, Lia316 commented on Projects/App/Sources/Domain/User/UserInfoManager.swift
> +
p1

singleton 패턴인만큼 생성자에 private 접근제어를 붙여줘야 할 것 같습니다..!

2022-12-03 14:09 UTC, Lia316 commented on Projects/App/Sources/Domain/User/UserInfoManager.swift
> +    }
just 고찰

싱글톤하고 static property 및 메서드가 함께있는 게 되게 낯선 것 같아서 계속 이 부분에 대해서 생각해봤어요.
요기 [static vs singleton medium blog](https://medium.com/@liketaehoon/swift-static-vs-singleton-45743f619516) 를 보시면, 
- 싱글톤은 한번만 초기화되어야 하는 비싼 객체에 적절하고
- static은 인스턴스화 과정 없이 스택에 저장하는 값싼 값들에 있어 적절하다고 합니다

그러면 유저 관련 정보를 static으로 저장하는 것도 적절하고, 
Org name을 서버에서 불러오는 것도 비동기 네트워킹 작업이니까 인스턴스화하는 것도 필요해서 싱글톤으로 쓸 수도 있는데
왜 그럼 성격이 다른 것 같은 두 개가 같이 있지?? 하는 의문이 생겼습니다.

그러면 어디에 들어가는게 적절한가 고민을 빡세게 해봤는데요,
아직 조직 여러개 추가가 불가능한 상황이다 보니까, 적절한 곳이 없는 것 같아요
나중에 소셜 로그인 후에, 조직 선택하는 화면이 생긴다면, 그곳의 UseCase에 들어가는 게 적절하지 않을까,, 싶네요

처음에는 UseCase로 옮겨라! 하려고 했는데, 적절한 곳이 없어서 갈 곳 잃은 커멘트였습니다,,

2022-12-03 14:13 UTC, chaneeii commented on Projects/App/Sources/UI/Place/PlaceList/View/PlaceListViewController.swift
>          placeTitle.font = .systemFont(ofSize: 17, weight: .bold)
보통 그런 경우 view 하이라키 때문이지 않을까 싶은데 아무튼 해결이 되었다니 다행이네요!

2022-12-03 14:16 UTC, chaneeii commented on Projects/App/Sources/Domain/User/UserInfoManager.swift
> +    }
저도 요부분에 공감했습니다! 
usermanager보다는 usecase를 분리하는게 좋을 것 같아보였는데 비슷하게 결론 내리지못하겠더라구요 
어렵네여 정말

2022-12-03 14:38 UTC, Lia316 commented on Projects/App/Sources/Domain/User/UserInfoManager.swift
> +    }
근데 로그인 쪽에서 저장해도, 로그아웃할 때 정보를 다 삭제하는 데다,
다시 로그인할 때 서버에서 도메인 이름을 주진 않아서 
아마 서버에서 OrgId 로 조직명 fetching 하는 코드 자체는 필요할 것 같아요

로그인 쪽으로 코드를 옮기는 건 나쁘지 않을 것 같아요!

다만, `UserInfoManager.userInfo.userOrgName` UserInfoManager의 프로퍼티에 손을 대는 일이다 보니까,
UserInfoManager가 자기 일을 자기가 책임지는 것도 어느 정도 맞다고도 생각이 들어서
전 고반의 의견이 궁금해요

2022-12-04 02:10 UTC, Gobans commented on Projects/App/Sources/Domain/User/UserInfoManager.swift
> +    }
**UserInfoManager에 싱글톤과 static property 및 메서드가 함께있는 형태가 된 이유는 UserDefaults 를 사용하기 떄문이라고 생각합니다.**

- userInfo 는 UserDefaults 의 싱글톤 인스턴스를 사용하는 연산 프로퍼티 이기때문에, UserInfoManager 의 싱글톤 인스턴스가 될 필요가 사실상 없습니다. 때문에 userInfo는 사실상 UserInfoManager 의 싱글톤과 거의 무관한 프로퍼티입니다. 
그렇기 때문에 static 을 붙이든 안붙이든 크게 상관없다고 생각하는데,
 `UserInfoManager.shared.userInfo` 보다 `UserInfoManager.userInfo ` 로 한 depth 더 들어가지 않고 사용하는게 편리하다고 생각하여 그대로 두었습니다.

**UserInfoManager를 싱글톤인스턴스로 만들어 메소드를 사용하게끔 만든 이유는 userOrgName 을 fetching 하고 fetching 완료를 binding 하는 곳이 여러곳이 될 것 이라고 생각했기 때문입니다.**
- 현재는 조직의 이름을 fetching 하고 fetching 완료를 binding하는 곳이 PlaceList 한 곳 이지만, 추후에 유저가 여러 조직을 가입하고 변경할 수  있게 된다면, 여러개의 뷰에서 userOrgName의 업데이트를 알려야합니다. 그래서 PassthroughSubject `isNameFetched` 를 여러 뷰에서 공유해서 binding하여 userOrgName 의 변화를 한번에 업데이트 되는 것을 의도하였습니다.

**fetchOrganizationList 가 UserInfoManager 안에 들어있는 이유는 리아가 말씀하신 책임에 따른 객체 구성을 생각했기 때문입니다.**
- fetchOrganizationList 메소드가 실제로는 organizationList를 불러와서 userInfo의 userOrgName을 저장하는 작업을 하기 떄문에, 객체안의 프로퍼티를 변경하는 메소드는 해당 객체 안에 존재해야한다고 생각합니다.

- ++ 그런데 현재 구조에서는 추후 조직을 변경하는 동작에서 비효율성 (조직을 변경할 때 마다 매번 organizationList를 fetch 함)이 있는 것 같아서 구조 개선이 필요한 것 같습니다. 이는 TODO 로 남겨 놓고 userOrganization 사용 구조개선 작업을 할 떄 메소드를 분리하는 형태로 변경해보겠습니다.
b322382d90ba90a2d3ef98bb1a410f2cc5d76725

2022-12-04 02:49 UTC, Gobans commented on Projects/App/Sources/UI/User/Login/ViewModel/ThirdPartyLoginViewModel.swift
> +                    if isEmptyOrganization == true {
UserInfoManager.userInfo?.userOrganization.isEmpty 가 옵셔널이 되어서 true 를 명시해준 것 같은데,
nil일 경우 true 로 unwrapping 해주는게 낫겠네요..! 
1141f9279db00881628c1714a49f64d620dae4eb

2022-12-04 02:51 UTC, Gobans commented on Projects/App/Sources/UI/Place/PlaceList/View/PlaceListViewController.swift
> +//  Updated by 고반 on 2022/12/03.
그렇군요..!
수정하였습니다
4cba35200629b50faf915c21e692baac8c03c8dd

2022-12-04 02:52 UTC, Gobans commented on Projects/App/Sources/Domain/User/UserInfoManager.swift
> +
요거는 혹시 `isNameFetched` 에 private 제어를 붙이는걸 말씀하신걸까요?
isNameFetched 는 PlaceListViewController 에 바인딩 되는 subject입니다!

2022-12-04 02:58 UTC, Gobans commented
@Lia316  리뷰 반영하였습니다~!!
제 의견에 가감없이 말씀해주세요~~

2022-12-04 03:57 UTC, Lia316 commented on Projects/App/Sources/UI/User/Login/ViewModel/ThirdPartyLoginViewModel.swift
> +                    if isEmptyOrganization == true {
아아 그런 이유가 있었군요! 
요렇게 바꾸니까, 옵셔널이 되는 것도 더 잘 보여서 좋은 것 같아요! 👍🏻

2022-12-04 03:59 UTC, Lia316 commented on Projects/App/Sources/Domain/User/UserInfoManager.swift
> +
생성자 == init  입니다!

2022-12-04 04:53 UTC, Gobans commented on Projects/App/Sources/Domain/User/UserInfoManager.swift
> +
아하 머쓱하군요
수정완료!
f41cdafeb0f8e4fe1391836a2416bb0a93e5b23a

2022-12-04 10:04 UTC, Lia316 commented on Projects/App/Sources/Domain/User/UserInfoManager.swift
> +
음.. 어차피 싱글톤 패턴이라 생성자도 외부에서 못 만들고, 테스트도 못 해서
굳이 파라미터가 있을 필요가 있나 싶긴 해요..!

현재는 위에도 프로퍼티를 초기화해주고, 아래 생성자에서도 초기화해주는데, 둘 중에 하나만 해도 괜찮을 것 같아요~!
특히 어차피 생성을 shared를 통해 이미 해주고 있다보니까, 그냥 파라미터는 삭제해도 괜찮지 않을까요?
저는 그냥 `init() {}` 만 해도 충분할 거라고 생각했어요

2022-12-04 10:06 UTC, Lia316 approved these changes
이번 PR은 디자인패턴에 대해 논의하는 유의미한 시간이었던 것 같아요!
매니저 이 친구... 저는 아직 고민이 더 필요하기는 한데, 재밌네요 ㅋㅋㅋ

2022-12-04 10:30 UTC, chaneeii approved these changes

2022-12-04 11:17 UTC, Gobans commented on Projects/App/Sources/Domain/User/UserInfoManager.swift
> +
엇 이렇게도 되는군요! 반영했습니다~!
d9a60f3ea919faaffb3f6037532ca1b3305b1090

2022-12-04 11:27 UTC, merged