[Setting] 프로젝트 Tuist 초기 셋팅 및 PR 템플릿과 auto_assign 적용
DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY pull request #14
Opened 2022-10-08 05:55 UTC by Gobans

## 작업내용

- [x] 프로젝트 Tuist 초기 셋팅
- [x] PR 템플릿 적용 
- [x] auto_assign 적용

<img width="250" src="https://user-images.githubusercontent.com/56781342/194689849-9c433ed5-b370-41f6-a23a-0cd665339264.png">

### 프로젝트 Tuist 초기 셋팅 
- 전에 이야기 했던 것 처럼 App, DesignSystem, Network 로 3개로 모듈을 나누었습니다.
- SwiftLint가 적용된 상태입니다.
- 적용된 Package Dependencies는 스크린샷과 같습니다. Package Manager은 SPM 입니다.

### auto_assign
- 처음 적용해보는거라 잘 될지 모르겠네요. PR 작성창에서 Reviewers와 Assignees를 지정해주지 않고 create pull request 를 하면 적용된다고 합니다. 다음 PR 때 제대로 작동하는지 테스트 해보면 좋을 것 같습니다.

## 리뷰포인트

- 오타나 수정사항이 있다면 알려주세요..!

## Reference

- Zesty_BOARD

## Checklist
- [x] 브랜치를 가져와 작업한 경우 이전 브랜치에 PR을 보냈는지 확인
- [x] 빌드를 위해 SceneDelegate 수정한 것 PR로 올리지 않았는지 확인
- [x] 필요없는 주석, 프린트문 제거했는지 확인
- [x] 컨벤션 지켰는지 확인
- [x] final, private 제대로 넣었는지 확인
- [x] Xcode Team none 으로 되어있는지 확인

2022-10-08 06:23 UTC, chaneeii reviewed
고생하셨습니다 🥳🥳🥳

다만,,,, 아쉬운점이 있다면 placeholder 가 아니라 boilerplate라는거...! 
사라질 파일이니 그냥 둬도 좋을 것 같아요!

2022-10-08 06:25 UTC, chaneeii approved these changes
고생하셨습니다 🥳🥳🥳

다만,,,, 아쉬운점이 있다면 이럴때 사용하는 단어가 placeholder 가 아니라 boilerplate라는거...!
사라질 파일이니 그냥 둬도 좋을 것 같아요!

2022-10-08 15:45 UTC, Lia316 requested changes
모든 세팅을 한꺼번에 완료하셨군요! 🤩🙌🏻
정말 수고 많으셨고 감사합니다! ㅎㅎ

그런데 제가 빌드를 시도해봤을 때는 안 돼서, 이 부분 확인 부탁드립니다.

그리고, 이건 정말 사소한 의견이지만 😅 폴더 순서 변경을 요청드리고 싶습니다..ㅎ
- Source - Resource 순서
- Application - Global - UI - Domain 순서
로 부탁드립니다!

2022-10-08 15:45 UTC, Lia316 commented on Projects/App/.swiftlint.yml
> +- line_length
[P3]

`  - trailing_whitespace` 추가 부탁드립니다

2022-10-08 15:45 UTC, Lia316 commented on Projects/App/Sources/Application/SceneDelegate.swift
> +    }
[P2]

```swift
    func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions) {
        guard let windowScene = (scene as? UIWindowScene) else { return }
        let window = UIWindow(windowScene: windowScene)
        window.rootViewController = ViewController()
        self.window = window
        window.makeKeyAndVisible()
    }
```
와 함께 `ViewController` 클래스를 작성해서 돌려봤는데도 빌드가 되지 않습니다..! 
혹시 고반 코드에서는 정상적으로 빌드가 되시나요? 👀

2022-10-08 15:45 UTC, Lia316 commented on Projects/App/Sources/Application/SceneDelegate.swift
> +    func sceneDidEnterBackground(_ scene: UIScene) {}
[P4]

```suggestion
```

사용하지 않는 코드는 삭제해도 좋을 것 같습니다.

2022-10-08 15:45 UTC, Lia316 commented on Projects/Network/Project.swift
> +)
[Q]

framework가 왜 필요한 친구인지 (진짜 순전히) 궁금합니다
이 폴더 안에는 어떤 파일을 넣어야하나요? 👀❓

2022-10-08 15:49 UTC, Lia316 commented on Projects/App/Sources/Application/SceneDelegate.swift
> +    }
[P4]

아, 추가로 스토리보드 파일도 삭제하고 `info.plist` 파일에서도 메인 스토리보드를 삭제하신 것 같던데
위의 코드 정도는 세팅해놔도 괜찮지 않을까요?

2022-10-09 07:24 UTC, Gobans commented on Projects/App/.swiftlint.yml
> +- line_length
[63e0ece](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/14/commits/63e0ece86864b27ba425eec9cf6845ed96f86d1d) 추가하였습니다!

2022-10-09 07:34 UTC, Gobans commented on Projects/App/Sources/Application/SceneDelegate.swift
> +    }
정말 앱을 앱을 실행시켜보니까 빌드가 안되네요..!  확인 했었어야 했는데.. 대신 찾아주셔서 감사합니다🙏
이유가 뭔가 했더니 dynamic framework 와 static framework 설정의 문제였는데, 정확하게 왜 dynamic framework를 사용하면 빌드가 안되는지는 이유를 잘 모르겠습니다. 다만 Tuist [예제](https://github.com/baekteun/Tuist_Sample)를 보면 내부에 소스코드가 있는 경우는 static framework 로 쓰고 외부 Package를 가지고 있는 module은 dynamic framework로 사용하더라구요. 일단은 현재까지는 이정도로만 인지하고 있습니다.
[dynamic framework 와 static framework 참고](https://minsone.github.io/ios/mac/ios-framework-part-1-static-framework-dynamic-framework)

ViewController와 더불어 주신 코드로 세팅을 해놓았습니다!

[c5576e0](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/14/commits/c5576e059a2c9822121a02ed94cf325e6448bc14)

2022-10-09 07:35 UTC, Gobans commented on Projects/App/Sources/Application/SceneDelegate.swift
> +    func sceneDidEnterBackground(_ scene: UIScene) {}
[d23c8a9](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/14/commits/d23c8a9fb69f885b3b75d8bca3d9dea2d2e3c89c) 삭제하였습니다!

2022-10-09 07:39 UTC, Gobans commented on Projects/Network/Project.swift
> +)
이곳에서 framework란 해당 모듈을 framework 로 취급하여 만들겠다는 설정이고, workspace에 들어있는 framework폴더는 Tuist가 자동으로 생성해주더라구요. 제 생각에는 Tuist의 Dependency.swift 로 모듈을 관리하면 framework를 resolve 해서 쓰는데, 이때 이 폴더에 들어가는게 아닌가 생각을 합니다. 혹시 나중에 테스트 해본다면 알려드릴게요!

2022-10-09 08:04 UTC, Lia316 commented on Projects/App/Sources/Application/SceneDelegate.swift
> +    }
문제 해결하시느라 수고 많으셨습니다..! 
저도 dynamic framework와 static framework에 대해서 공부해보면서 함께 이유 찾아볼게요
상세한 설명까지 덧붙여주셔서 감사합니다 :)

2022-10-09 08:06 UTC, Lia316 commented on Projects/Network/Project.swift
> +)
오.. 그렇군요 감사합니다!!

2022-10-09 08:08 UTC, Lia316 approved these changes
리뷰 반영해주셔서 감사드리고 수고 많으셨습니다~!

아주 사소한 불편함이지만,, source 와 resource 폴더 순서만 변경해주시면 정말 감사드리겠습니다..!

2022-10-09 10:16 UTC, Gobans commented
> 리뷰 반영해주셔서 감사드리고 수고 많으셨습니다~!
> 
> 아주 사소한 불편함이지만,, source 와 resource 폴더 순서만 변경해주시면 정말 감사드리겠습니다..! 그러나 [P4]라서 일단 approve 드립니다!

오.. 이 요청을 깜빡하고 지나쳤네요😂 미안해요!! 
그런데 아쉽게도 폴더 순서 변경이 어려울 것 같아요..! App 모듈의 pbxproj 파일을 뜯어서 고쳐봤는데 안되길래 찾아봤더니
https://github.com/tuist/tuist/pull/164
이런식으로 그냥 알파벳 순으로 프로젝트 파일들을 generate 해버리더라구요.😿
Tuist가 conflict를 없애주는 대신에 이렇게 조금 사소하게 불편한 점이 있네요

2022-10-09 10:38 UTC, Lia316 commented
> 오.. 이 요청을 깜빡하고 지나쳤네요😂 미안해요!!
그런데 아쉽게도 폴더 순서 변경이 어려울 것 같아요..! App 모듈의 pbxproj 파일을 뜯어서 고쳐봤는데 안되길래 찾아봤더니
https://github.com/tuist/tuist/pull/164
이런식으로 그냥 알파벳 순으로 프로젝트 파일들을 generate 해버리더라구요.😿
Tuist가 conflict를 없애주는 대신에 이렇게 조금 사소하게 불편한 점이 있네요

앗 그렇군요 😭
아닙니다 최선을 다해 반영해주려고 하셔서 감사해요!

2022-10-09 11:28 UTC, merged