[Setting] 기본 코드 템플릿 작성 및 SubView 추가를 위한 Extension 작성
DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY pull request #17
Opened 2022-10-11 09:38 UTC by Gobans

## 작업내용

- [x] 기본 코드 작성 스타일을 예제로 가지고 있는 ViewController 작성
- [x] 기본 코드 템플릿을 가지고 있는 ViewControllerTemplate 작성
- [x] 여러개의 SubView를 쉽게 추가할 수 있도록 Extension 추가

### ViewController 
- 리아 일 공백 하나하나 다 의도된 것입니다

|작업 전|작업 후|
|:---:|:---:|
|<img width="250" src="">|<img width="250" src="">|

## 리뷰포인트

## Reference

## Checklist
- [ ] 브랜치를 가져와 작업한 경우 이전 브랜치에 PR을 보냈는지 확인
- [ ] 빌드를 위해 SceneDelegate 수정한 것 PR로 올리지 않았는지 확인
- [ ] 필요없는 주석, 프린트문 제거했는지 확인
- [ ] 컨벤션 지켰는지 확인
- [ ] final, private 제대로 넣었는지 확인
- [ ] Xcode Team none 으로 되어있는지 확인

2022-10-11 12:18 UTC, italsehf approved these changes

2022-10-11 12:44 UTC, chaneeii approved these changes
LGTM👍

2022-10-11 13:16 UTC, chaneeii requested changes
@Gobans 근데 지금 봤는데, 파일명이 

UIStackView+ addArragnedSubviews 이런식인데, 이러면 UIStackView 관련한 여러 extension을 넣기에 부적합해보입니다..

하나의 파일이 하나의 extension 을 담는건 아닌거 같아서
UIStackView+ or  UIStackView+ Utils 는 어떨까요?

2022-10-11 13:53 UTC, tea-hkim approved these changes
고생하셨습니다 👍 코드 컨벤션 아닌 컨벤션이 생긴 것 같습니다. 덕분에 작업이 수월해지겠네요 :)

2022-10-11 16:22 UTC, chaneeii commented on Projects/App/Sources/Application/ViewControllerTemplate.swift
> +    private func configureUI() {
p2
configureUI 라는 표현이 너무 이상한데
`UI()` or `setUI()` 로 
변경하는 것에 어떻게 생각하시나요?

2022-10-11 16:22 UTC, chaneeii commented on Projects/App/Sources/Application/ViewControllerTemplate.swift
> +    private func configureLayout() {
p2
얘도뭔가 configureLayout말고
layout() or setLayout() 어떤가요?

2022-10-12 06:15 UTC, italsehf commented on Projects/App/Sources/Application/ViewControllerTemplate.swift
> +    private func configureUI() {
setUI() 에 한표

2022-10-12 06:16 UTC, italsehf commented on Projects/App/Sources/Application/ViewControllerTemplate.swift
> +    private func configureLayout() {
setLayout() 에 한표

2022-10-12 08:21 UTC, Lia316 commented on Projects/App/Sources/Application/ViewControllerTemplate.swift
> +    private func configureUI() {
저는 애플 공식 예제 등을 보면 `configureOOO` 이라는 표현을 종종 봐서 이렇게 제안했었습니다.

> [애플 공식 예제 코드 중](https://developer.apple.com/documentation/uikit/views_and_controls/collection_views/implementing_modern_collection_views)
<img width="1099" alt="image" src="https://user-images.githubusercontent.com/73650994/195288743-3b80277a-4f9a-420a-8bce-d5c64b15e06d.png">

또, [Configure vs Set - What's the difference?](https://wikidiff.com/set/configure) 라는 글을 보면, 
configure이라는 단어가 특정 목적을 위해 설정한다라는 의미가 담겨 있어서 
포괄적인 의미를 가진 set보다는 명확하다고 생각해서 configure이 적절하다고 생각해요!

2022-10-12 08:25 UTC, Lia316 commented on Projects/App/Sources/Application/ViewControllerTemplate.swift
> +    private func configureUI() {
그리고 덧붙이자면, 
메서드 명은  `UI`나 `layout` 같이 명사로 작명하기 보다는,
어떤 동작을 수행하는지를 나타내야한다고 생각해요..!

[클린코드](https://github.com/Yooii-Studios/Clean-Code/blob/master/Chapter%2002%20-%20의미%20있는%20이름.md)에서도 메서드 명으로는 동사구를 사용하는 것을 권장한다고 하네요~!

2022-10-12 08:27 UTC, Lia316 approved these changes
함께 작성했던 코드라서 바로 approve 드립니다 ^~^
고반 수고 많으셨어요 😁

2022-10-12 09:57 UTC, chaneeii commented on Projects/App/Sources/Application/ViewControllerTemplate.swift
> +    private func configureUI() {
단순히 사전적으로 보는게 아니라,, 언어적으로 configure 라는 표현이 ui를 그리는 부분에서 굉장히 어색하게 들립니다.

위의 코드예제와 같은 경우에는 configure 라는 표현이 적합하지만 레이아웃을 잡을때는 적합하지 않아보입니다.

configureUI 는 괜찮은데 configureLayout은 아예 말이 안되게 들려요..
언어적인 감각이라 자세하게 설명하기 어렵네요 🥲

configureUI 를 쓸꺼면 레이아웃은 setConstraints 로라도 부탁드립니다..

저도 메소드명을 동사로 하는 것은 찬성하는 바 입니다

2022-10-12 13:07 UTC, Gobans commented on Projects/App/Sources/Application/ViewControllerTemplate.swift
> +    private func configureUI() {
[f7b8768](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/17/commits/f7b8768ce11f960c7554f2efd1309cbf8cbd1fef) 수정사항 반영하였습니다!

2022-10-12 13:07 UTC, Gobans commented on Projects/App/Sources/Application/ViewControllerTemplate.swift
> +    private func configureLayout() {
[f7b8768](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/17/commits/f7b8768ce11f960c7554f2efd1309cbf8cbd1fef) 수정사항 반영하였습니다!

2022-10-12 13:21 UTC, chaneeii approved these changes
고생하셨습니다 🔥

2022-10-12 13:30 UTC, merged