[Feat] endpoint로 request 생성하기 & 응답 받기
DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY pull request #18
Opened 2022-10-12 16:34 UTC by Lia316

## 작업내용
<img width="214" alt="image" src="https://user-images.githubusercontent.com/73650994/195392315-0146944e-43cb-486f-8073-672eba08042b.png">
- [x]URLComponents로 URL 생성하기 
- [x] endpoint로 request 생성하기
- [x] JSON 데이터 request 보내기 및 응답 받기

## 다음에 할 일
- 에러 핸들링
- multipart 통신 (Alamofire로 할 생각)
- API
- Mock API
- DTO

## 리뷰포인트
- 에러 처리는 아직 미완입니다
- `Encodable+toDictionary` 는 Extension 폴더가 없어서 어디에 파일 분리해야할 지 고민입니다 ㅠ 의견 받아요!
- `NetworkService`의 `request` 메소드를 chainable하게 만들려다 보니
   에러 핸들링 메서드를 `Publisher` extension에 넣었습니다..!
   이 방법이 괜찮은지, 다른 좋은 방법은 없을지 함께 고민해보고 싶은 포인트에요!

## Reference
- 김종권 님의 블로그 :  [네트워크(network) - testable한 URLSession 설계 (Endpoint, Provider)](https://ios-development.tistory.com/719)

## Checklist
- [x] 브랜치를 가져와 작업한 경우 이전 브랜치에 PR을 보냈는지 확인
- [x] 빌드를 위해 SceneDelegate 수정한 것 PR로 올리지 않았는지 확인
- [x] 필요없는 주석, 프린트문 제거했는지 확인
- [x] 컨벤션 지켰는지 확인
- [x] final, private 제대로 넣었는지 확인
- [x] Xcode Team none 으로 되어있는지 확인

2022-10-13 00:40 UTC, Lia316 commented
@YebinKim review 요청 드려요! 
흔쾌히 수락해주셔서 감사합니다 😁

2022-10-13 01:46 UTC, chaneeii approved these changes
🎉🎉 귣귣
몇가지 개선하면 좋을 것들이 있어서 해당 부분 코멘트 남겼어요!
<img width="300" src="https://user-images.githubusercontent.com/63157395/195479588-b20d73e5-aff4-487f-ba4c-a1842dcd0157.png">

2022-10-13 01:46 UTC, chaneeii commented on Projects/Network/Sources/Service/NetworkService.swift
> +protocol NetworkServiceable {
p1
typo -> NetworkServable

2022-10-13 01:46 UTC, chaneeii commented on Projects/Network/Sources/EndPoint/ResponseRequestable.swift
> +        return jsonData as? [String: Any]
p3
옵셔널 처리를 해보는건 어떨까요??

```suggestion
guard let data = try? JSONEncoder().encode(self) else { return [:] }
guard let dictionary = try? JSONSerialization.jsonObject(with: data, options: .allowFragments) as? [String: Any] else { return [:] }
return dictionary
```

2022-10-13 01:46 UTC, chaneeii commented on Projects/Network/Sources/EndPoint/ResponseRequestable.swift
> +protocol ResponseRequestable {
💬 질문
이건 혹시 이름 뜻이 뭘까요..?

request할만한 응답....? 
레퍼 주신건 RequestReponsable 인데 얘는 반대라 궁금합니당

2022-10-13 01:46 UTC, chaneeii commented on Projects/Network/Sources/Service/NetworkError.swift
> +}
🎉 제안
LocalizedError 를 사용해보는거 어떨까요?

- 레퍼 : https://ios-development.tistory.com/849

2022-10-13 01:46 UTC, chaneeii commented on Projects/Network/Sources/Service/NetworkError.swift
> +}
```
case invalidRequest
case badRequest
case unauthorized
case forbidden
case notFound
case error4xx(_ code: Int)
case serverError
case error5xx(_ code: Int)
case decodingError
case urlSessionFailed(_ error: URLError)
case unknownError
```

2022-10-13 01:46 UTC, chaneeii commented on Projects/Network/Sources/EndPoint/ResponseRequestable.swift
> +    var method: HttpMethod { get }
p3

요거 enum 처리하는거 어떨까요?

```swift
접근지저장 enum HTTPMethod: String {
      case get     = "GET"
      case post    = "POST"
      case put     = "PUT"
      case patch    = "PATCH"
      case delete  = "DELETE"
}
```

2022-10-13 02:55 UTC, Lia316 commented on Projects/Network/Sources/EndPoint/ResponseRequestable.swift
> +    var method: HttpMethod { get }
Endpoint 파일에 작성되어 있습니다!

2022-10-13 02:56 UTC, Lia316 commented on Projects/Network/Sources/Service/NetworkError.swift
> +}
네트워크 에러 처리는 2nd or 3rd sprint에 작성할 거라 그 때 추가하도록 하겠습니다!
말씀해주셔서 감사합니다 ㅎㅎ

2022-10-13 03:03 UTC, Lia316 commented on Projects/Network/Sources/EndPoint/ResponseRequestable.swift
> +protocol ResponseRequestable {
음 그냥 응답도 요청도 가능한 친구 == 엔드포인트 라고 생각해서 작명했습니다.

이 프로토콜이 다른 곳에서 참고했던 코드에서도 나와서 사용했는데,
[clean architecture + mvvm 예제](https://github.com/kudoleh/iOS-Clean-Architecture-MVVM) 여길 보면 제가 작성한 것처럼 반대로 적혀있습니다.

레퍼를 보시면, 
```swift
protocol Requestable { }
protocol Responsable { }
protocol RequesteResponsable: Requestable, Responsable {}
class Endpoint<R>: RequesteResponsable { }
```
이렇게 작성되어 있는데, 이런 식으로 둘 다 가능하다는 의미로 보시면 될 것 같아요!

2022-10-13 03:04 UTC, Lia316 commented on Projects/Network/Sources/Service/NetworkService.swift
> +protocol NetworkServiceable {
언어적 맥락에서 네이밍은 버리 의견 무조건 따르겠습니다 🔥

2022-10-13 03:06 UTC, Lia316 commented on Projects/Network/Sources/Service/NetworkService.swift
> +protocol NetworkServiceable {
[a45f125](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/18/commits/a45f125743ff8aa3fc8955c5be160f60f631dff4) 반영했습니다! 감사드려요

2022-10-13 03:33 UTC, Lia316 commented on Projects/Network/Sources/EndPoint/ResponseRequestable.swift
> +        return jsonData as? [String: Any]
현재 try 코드들은 모두 throw를 통해서 에러가 `NetworkServable`까지 전달되기 때문에, 
`RequestReponsable` 의 모든 코드는 에러를 뿜게 작성했습니다.

제안해주신 대로 옵셔널 바인딩을 하면 `return [:]` 같이 의미없는 빈 값을 전달하게 되는데,
네트워크 통신 과정 상에서는 빈 값을 전달하기 보다는 확실하게 실패했다는 에러를 전달하는 것이 더 중요하다고 저는 생각합니다!

2022-10-13 03:40 UTC, chaneeii commented on Projects/Network/Sources/EndPoint/ResponseRequestable.swift
> +protocol ResponseRequestable {
넵 👍

2022-10-13 03:40 UTC, Gobans commented
세션 시간중에 많은 설명과 궁금증을 해결해주셔서 코드를 이해할 수 있었습니다. 문제 될만한 부분을 저의 기준에서 찾지 못해서 Approve 하겠습니다!! 🔥 에러처리의 기반이 잘 닦인 깔끔한 코드같아서 마음이 편안하고 소화가 잘되네요 🧚‍♀️

2022-10-13 03:41 UTC, Gobans approved these changes

2022-10-13 03:42 UTC, chaneeii approved these changes

2022-10-13 05:03 UTC, Gobans requested changes
맞다 리아 .swiftyml 을 각 모듈에 만들고 rule에
```swift
identifier_name:
    excluded:
        - id
```
추가해주실 수 있나요?

2022-10-13 05:33 UTC, Lia316 commented
> 맞다 리아 .swiftyml 을 각 모듈에 만들고 rule에
> 
> ```swift
> identifier_name:
>     excluded:
>         - id
> ```
> 
> 추가해주실 수 있나요?

아 잊어버릴 뻔 했는데 말씀해주셔서 정말 감사합니다! 
[c349cd1](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/18/commits/c349cd19d73e39790206d7e64017f8982081abc8) 반영했습니다!

2022-10-13 05:36 UTC, Lia316 commented
> toDictionary 메소드가 여러곳에서 쓰인다면 Extension 폴더를 파서 Encodable+ 로 파일 만드는게 좋을 것 같습니다.

현재 느낌으로는 이 이상으로 메서드가 쓰일 것 같지 않긴 합니다.
이 부분은 나중에 extension이 더 작성되거나, toDictionary 메서드가 여러 곳에서 쓰이게 될 때 분리해도 괜찮을까요?

2022-10-13 06:18 UTC, italsehf approved these changes
여러분들이 있어서 든든해요👏🏻👏🏻
제가 아직 많이 부족해서 완벽하게 코드를 이해하지 못해
자세하게 코드 리뷰하지 못하는 점 고멘네..
얼른 공부해서 코드 이해 안되는 부분 있으면 질문할게요 !!

2022-10-13 07:43 UTC, Gobans commented on Projects/DesignSystem/.swiftlint.yml
> +  - Sources/Application/SceneDelegate.swift
요것들은 DesignSystem 모듈에 없는거라 삭제해도 좋을 것 같아요!

2022-10-13 07:43 UTC, Gobans commented on Projects/Network/.swiftlint.yml
> +  - Sources/Application/SceneDelegate.swift
위와마찬가지입니다!

2022-10-13 07:43 UTC, Gobans commented
> > toDictionary 메소드가 여러곳에서 쓰인다면 Extension 폴더를 파서 Encodable+ 로 파일 만드는게 좋을 것 같습니다.
> 
> 현재 느낌으로는 이 이상으로 메서드가 쓰일 것 같지 않긴 합니다. 이 부분은 나중에 extension이 더 작성되거나, toDictionary 메서드가 여러 곳에서 쓰이게 될 때 분리해도 괜찮을까요?

넵!! 그렇게 하면 충분할 것 같아용

2022-10-13 07:44 UTC, Lia316 commented on Projects/DesignSystem/.swiftlint.yml
> +  - Sources/Application/SceneDelegate.swift
무지성 복붙 죄송합니다

2022-10-13 07:48 UTC, Lia316 commented on Projects/Network/.swiftlint.yml
> +  - Sources/Application/SceneDelegate.swift
두 모듈 다 반영했습니다! [e63c737](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/18/commits/e63c73722d5c9590023db47787dfabbb230cbdbe)
꼼꼼히 리뷰해주셔서 감사합니다!

2022-10-13 08:12 UTC, Gobans commented on Projects/Network/.swiftlint.yml
> +  - Sources/Application/SceneDelegate.swift
빠른 수정 감사합니다!😸

2022-10-13 08:13 UTC, Gobans approved these changes

2022-10-13 12:11 UTC, chaneeii requested changes
🫰

2022-10-13 12:11 UTC, chaneeii commented on Projects/Network/Sources/Service/NetworkService.swift
> +protocol  NetworkServable {
p1
띄어쓰기 1칸으로 해주세요!

2022-10-13 12:11 UTC, chaneeii commented on Projects/Network/Sources/EndPoint/Endpoint.swift
> +}
p2)
이 엔드포인트는 response 역할을 하지않는데 왜 ResponseRequestable 을 채택한건가요?
다 request 에 사용하는 애들이네요🧐

2022-10-13 12:11 UTC, chaneeii commented on Projects/Network/Sources/EndPoint/ResponseRequestable.swift
> +protocol ResponseRequestable {
p3)
요거 다시 논란거리로 만들어서 죄송합니당..

```swift
// 김종권님코드!
protocol RequestResponsable: Requestable, Responsable {}

class Endpoint<R>: RequestResponsable {
    typealias Response = R
```

이 이름이 의미를 가지려면 우선  이런식으로 두가지 모두 채택을 하고 있어야 의미가 있을 것 같습니다.. 
지금으로서는 다시 이해해보려했는도 이해가 안가네요ㅠ

🧐🧐🧐근본적인 역할에 대한 의문
결국 response 역할을 안하고 있는데 RequestResponsable이 아니라 
현재로서는 Requestable 이 적절한것같고
차라리 Responsable 을 따로 두고 제네릭을 두개 받는게 어떨까요?

----------

2022-10-13 12:11 UTC, chaneeii commented on Projects/Network/Sources/Service/NetworkService.swift
> +    func request<E: ResponseRequestable, T: Decodable>(with endpoint: E, responseType: T.Type)
p1)

김종권님 블로그를 꼼꼼히 읽어보니깐  이렇게 있는데

![스크린샷 2022-10-13 오후 9 02 21](https://user-images.githubusercontent.com/63157395/195590946-7958385e-c0c5-4b35-ab75-d3aae49b0d71.png)


> 단순히 URL을 request로 주어, Data를 얻는 request (ex - 이미지 url을 넣고 이미지 Data 얻어오는 경우 사용)

1.  즉, 이미지용인데 이부분은 저희는 kingfisher 를 사용하니깐 필요 없지 않을까요?

2.  또한 요걸 get, delete 와 post, put을 따로 작성한 이유가 무엇일까요?
한가지로 합쳐도 되지않을까요?

2022-10-13 12:54 UTC, YebinKim reviewed
리아 안녕하세요~
protocol 을 활용해 네트워킹 타입들을 잘 분리하셨음이 굉장히 눈에 띄었어요!! 🤩🙌

`Encodable+toDictionary 는 Extension 폴더가 없어서 어디에 파일 분리해야할 지` 에 대한 고민은 추후 `Encodable` 타입에 대한 확장 가능성이 많진 않아보이고 해당 파일(`ResponseRequestable.swift`) 안에서만 사용할 것으로 보여서 fileprivate 등으로 접근제어를 높이면 어떨까 하는 생각이 드네요 🤔

고생 많으셨어요~!! 🐿

2022-10-13 12:54 UTC, YebinKim commented on Projects/Network/Sources/EndPoint/Endpoint.swift
> +         headers: [String: String]? = [:]) {
p3;

옵셔널 타입이지만 초기값으로 빈 딕셔너리를 전달하는 이유가 무엇일까요?

2022-10-13 12:54 UTC, YebinKim commented on Projects/Network/Sources/EndPoint/ResponseRequestable.swift
> +    func getUrlRequest() throws -> URLRequest {
p3;

Swift 언어는 반환받는 값이 명확하다면 get 네이밍을 지양하고 있습니다!
아래 `private func url() throws -> URL` 메서드와 같이 get 을 생략하고 네이밍을 작성해보면 어떨까요?

2022-10-13 12:54 UTC, YebinKim commented on Projects/Network/Sources/EndPoint/ResponseRequestable.swift
> +            if !bodyParams.isEmpty {
p3;

혹시 guard 구문의 사용도 생각해보셨을까요?

2022-10-14 01:20 UTC, Lia316 commented on Projects/Network/Sources/Service/NetworkService.swift
> +protocol  NetworkServable {
앗 린트가 왜 안 잡아줬을까요? 😂
린트 대신 잡아주셔서 감사합니다! [c33ce60](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/18/commits/c33ce607c1e8e3031e1c4c7a0a95c957c633485a) 반영했습니다!

2022-10-14 01:25 UTC, Lia316 commented on Projects/Network/Sources/Service/NetworkService.swift
> +    func request<E: ResponseRequestable, T: Decodable>(with endpoint: E, responseType: T.Type)
아하 삭제하겠습니다. 
처음에는 간단한 request 정도는 endpoint를 다 넣지 않고 그냥 가져와도 괜찮지 않을까? 싶어서 분리한 거였지만, 
지금 보니 굳이 그럴 필요도 없겠다는 생각이 드네요.

2022-10-14 01:26 UTC, Lia316 commented on Projects/Network/Sources/Service/NetworkService.swift
> +    func request<E: ResponseRequestable, T: Decodable>(with endpoint: E, responseType: T.Type)
[fc36e95](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/18/commits/fc36e95e87b919e09f04db0ad31b71b89502b3ab) 반영 완료했습니다!

2022-10-14 01:30 UTC, Lia316 commented on Projects/Network/Sources/EndPoint/Endpoint.swift
> +}
말씀하신대로 response 역할을 할 때 의미를 부여하는 게 더 적절하다고 이해해서 리뷰 반영했습니다!
[b70d12b](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/18/commits/b70d12b46f60b76b51ceeb33c5aed4277351ddba)
다시 한 번 꼼꼼히 봐주셔서 감사합니다!

2022-10-14 01:31 UTC, Lia316 commented on Projects/Network/Sources/EndPoint/ResponseRequestable.swift
> +protocol ResponseRequestable {
[b70d12b](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/18/commits/b70d12b46f60b76b51ceeb33c5aed4277351ddba) 반영했습니다! 
말씀하신대로 현재 의미로 적절한 Requestable로 프로토콜 명을 수정했습니다

2022-10-14 01:40 UTC, Lia316 commented on Projects/Network/Sources/EndPoint/Endpoint.swift
> +         headers: [String: String]? = [:]) {
리뷰 감사합니다 😁
덕분에 옵셔널 타입의 초기값에 대해 다시 생각해볼 수 있었습니다!

추후에 ["Content-Type": "application/json"] 과 같이 주로 쓰이는 헤더를 써둘 생각으로 일단 남겨놨습니다.
약간 TODO 같은 느낌으로 남겨놨는데, 현 시점에서 삭제하는 게 더 좋다면 삭제하겠습니다!

2022-10-14 01:42 UTC, Lia316 commented on Projects/Network/Sources/EndPoint/ResponseRequestable.swift
> +    func getUrlRequest() throws -> URLRequest {
네이밍 명심하겠습니다! 
변경했습니다 [39fe154](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/18/commits/39fe15428654c4acc5f3273db747e47342884eee) 
말씀해주셔서 감사드립니다 :)

2022-10-14 01:50 UTC, Lia316 commented on Projects/Network/Sources/EndPoint/ResponseRequestable.swift
> +            if !bodyParams.isEmpty {
리뷰 감사드려요! 
guard 구문과 if 구문 중 뭐가 더 적절할 지 말씀해주셔서 생각해보게 되었습니다.

Endpoint에서 httpBody가 없는 경우도 받고 있어서 
guard 구문 보다는 if 구문을 통해서 이후 코드도 실행할 수 있는 것이 더 좋을 것 같다고 판단했습니다!

2022-10-14 01:54 UTC, Lia316 commented
@chaneeii  @YebinKim  두 분 모두 리뷰해주셔서 정말 감사드립니다!
말씀하신 부분 중에 반영한 것도 있고, 제 생각을 코멘트로 남긴 것이 있습니다. 

저희 팀 브랜치 규칙이 모든 conversation resolve 여서 완료된 리뷰에는 resolve 부탁드립니다!

2022-10-14 02:29 UTC, chaneeii approved these changes
🎉

2022-10-14 02:51 UTC, tea-hkim approved these changes
공유해주신 블로그 글을 보고 이해하고 오느라 리뷰가 늦었습니다!
코드가 체계적으로 잘 짜여 있어서 마음이 편안해집니다 :)
수고하셨습니다!

2022-10-14 05:04 UTC, YebinKim commented on Projects/Network/Sources/EndPoint/Endpoint.swift
> +         headers: [String: String]? = [:]) {
그런 의도였군요!
현 시점에서 사용하지 않는다면 레거시가 되는 것을 방지하기 위해 삭제하는 게 어떨까 싶습니다 😄

2022-10-14 05:06 UTC, YebinKim commented
@Lia316 
리아~ 제가 `Encodable+toDictionary 는 Extension 폴더가 없어서 어디에 파일 분리해야할 지` 에 대해 fileprivate 을 추천드린 부분은 정확히 얘기하자면 extension 자체의 접근제어 수준을 높이는 것이었어요! 현재와 같이 메서드에 붙이는 것도 괜찮지만, 정확한 의도를 전달드리고자 덧붙여봅니다!

2022-10-14 05:24 UTC, Lia316 commented on Projects/Network/Sources/EndPoint/Endpoint.swift
> +         headers: [String: String]? = [:]) {
넵 현재 필요한 코드만 남겨두겠습니다~!
[0942c03](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/18/commits/0942c03cab269137bae98aa7e9dfd8382ae638fe) 반영했습니다!

2022-10-14 05:25 UTC, Lia316 commented
> @Lia316
> 리아~ 제가 `Encodable+toDictionary 는 Extension 폴더가 없어서 어디에 파일 분리해야할 지` 에 대해 fileprivate 을 추천드린 부분은 정확히 얘기하자면 extension 자체의 접근제어 수준을 높이는 것이었어요! 현재와 같이 메서드에 붙이는 것도 괜찮지만, 정확한 의도를 전달드리고자 덧붙여봅니다!

@YebinKim [20d578c](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/18/commits/20d578cad0a49d100126113cee9bcd51a9ab17dc) extension으로 접근 제어 위치를 수정했습니다! 감사합니다

2022-10-14 06:07 UTC, merged