Feat/signup/zes 109 base UI
DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY pull request #22
Opened 2022-10-14 03:34 UTC by Gobans

## 작업내용

- [x] 로그인 / 닉네임 입력 / 회원가입 UI 작업
- [x] 공용 컴포넌트 ShadowButtonView, UITextFieldPadding 작업 
- [x] 필요없는 PR 수정

|로그인|닉네임 입력|닉네임 입력|회원가입 완료|
|:---:|:---:|:---:|:---:|
|<img width="250" src="https://user-images.githubusercontent.com/56781342/195753513-79dcbe38-1b23-49b1-b010-f569e9d6b170.png">|<img width="250" src="https://user-images.githubusercontent.com/56781342/195753522-96daf155-8a3d-4f45-8f0e-3ebe9ca27afa.png">|<img width="250" src="https://user-images.githubusercontent.com/56781342/195753528-29caa119-0fd9-41f7-936f-7420b7d42a06.png">|<img width="250" src="https://user-images.githubusercontent.com/56781342/195753524-e4dc9c75-1bf0-45cb-a043-5879cadf0a01.png">|

### 로그인 / 닉네임 입력 / 회원가입 UI 작업
- Color 는 아직 제대로 안맞췄고 (color Extension 나오면 그때 작업 하려합니다) Font는 크기만 맞췄어요. 나중에 UI Design 을 다시 해서 PR 보내려 합니다.

### 공용 컴포넌트 ShadowButtonView, UITextFieldPadding
- DesignSystem에 두가지 컴포넌트를 추가했습니다.
- 조금 특이사항이 있습니다. ShadowButtonView의 tittle 을 설정할때 ShadowButtonView.button.**setAttributedTitle** 을 사용해서 title을 설정해야 합니다..! 이렇게 안하면 폰트가 안먹어요😿

### 필요없는 PR 수정
- `Xcode Team none 으로 되어있는지 확인` 이 문구가 Tuist를 사용하면서 필요가 없어졌기 때문에 (tuist generate 할때 none 으로 초기화 되요) 삭제 하였습니다.

## 리뷰포인트

- @YebinKim 리뷰 부탁드립니다!! 🙌
- PR 폭탄 죄송합니다. Task 를 너무 크게 잡았어요🙀 다음부터는 잘 나눠서 올리겠습니다.
- NickNameInputViewController 에 UI 기능들이 조금 많이 들어있어서, 이 부분을 중점적으로 봐주시면 감사하겠습니다. 
- ++ 공용 Component도!

## Checklist
- [x] 브랜치를 가져와 작업한 경우 이전 브랜치에 PR을 보냈는지 확인
- [x] 빌드를 위해 SceneDelegate 수정한 것 PR로 올리지 않았는지 확인
- [x] 필요없는 주석, 프린트문 제거했는지 확인
- [x] 컨벤션 지켰는지 확인
- [x] final, private 제대로 넣었는지 확인

2022-10-14 05:10 UTC, italsehf approved these changes
빠른 작업 감사합니다 고반✨
제가 남긴 코멘트들은 다 사소한 것들이니 한번씩 가볍게 확인만 해주시면 될 거 같아요 :)

2022-10-14 05:10 UTC, italsehf commented on Projects/App/Sources/Global/Extension/UITextField+addInset.swift
> +//        let leftEdge =
p5
필요하지 않은 주석이라면 삭제 부탁드려요!

2022-10-14 05:10 UTC, italsehf commented on Projects/App/Sources/UI/User/Signup/ViewModel/NickNameInputViewModel.swift
> +}
p5
기본 코드 템플릿 참고했을 때 마지막에 공백 한 줄 추가해야하는 것으로 알고 있는데 맞을까요??

2022-10-14 05:10 UTC, italsehf commented on Projects/App/Sources/UI/User/Signup/Views/NickNameInputViewController.swift
> +}
p5
위에 남긴 제 코멘트가 맞다면 여기도 공백 한 줄 추가해주세요 ~!

2022-10-14 05:10 UTC, italsehf commented on Projects/DesignSystem/Sources/Component/ShadowButtonView.swift
> +        button.titleLabel?.font = .systemFont(ofSize: 17, weight: .bold)
p4
폰트 사이즈가 17이라고 되어있는데 혹시 .body가 아니라 17로 작성하신 이유가 따로 있을까요??

2022-10-14 05:10 UTC, italsehf commented on Projects/App/Sources/UI/User/Signup/Views/SignupCompleteViewController.swift
> +        nickNameLabel.font = .systemFont(ofSize: 17, weight: .semibold)
p4
폰트 사이즈 17 + .semibold 면 혹시 .headline이 아니라 직접 입력하여 작성하신 이유가 따로 있을까요??

2022-10-14 05:10 UTC, italsehf commented on Projects/App/Sources/UI/User/Signup/Views/SignupCompleteViewController.swift
> +                                                       attributes: [.font: UIFont.systemFont(ofSize: 13)])
p4
이 부분도 폰트 사이즈가 .footnote가 아니라 직접 13으로 입력하신 이유가 궁금합니다!

2022-10-14 05:19 UTC, Gobans commented on Projects/App/Sources/Global/Extension/UITextField+addInset.swift
> +//        let leftEdge =
[62700b2](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/22/commits/62700b27ce7222bbb25ece0f4e200f4597fa4295) 전에 쓰다가 만건데 여기에 흘러 들어갔네요. 삭제했습니다!

2022-10-14 05:20 UTC, Gobans commented on Projects/App/Sources/UI/User/Signup/ViewModel/NickNameInputViewModel.swift
> +}
[6372e8b](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/22/commits/6372e8ba3dc354b4c1c8b4419cae02f48ec4ebfc) 그렇네요🙀 공백확인 감사합니다!

2022-10-14 05:20 UTC, Gobans commented on Projects/App/Sources/UI/User/Signup/Views/NickNameInputViewController.swift
> +}
[6372e8b](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/22/commits/6372e8ba3dc354b4c1c8b4419cae02f48ec4ebfc) 삭제하였습니다!

2022-10-14 05:21 UTC, Gobans commented on Projects/DesignSystem/Sources/Component/ShadowButtonView.swift
> +        button.titleLabel?.font = .systemFont(ofSize: 17, weight: .bold)
이 부분은 아마 bold라 썼던 것 같은데 필요없는 코드라 삭제하였습니다! [5fee6f7](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/22/commits/5fee6f74308b19db7dc2be236973138c1ec5ed7f)

2022-10-14 05:21 UTC, Gobans commented on Projects/App/Sources/UI/User/Signup/Views/SignupCompleteViewController.swift
> +        nickNameLabel.font = .systemFont(ofSize: 17, weight: .semibold)
저의 실수입니다 세심한 확인 감사합니다! [bb9052e](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/22/commits/bb9052e48f95a6e02cd1620f5078b779ff239b4f)

2022-10-14 05:22 UTC, Gobans commented on Projects/App/Sources/UI/User/Signup/Views/SignupCompleteViewController.swift
> +                                                       attributes: [.font: UIFont.systemFont(ofSize: 13)])
수정하였습니다! [bb9052e](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/22/commits/bb9052e48f95a6e02cd1620f5078b779ff239b4f)

2022-10-14 05:35 UTC, chaneeii requested changes
🔥 고생하셨습니다
몇가지 리뷰사항 적어두었으니 확인해주세요

2022-10-14 05:35 UTC, chaneeii commented on Projects/App/Resources/Assets.xcassets/AppleLogin.imageset/Contents.json
> +  }
p1
나중에 design system 모듈로 이사해주세요

2022-10-14 05:35 UTC, chaneeii commented on Projects/App/Resources/Assets.xcassets/KakaoLogin.imageset/Contents.json
> +}
p1
나중에 design system 모듈로 이사해주세요

2022-10-14 05:35 UTC, chaneeii commented on Projects/App/Resources/Assets.xcassets/ZESTER_ONE.imageset/Contents.json
> +}
p1
나중에 design system 모듈로 이사해주세요

2022-10-14 05:35 UTC, chaneeii commented on Projects/App/Resources/Assets.xcassets/ZESTER_THREE.imageset/Contents.json
> +  }
p1
나중에 design system 모듈로 이사해주세요

2022-10-14 05:35 UTC, chaneeii commented on Projects/App/Sources/Application/SceneDelegate.swift
>      }
p3
저희 씬델리게이트는 안건드리기로 한것같은데 요거 건드려도 되는 부분인가요?

2022-10-14 05:35 UTC, chaneeii commented on Projects/App/Sources/Global/Extension/UITextField+addInset.swift
> +}
p1
사용하지 않는 코드같아보이는데 삭제해주시거나 주석으로 명확하게 역할 알려주세요

2022-10-14 05:35 UTC, chaneeii commented on Projects/App/Sources/UI/User/Login/Views/ThirdPartyLoginViewController.swift
> +            make.trailing.equalTo(view.snp.trailing).offset(-20)
p5

스냅킷 사용팁 공유요 

```suggestion
            make.leading.trailing.equalTo(view.snp.leading).inset(20)
```

2022-10-14 05:35 UTC, chaneeii commented on Projects/App/Sources/UI/User/Signup/ViewModel/NickNameInputViewModel.swift
> +        return string == ""
p3
1. .isEmpty 는 어떨까요?
2. string 보다는 좀더 의미 있는 변수명이 좋을 것 같습니다

2022-10-14 05:35 UTC, chaneeii commented on Projects/App/Sources/UI/User/Signup/ViewModel/NickNameInputViewModel.swift
> +}
p3
object 보다는 의미 있는 변수명이 좋을 것 같습니다

2022-10-14 05:35 UTC, chaneeii commented on Projects/App/Sources/UI/User/Signup/ViewModel/NickNameInputViewModel.swift
> +    @Published var isKeyBoardShown = false
p2)
Keyboard 로 해주세요,, 약간 불편하네요 😂
GoBan 느낌

2022-10-14 05:35 UTC, chaneeii commented on Projects/App/Sources/UI/User/Signup/ViewModel/NickNameInputViewModel.swift
> +import Combine
p1)
순서 신경 써주세요~~
1. 퍼스트파티 알파벳순
Combine -> UIKit

2. 퍼스트파티 이외 알파벳순

2022-10-14 05:35 UTC, chaneeii commented on Projects/App/Sources/UI/User/Signup/Views/NickNameInputViewController.swift
> +import DesignSystem
p1)
순서
1. C->U
2. DesignSystem

2022-10-14 05:35 UTC, chaneeii commented on Projects/App/Sources/UI/User/Signup/Views/NickNameInputViewController.swift
> +    private var keyBoardDownConstraints: NSLayoutConstraint?
p3)
typo -> keyboard

2022-10-14 05:35 UTC, chaneeii commented on Projects/App/Sources/UI/User/Signup/Views/NickNameInputViewController.swift
> +        nextButtonView.button.setAttributedTitle(NSAttributedString(string: "다음", attributes: [NSAttributedString.Key.font: UIFont.systemFont(ofSize: 17, weight: .bold)]), for: .normal)
p3)
상당히 긴데 여러줄로 끊는건 어떨까요?

2022-10-14 05:35 UTC, chaneeii commented on Projects/App/Sources/UI/User/Signup/Views/NickNameInputViewController.swift
> +    }
💬 to @all
저희 bindui 를 그냥 fuction 들이랑 같이 두기보다는 extension 을 따로빼거나 configureUI 그친구들 근처에 두는 건 어떨까요?
중요한 부분인데 다른 일반함수들이랑 섞이니깐 보기 애매하네용

2022-10-14 05:35 UTC, chaneeii commented on Projects/App/Sources/UI/User/Signup/Views/NickNameInputViewController.swift
> +        nickNameTextField.delegate = self
p3)
combine 을 사용하는데
delegate 가 필요한 이유가 궁금합니다..!

2022-10-14 05:35 UTC, chaneeii commented on Projects/App/Sources/UI/User/Signup/Views/SignupCompleteViewController.swift
> +
p3)
라벨을 바닥기준으로 offsset을 맞춰주셨는데, 다양한 레이아웃에 대응할 수 있도록 버튼 top 기준으로 맞춰주세요

2022-10-14 05:35 UTC, chaneeii commented on Projects/App/Sources/UI/User/Signup/Views/SignupCompleteViewController.swift
> +
p1)
우리에겐 view.addSubviews 가 있습니당 ⛏⛏⛏

2022-10-14 05:35 UTC, chaneeii commented on Projects/App/Sources/UI/User/Signup/Views/SignupCompleteViewController.swift
> +                                                                     attributes: [NSAttributedString.Key.font: UIFont.systemFont(ofSize: 17, weight: .bold)]), for: .normal)
p5)
for 도 한줄 띄워주는건 어떤가요?

2022-10-14 05:35 UTC, chaneeii commented on Projects/DesignSystem/Sources/Component/ShadowButtonView.swift
> +    private let buttonShadowView = UIView()
p4)
위에는 public 아래는 private인 이유가 있을까요?

2022-10-14 05:35 UTC, chaneeii commented on Projects/DesignSystem/Sources/Component/ShadowButtonView.swift
> +        buttonShadowView.backgroundColor = state ? .lightGray : .black
p4)
setDisable`d` 가 좋을 것 같습니다~

그리고 라이트 그레이 말고 다른걸로 나중에 잊지말아요~!~🚀

2022-10-14 05:35 UTC, chaneeii commented on Projects/DesignSystem/Sources/Component/ShadowButtonView.swift
> +
p3)
addSubviews! 를 써줍시당

2022-10-14 05:35 UTC, chaneeii commented on Projects/DesignSystem/Sources/Component/UITextFieldPadding.swift
> +    public init(top: CGFloat, left: CGFloat, bottom: CGFloat, right: CGFloat) {
p5)
요거 사용법 적어주시면 감사합니다 🙏

2022-10-14 05:35 UTC, chaneeii commented on Projects/DesignSystem/Sources/Component/UITextFieldPadding.swift
> +    var padding: UIEdgeInsets
p3)
이친구 접근지정자는 있어야하지않을까요?

2022-10-14 05:42 UTC, Lia316 commented on Projects/App/Sources/UI/User/Signup/Views/NickNameInputViewController.swift
> +    }
중요한 부분이라 메서드들 중에서는 가장 위에 있었으면 하긴 합니다
extension 찬성이요~

2022-10-14 06:03 UTC, YebinKim requested changes
고반(High Half) 안녕하세요~
UI 코드의 구조가 일관성 있고 깔끔하네요!

일부 기기에서 레이아웃 깨짐이 있어 해당 부분 먼저 확인 부탁드립니다 😄

#### 1. iPhone13 Pro 기기에서 애플 로그인 버튼 UI 깨짐
<img width="200" alt="Layout1" src="https://user-images.githubusercontent.com/38066039/195773611-af3b81e8-8a58-4221-9ed2-37e7307e7b44.png">

#### 2. 가로모드에서 버튼 동작 불가능
<img width="400" alt="Layout2" src="https://user-images.githubusercontent.com/38066039/195773651-b5370e4c-6659-4600-93f8-dff9f8bdbdb3.png">

2022-10-14 06:03 UTC, YebinKim commented on Projects/App/Sources/Global/Extension/UITextField+addInset.swift
> +}
p2;

어떤 의도의 extension 이었을까요?? 불필요한 코드라면 삭제가 필요해보입니다~

2022-10-14 06:06 UTC, Gobans commented on Projects/App/Sources/Application/SceneDelegate.swift
>      }
요거 navigationController 만 덧붙여서 테스팅 할때 화면 이동 편하게 하려고 의도적으로 수정한거라 상관없습니다!

2022-10-14 06:06 UTC, YebinKim commented on Projects/App/Sources/Global/Extension/UITextField+addInset.swift
> +}
는 이미 @italsehf 의 코멘트에서 언급되었군요..?! 코멘트는 Resolve 처리 하겠습니다 ㅎㅎㅎ

2022-10-14 06:07 UTC, Gobans commented on Projects/App/Sources/Global/Extension/UITextField+addInset.swift
> +}
삭제하였습니다! [5fee6f7](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/22/commits/5fee6f74308b19db7dc2be236973138c1ec5ed7f)

2022-10-14 06:22 UTC, Gobans commented on Projects/App/Sources/UI/User/Login/Views/ThirdPartyLoginViewController.swift
> +            make.trailing.equalTo(view.snp.trailing).offset(-20)
`make.leading.trailing.equalToSuperview().inset(20)`
이렇게 맞나요? 에버리가 한걸로하면 뷰가 날라가요🎃

2022-10-14 06:51 UTC, Gobans commented on Projects/App/Resources/Assets.xcassets/AppleLogin.imageset/Contents.json
> +  }
[584b559](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/22/commits/584b559dd11c675947afd39fbc65a673ce20a4f2) .swftyml 룰 추가 후 이사했습니다!

2022-10-14 06:51 UTC, Gobans commented on Projects/App/Resources/Assets.xcassets/KakaoLogin.imageset/Contents.json
> +}
[584b559](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/22/commits/584b559dd11c675947afd39fbc65a673ce20a4f2) .swftyml 룰 추가 후 이사했습니다!

2022-10-14 06:52 UTC, Gobans commented on Projects/App/Resources/Assets.xcassets/ZESTER_ONE.imageset/Contents.json
> +}
[584b559](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/22/commits/584b559dd11c675947afd39fbc65a673ce20a4f2) .swftyml 룰 추가 후 이사했습니다!

2022-10-14 06:52 UTC, Gobans commented on Projects/App/Resources/Assets.xcassets/ZESTER_THREE.imageset/Contents.json
> +  }
[584b559](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/22/commits/584b559dd11c675947afd39fbc65a673ce20a4f2) .swftyml 룰 추가 후 이사했습니다!

2022-10-14 06:58 UTC, Gobans commented on Projects/App/Sources/UI/User/Signup/ViewModel/NickNameInputViewModel.swift
> +        return string == ""
[c5973ee](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/22/commits/c5973eeba712a7edb7a51c3bf7e33e17807fe786) 반영완료

2022-10-14 06:58 UTC, Gobans commented on Projects/App/Sources/UI/User/Signup/ViewModel/NickNameInputViewModel.swift
> +}
[c5973ee](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/22/commits/c5973eeba712a7edb7a51c3bf7e33e17807fe786) 반영완료

2022-10-14 06:58 UTC, Gobans commented on Projects/App/Sources/UI/User/Signup/ViewModel/NickNameInputViewModel.swift
> +}
> p3
> object 보다는 의미 있는 변수명이 좋을 것 같습니다

[c5973ee](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/22/commits/c5973eeba712a7edb7a51c3bf7e33e17807fe786) 반영완료

2022-10-14 07:03 UTC, Gobans commented on Projects/App/Sources/UI/User/Signup/ViewModel/NickNameInputViewModel.swift
> +    @Published var isKeyBoardShown = false
그럼 오히려 맞을수도?? 하지만 반영완료 [bb3000b](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/22/commits/bb3000ba6fca28297999e145b190fb13176f6a62)

2022-10-14 07:03 UTC, Gobans commented on Projects/App/Sources/UI/User/Signup/Views/NickNameInputViewController.swift
> +    private var keyBoardDownConstraints: NSLayoutConstraint?
반영완료 [bb3000b](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/22/commits/bb3000ba6fca28297999e145b190fb13176f6a62)

2022-10-14 07:03 UTC, Gobans commented on Projects/App/Sources/UI/User/Signup/ViewModel/NickNameInputViewModel.swift
> +import Combine
변경완료 [35bb3d5](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/22/commits/35bb3d5326c9ef71fdd2ca0310dd7df92a87744c)

2022-10-14 07:03 UTC, Gobans commented on Projects/App/Sources/UI/User/Signup/Views/NickNameInputViewController.swift
> +import DesignSystem
변경완료 [35bb3d5](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/22/commits/35bb3d5326c9ef71fdd2ca0310dd7df92a87744c)

2022-10-14 07:10 UTC, Gobans commented on Projects/App/Sources/UI/User/Signup/Views/NickNameInputViewController.swift
> +        nextButtonView.button.setAttributedTitle(NSAttributedString(string: "다음", attributes: [NSAttributedString.Key.font: UIFont.systemFont(ofSize: 17, weight: .bold)]), for: .normal)
반영완료 [f510012](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/22/commits/f51001299fa5046b42907cc674115bc429ee60e8)

2022-10-14 07:34 UTC, Gobans commented on Projects/App/Sources/UI/User/Signup/Views/NickNameInputViewController.swift
> +        nickNameTextField.delegate = self
combine으로 TextField의 
```swift
func textField(_ textField: UITextField, shouldChangeCharactersIn range: NSRange, replacementString string: String) -> Bool

 func textFieldShouldReturn(_ textField: UITextField) -> Bool
```
이 델리게이트 메소드 둘을 제어하는 방법을 모르겠어요😿

2022-10-14 07:37 UTC, Gobans commented on Projects/App/Sources/UI/User/Signup/Views/NickNameInputViewController.swift
> +    }
반영하였습니다! [461ba70](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/22/commits/461ba70ad1e609feb99975b4ab0823acf9f129f7)

2022-10-14 07:38 UTC, Gobans commented on Projects/App/Sources/UI/User/Signup/Views/SignupCompleteViewController.swift
> +
반영완료 [3de5855](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/22/commits/3de5855013bac86643b9873f9d807c3175197f90)

2022-10-14 07:39 UTC, Gobans commented on Projects/App/Sources/UI/User/Signup/Views/SignupCompleteViewController.swift
> +                                                                     attributes: [NSAttributedString.Key.font: UIFont.systemFont(ofSize: 17, weight: .bold)]), for: .normal)
이건 for 한줄 띄우면 더 이상해서.. 반영안하는게 좋을 것 같습니다
<img width="856" alt="image" src="https://user-images.githubusercontent.com/56781342/195790088-a1162631-63ba-46d9-8821-70caf764c84e.png">

2022-10-14 07:41 UTC, Gobans commented on Projects/DesignSystem/Sources/Component/ShadowButtonView.swift
> +    private let buttonShadowView = UIView()
button 은 직접 접근하여 setAttributedTitle이나 setImage 등을 설정해주어야하는 반면 buttonShadowView는 단순히 버튼을 꾸며주기만 하는 view라 private로 제어하였습니다.

2022-10-14 07:47 UTC, Gobans commented on Projects/DesignSystem/Sources/Component/UITextFieldPadding.swift
> +    var padding: UIEdgeInsets
헉 맞네요 [8dbe094](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/22/commits/8dbe094e40b5e045f667b1201cac55228bf1ee69) 적용완료!

2022-10-14 07:48 UTC, Gobans commented on Projects/App/Sources/UI/User/Signup/Views/SignupCompleteViewController.swift
> +
오예 ⛏⛏⛏⛏⛏⛏⛏⛏⛏ [7242523](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/22/commits/72425230318ab834bda2458fd21a59bd26caaa30)

2022-10-14 07:49 UTC, Gobans commented on Projects/DesignSystem/Sources/Component/ShadowButtonView.swift
> +
근데 이곳은 DesignSystem이라 addSubviews가 없는데 extension을 만들어서 쓰는게 맞을까요?

2022-10-14 08:00 UTC, Gobans commented on Projects/DesignSystem/Sources/Component/ShadowButtonView.swift
> +        buttonShadowView.backgroundColor = state ? .lightGray : .black
반영완료 [ef641fa](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/22/commits/ef641faa3b912839f588b25a5043f15c2a312dda)

2022-10-14 08:17 UTC, Gobans commented on Projects/DesignSystem/Sources/Component/UITextFieldPadding.swift
> +    public init(top: CGFloat, left: CGFloat, bottom: CGFloat, right: CGFloat) {
본문에 내용 추가하였습니다!!

2022-10-14 09:05 UTC, Gobans commented
@YebinKim 비비 직접 구동 리뷰 감사드려요!!
제 별명이 많아지고 있네요😂👻

**1. iPhone13 Pro Max 기기에서 애플 로그인 버튼 UI 깨짐**
<img width="439" alt="image" src="https://user-images.githubusercontent.com/56781342/195801390-6def9e43-39a9-41b3-94c2-11c653bf2929.png">

kakaoLogin 이미지 길이가 많이 짧아서 이런 문제가 발생했어요. asset에 이미지를 다시 추가하고 .scaleToFit으로 비율에 맞게 보여지도록 수정했어요!

<img width="442" alt="image" src="https://user-images.githubusercontent.com/56781342/195807987-1164e6cb-6971-4c96-a1e9-9bbf1f473f0e.png">

**2. 가로모드에서 버튼 동작 불가능**
팀원들과 이야기 나눴는데 가로모드를 지원하지 않기로 해서 Info.plist 를 수정하여 세로모드 고정을 했어요!

세심한 리뷰 감사합니다~!
[e1ac39c](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/22/commits/e1ac39c0e68c06ccf78590ceb20d70062c733110)

2022-10-14 09:07 UTC, Gobans commented
@chaneeii 불꽃 리뷰 감사합니다. 🔥🔥 불꽃 방어 했으니 확인 부탁드려요.

2022-10-14 16:12 UTC, YebinKim approved these changes
빠른 확인 감사합니다 고반!! 😆
고생 많으셨어요~

2022-10-15 00:35 UTC, tea-hkim reviewed
작업량이 많았는데도 빠르게 끝내셨네요!!
수고하셨습니다 :)

2022-10-15 00:35 UTC, tea-hkim commented on .github/auto_assign.yml
> +  - tea-hkim
아예 추가가 안됐었군요

2022-10-15 00:35 UTC, tea-hkim commented on Projects/DesignSystem/Sources/Component/UITextFieldPadding.swift
> +    public init(top: CGFloat, left: CGFloat, bottom: CGFloat, right: CGFloat) {
p2)
고반 나중에 UITextFieldPadding에 대학교 도메인 UILabel을 넣어서 사용해야 할 것 같은데 그때는 어떻게 사용하는게 좋을까요? 따로 익스텐션을 만들어야 하는걸까요?

2022-10-15 05:00 UTC, Gobans commented on .github/auto_assign.yml
> +  - tea-hkim
버그가 있었네요..

2022-10-15 05:03 UTC, Gobans commented on Projects/DesignSystem/Sources/Component/UITextFieldPadding.swift
> +    public init(top: CGFloat, left: CGFloat, bottom: CGFloat, right: CGFloat) {
그때는 UITextFieldPadding과 합쳐서 만든 새로운 클래스를 해당 작업 폴더안에 따로 만들면될 것 같습니다. 아니면 사용하는 ViewController 에서 UIView에 UITextField 와 UILabel과 합쳐 디자인을 묶어서 만들거나요. 반복되서 사용될 컴포넌트는 아닌 것 같아요

2022-10-15 08:25 UTC, Lia316 commented on Projects/DesignSystem/Sources/Component/ShadowButtonView.swift
> +
앗 그렇군요. 저는 만드는 거에 한 표요

2022-10-15 11:35 UTC, Lia316 requested changes
고반 수고하셨어요~!
멋진 UI 덕분에 앱이 웅장해지는 것 같아요!

코드 스타일과 MVVM 패턴에 관해서 주로 리뷰 남겨드렸으니 확인 부탁드려요 😋
버그만 없다 뿐이지 P1 코멘트입니다 ^__^

아 그리고, 현재 텍스트필드 선택 여부에 따라 다음 버튼이 움직이는데 의도된 걸까요? 👀
<img width="200" alt="image" src="https://user-images.githubusercontent.com/73650994/195984238-39deb578-935c-4f65-b15e-603bbb6c24e5.png">  <img width="200" alt="image" src="https://user-images.githubusercontent.com/73650994/195984250-a3a3bc27-a30a-4bd4-98d1-026cadf57ebe.png">

2022-10-15 11:35 UTC, Lia316 commented on Projects/App/Sources/UI/User/Login/Views/ThirdPartyLoginViewController.swift
> +        view.addSubviews([titleStackView, characterImageView, loginStackView])
[P2]

```suggestion
    
    private func createLayout() {
        view.addSubviews([titleStackView, characterImageView, loginStackView])
```

통일한 UI 메서드 명 규칙 준수 부탁드려요!

2022-10-15 11:35 UTC, Lia316 commented on Projects/App/Sources/UI/User/Signup/Views/NickNameInputViewController.swift
> +        .eraseToAnyPublisher()
[P2]

`UITextField` extension에 프로퍼티로 넣는 건 어떨까요? 👀
모든 텍스트필드가 퍼블리셔를 사용할 수 있어서 훨씬 간편해질 것 같습니다.

2022-10-15 11:35 UTC, Lia316 commented on Projects/App/Sources/UI/User/Signup/Views/NickNameInputViewController.swift
> +    }
[P2]

View에 로직이 들어가지 않도록 주의해주세요! ⚠️
해당 일을 ViewModel에게 맡겨보는 것은 어떨까요?

2022-10-15 11:35 UTC, Lia316 commented on Projects/App/Sources/UI/User/Signup/Views/NickNameInputViewController.swift
> +                guard let self = self else { return }
✨✨ `weak self` ✨✨
🙌🏻 `guard let self = self else { return }`  🙌🏻

2022-10-15 11:35 UTC, Lia316 commented on Projects/App/Sources/UI/User/Signup/Views/NickNameInputViewController.swift
> +        return false
[P2]

이 로직 역시 뷰모델에게 맡기는 것은 어떨까요?

2022-10-15 11:35 UTC, Lia316 commented on Projects/App/Sources/UI/User/Signup/Views/NickNameInputViewController.swift
> +    }
[P2]

🚨 전면 수정 요망 ⚠️

`NotificationCenter`의 publisher에서 여러가지 textField 노티를 제공해줍니다.

```swift
extension UITextField {
    
    var textChangedPublisher: AnyPublisher<String, Never> {
        NotificationCenter.default.publisher(for: UITextField.textDidChangeNotification, object: self)
            .compactMap { $0.object as? UITextField }
            .compactMap { $0.text }
            .eraseToAnyPublisher()
    }

    var endEditingPublisher: AnyPublisher<UITextField, Never> {
        NotificationCenter.default.publisher(for: UITextField.textDidEndEditingNotification, object: self)
            .compactMap { $0.object as? UITextField }
            .eraseToAnyPublisher()
    }
    
}
```

와 같이 다양하게 제공해주니, 
func publisher(for name: [Notification](doc://com.apple.documentation/1pqvbeg?language=swift&usr=true).[Name](doc://com.apple.documentation/vdhixa?language=swift&usr=true), object: [AnyObject](doc://com.apple.documentation/1s8w1r2?language=swift&usr=true)? = nil) -> [NotificationCenter](doc://com.apple.documentation/z2j79s?language=swift&usr=true).[Publisher](doc://com.apple.documentation/11az9c8?language=swift&usr=true)

에서 Notification.Name을 잘 활용해보셨으면 해요! 💪🏻

2022-10-15 11:35 UTC, Lia316 commented on Projects/App/Sources/UI/User/Signup/Views/NickNameInputViewController.swift
> +        nextButtonView.button.addTarget(self, action: #selector(nextButtonClicked), for: .touchUpInside)
[Q]

`semanticContentAttribute = .forceRightToLeft` 는 어떤 용도로 사용되었나요? 👀

2022-10-15 11:35 UTC, Lia316 commented on Projects/App/Sources/UI/User/Signup/Views/NickNameInputViewController.swift
> +        view.addSubviews([titleStackView, nickNameTextField, nextButtonView])
[P2]

```suggestion
    
    private func createLayout() {
        view.addSubviews([titleStackView, nickNameTextField, nextButtonView])
```

2022-10-15 11:35 UTC, Lia316 commented on Projects/App/Sources/UI/User/Signup/ViewModel/NickNameInputViewModel.swift
> +    @Published var activatedField: UITextField?
[P2]   (마음만 같아선 [P1])

😱 ViewModel이 UIKit 요소를 가질 이유가 있을까요?

제가 코멘트로 남겨드린 TextField의 NotificationCenter Publisher를 잘 활용하면 
저 `activatedField` 친구는 사라질 수 있을 것 같습니다.

2022-10-15 11:35 UTC, Lia316 commented on Projects/App/Sources/UI/User/Signup/Views/NickNameInputViewController.swift
> +        return false
[Q]

해당 코드는 어떤 목적으로 작성되었나요? 👀
목적에 따라 코드리뷰 드릴 내용이 달라질 것 같아서 여쭤봅니다!

2022-10-15 12:29 UTC, tea-hkim commented on Projects/DesignSystem/Sources/Component/UITextFieldPadding.swift
> +    public init(top: CGFloat, left: CGFloat, bottom: CGFloat, right: CGFloat) {
아하 첫번째 방식으로 하는게 간편하고 좋을 것 같습니다 :)

2022-10-15 13:56 UTC, chaneeii commented on Projects/App/Sources/UI/User/Login/Views/ThirdPartyLoginViewController.swift
> +            make.trailing.equalTo(view.snp.trailing).offset(-20)
마자요마자요 실수,..ㅎㅎ 감사합니다

2022-10-15 13:57 UTC, chaneeii commented on Projects/App/Sources/UI/User/Signup/Views/SignupCompleteViewController.swift
> +                                                                     attributes: [NSAttributedString.Key.font: UIFont.systemFont(ofSize: 17, weight: .bold)]), for: .normal)
왜저러냐,,,🧐
이상하니깐 우선 패쓰인졍이용

2022-10-15 13:57 UTC, chaneeii commented on Projects/DesignSystem/Sources/Component/ShadowButtonView.swift
> +
홀리,,몰리,,
역시 extension 을 따로 모듈을 분리햇어야하나 싶네요,,, 이런,,,
우선만들어주세요

2022-10-15 13:59 UTC, chaneeii commented on Projects/App/Sources/UI/User/Signup/Views/NickNameInputViewController.swift
> +                guard let self = self else { return }
✨ `모야 이거 너무 예쁜데요?` ✨

2022-10-15 13:59 UTC, chaneeii commented on Projects/App/Sources/UI/User/Signup/Views/NickNameInputViewController.swift
> +        nickNameTextField.delegate = self
고반이 바꾸고 싶다고 하면,
제가 제안하려던게 @Lia316 가 이미 써두었더군요!

참고참고
https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/22#discussion_r996292673

2022-10-15 14:01 UTC, chaneeii commented on Projects/App/Sources/UI/User/Signup/Views/NickNameInputViewController.swift
> +    }
리아 감사합니당,, 리뷰 대댓 쓸 내용이 줄었다 @Gobans  여기 참고요!
<img width="300" src="https://user-images.githubusercontent.com/63157395/195990565-f665da43-bf32-4248-b10f-49cfedbb6bbe.png">

2022-10-15 14:01 UTC, chaneeii commented on Projects/App/Sources/UI/User/Signup/ViewModel/NickNameInputViewModel.swift
> +    @Published var activatedField: UITextField?
리아 감사합니당,, 리뷰 대댓 쓸 내용이 줄었다 @Gobans 여기 참고요- 22222

2022-10-15 14:29 UTC, Lia316 commented on Projects/DesignSystem/Sources/Component/ShadowButtonView.swift
> +
> 역시 extension 을 따로 모듈을 분리햇어야하나 싶네요,,, 이런,,,

헉 이런 방법이... 🤔 고민 한 번 해보죠

2022-10-16 05:30 UTC, Gobans commented on Projects/DesignSystem/Sources/Component/ShadowButtonView.swift
> +
추가하였습니다! [e8ede52](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/22/commits/e8ede52abb8f42bd35dfce1b9529249ef5f269db)

2022-10-16 05:31 UTC, Gobans commented on Projects/App/Sources/UI/User/Login/Views/ThirdPartyLoginViewController.swift
> +        view.addSubviews([titleStackView, characterImageView, loginStackView])
이걸 빠트렸네요😿 수정완료! [30d3a3a](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/22/commits/30d3a3afde086f0b5d6df6a95bc69c1b6c15329f)

2022-10-16 05:33 UTC, Gobans commented on Projects/App/Sources/UI/User/Signup/Views/NickNameInputViewController.swift
> +        .eraseToAnyPublisher()
상황마다 다르게 publisher 만들어야 할 것 같아서 extension에 안넣었는데,
생각해보니 이건 text 변경이라 공용으로 쓰일 것 같네요! 반영하였습니다.
[2321619](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/22/commits/232161948249531ea56bb713830d6129adc3ed7b)

2022-10-16 05:33 UTC, Gobans commented on Projects/App/Sources/UI/User/Signup/Views/NickNameInputViewController.swift
> +    }
오오.. 그렇네요 감사합니다~!
[dfcfa78](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/22/commits/dfcfa783d233acbcd49abb4186f0ce847d484044)

2022-10-16 05:34 UTC, Gobans commented on Projects/App/Sources/UI/User/Signup/Views/NickNameInputViewController.swift
> +                guard let self = self else { return }
✨✨✨✨

2022-10-16 05:57 UTC, Gobans commented on Projects/App/Sources/UI/User/Signup/Views/NickNameInputViewController.swift
> +        return false
이 코드는 textField에 입력되는 문자를 검증하여 해당 문자를 textField에 입력할지 말지 판단하는 코드입니다. (특수문자, 스페이스, 글자 길이)
저도 이 로직을 뷰 모델에게 맡기고 싶긴한데, 
1. 해당 delegate 메소드를 Notification.Name 으로 지원하지 않음.
2. 해당 메소드와 같은 동작을 하는 코드를 구현하기 위한 소요가 너무 크다고 판단했습니다. (가능한지도 사실 잘 모르겠어요)

2022-10-16 06:45 UTC, Gobans commented on Projects/App/Sources/UI/User/Signup/ViewModel/NickNameInputViewModel.swift
> +    @Published var activatedField: UITextField?
viewController 에 있는 `override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?)` 이 메소드 떄문에 viewModel이 가지고 있어야 하지 않나 생각했는데, 없어도 되는군요?? 변경했습니다!
[dfcfa78](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/22/commits/dfcfa783d233acbcd49abb4186f0ce847d484044)

2022-10-16 06:46 UTC, Gobans commented on Projects/App/Sources/UI/User/Signup/Views/NickNameInputViewController.swift
> +        view.addSubviews([titleStackView, nickNameTextField, nextButtonView])
수정완료 [30d3a3a](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/22/commits/30d3a3afde086f0b5d6df6a95bc69c1b6c15329f)

2022-10-16 06:46 UTC, Gobans commented on Projects/App/Sources/UI/User/Signup/Views/NickNameInputViewController.swift
> +        nextButtonView.button.addTarget(self, action: #selector(nextButtonClicked), for: .touchUpInside)
다음 버튼의 '->' 이 이미지를 title의 오른쪽에 위치하도록 변경하는 용도입니다!

2022-10-16 06:49 UTC, Gobans commented on Projects/App/Sources/UI/User/Signup/Views/NickNameInputViewController.swift
> +    }
```swift
 func textField(_ textField: UITextField, shouldChangeCharactersIn range: NSRange, replacementString string: String) -> Bool
 func textFieldShouldReturn(_ textField: UITextField) -> Bool
```
이 두가지 delegate 메소드는 위의 리뷰에 답변과 같은 이유로 변경하지 않았습니다😿
textFieldDidBeginEditing과 textFieldDidEndEditing 은 Extension에 Publisher를 만들어서 다시 구현하였습니다

[dfcfa78](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/22/commits/dfcfa783d233acbcd49abb4186f0ce847d484044)

2022-10-16 06:57 UTC, Gobans commented
@Lia316  @chaneeii  리뷰 주신사항 반영하였습니다!
열렬한 코드리뷰에 감사드리며, 확인부탁드립니다 🙏

2022-10-16 09:07 UTC, Lia316 commented on Projects/App/Sources/UI/User/Signup/Views/NickNameInputViewController.swift
> +        return false
delegate 메서드를 그대로 사용하면서도 로직만 뷰모델에 옮길 수도 있지 않을까요? 👀

```swift
// ViewController.swift

    func textField(_ textField: UITextField, shouldChangeCharactersIn range: NSRange, replacementString string: String) -> Bool {
        return viewModel.isChangeNeeded(for: string)
    }
```

```swift
// ViewModel.swift

    func isChangeNeeded(for input: String) -> Bool {
        let maxNickNameCount = 6
        let isBackSpace = strcmp(input.cString(using: .utf8), "\\b") == -92
        if (nickNameText.count < maxNickNameCount && checkValidCharacter(to: input)) || isBackSpace {
            return true
        }
        return false
    }
    
    private func checkValidCharacter(to string: String) -> Bool { ... }

```

예시로 보여드립니다.

2022-10-16 10:21 UTC, Gobans commented on Projects/App/Sources/UI/User/Signup/Views/NickNameInputViewController.swift
> +        return false
아하 델리게이트를 아예 Publisher로 만들어서 처리하라는 말씀인줄 알았어요.
훨씬 보기 좋네요!! 친절한 예시 감사합니다. 🥳🥳

[b58a9ca](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/22/commits/b58a9ca7131cd2f52a8e85e00c520b117ab812bd)

2022-10-17 00:07 UTC, Lia316 commented on Projects/App/Sources/UI/User/Signup/Views/NickNameInputViewController.swift
> +        return false
메서드 명이 메서드의 역할을 좀 더 명확히 알려줬으면 좋겠어요..!

2022-10-17 00:08 UTC, Lia316 approved these changes
무려 100개가 넘는 PR.. 😲을 처리하시느라 고생 많으셨습니다!

2022-10-17 01:35 UTC, Gobans commented on Projects/App/Sources/UI/User/Signup/Views/NickNameInputViewController.swift
> +        return false
긴 논의 끝에 수정하였습니다! [64db152](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/22/commits/64db15292b24757e097bd89e664bd1ef565c14c7)

2022-10-17 01:41 UTC, chaneeii approved these changes
✅

2022-10-17 01:42 UTC, merged