[Feat] 도메인 레이어 모델 및 Mock Data 추가
DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY pull request #24
Opened 2022-10-14 06:36 UTC by chaneeii

## 작업내용

- [x] Model 추가
- [x] MockData 추가 

## 리뷰포인트
- 저희끼리 협의된 데이터 설계 이후 서버 데이터 내용 및 변경된 기획내용 (메뉴이름 등등) 을 반영하여 모델을 추가해두었습니다.
- 추가 변동이 가능한 상황을 대비해 미리 변수명은 작성해두고 주석을 처리해두었습니다. 
- 이상한 점이 있다면 알려주세요~

## Reference
[📝 노션 : 데이터 설계](https://avery-in-ada.notion.site/8f3d50f9c738417b9d37ca16af6859ac)

## Checklist
- [ ] 브랜치를 가져와 작업한 경우 이전 브랜치에 PR을 보냈는지 확인
- [ ] 빌드를 위해 SceneDelegate 수정한 것 PR로 올리지 않았는지 확인
- [ ] 필요없는 주석, 프린트문 제거했는지 확인
- [ ] 컨벤션 지켰는지 확인
- [ ] final, private 제대로 넣었는지 확인
- [ ] Xcode Team none 으로 되어있는지 확인

2022-10-14 09:33 UTC, Gobans requested changes
![image](https://user-images.githubusercontent.com/56781342/195812669-10809d94-4365-4647-b886-636db58c6d62.png)
mock! mock!

2022-10-14 09:33 UTC, Gobans commented on Projects/App/Sources/Domain/Review/Review.swift
> +    let menuName: String
p1
```suggestion
    let menuName: String?
```

2022-10-14 09:33 UTC, Gobans commented on Projects/App/Sources/Domain/MockData/MockData.swift
> +//  MockData.swift
p1
Review MockData 가 없어용

2022-10-15 00:48 UTC, tea-hkim approved these changes
수고하셨습니다!
Mock Mock

2022-10-15 00:48 UTC, tea-hkim commented on Projects/App/Sources/Domain/MockData/MockData.swift
> +        Organization(id: 1, name: "서울대", domain: "@snu.ac.kr", memberCount: 100, imageCount: 2, placeCount: 3),
애플 디벨로퍼 아카데미와 다른 학교 (여기서는 서울대)를 다니고 있는 사람은 어떻게 해야할 지 생각해 봐야겠네요... 2곳의 조직에 포함되는 사람은 어떻게 해야할 지

2022-10-15 04:01 UTC, chaneeii commented on Projects/App/Sources/Domain/MockData/MockData.swift
> +//  MockData.swift
추가했습니다

b4c26f2d2077e37e32babf6bd91f049bfefd229b

2022-10-15 04:02 UTC, chaneeii commented on Projects/App/Sources/Domain/Review/Review.swift
> +    let menuName: String
수정했습니다
65a7454a1f0d615de685fb940f788edd7e1a205f

2022-10-15 04:02 UTC, chaneeii commented on Projects/App/Sources/Domain/MockData/MockData.swift
> +        Organization(id: 1, name: "서울대", domain: "@snu.ac.kr", memberCount: 100, imageCount: 2, placeCount: 3),
우선은 서버에서 한조직만 저장해서 현재는 한 조직만 담고있는데, 나중에 배열로 처리해야할것같아요!
1.0 후에 다같이 이야기 해봐요

2022-10-15 05:05 UTC, Gobans approved these changes
고생하셨습니다 에버리!👍

2022-10-15 08:21 UTC, Lia316 requested changes
모델 작업해주셔서 감사드립니다~!

제가 생각했을 때는 수정사항이 있는 것 같아서 코멘트 달았는데,
아니라면 언제든 말씀해주세요!! 
수고하셨습니다 😁

2022-10-15 08:21 UTC, Lia316 commented on Projects/App/Sources/Domain/Place/Place.swift
> +//    let reviews: [Review]
[P1]

메인 맛집 리스트에서 맛집 이미지를 보여주려면 
`imageURL`이나 `reviews`  둘 중 하나가 있어야할 것 같아요

2022-10-15 08:21 UTC, Lia316 commented on Projects/App/Sources/Domain/Place/Place.swift
> +    let name: String
[Q]

`User`에서는 `organization`의 id만 갖고 있는 것 같은데, 
```swift
struct User {
    let id: Int
    let email: String
    let social: SocialProvider
    let nickname: String
    let authToken: String
    let organization: Int // [Int]
}
``` 

맛집은 `organization` 그대로 가지고 있는 이유가 있을까요?

2022-10-15 08:21 UTC, Lia316 commented on Projects/App/Sources/Domain/Review/Review.swift
> +    let place: Int
[P2]

place가 맛집의 아이디를 의미한다면, `placeId` 와 같이 의미를 명확히 해줘도 좋을 것 같습니다.

2022-10-15 08:32 UTC, Lia316 commented on Projects/App/Sources/Domain/Review/Review.swift
> +//
[P2]

https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/blob/feat/Model/ZES-116-model-mockdata/Projects/App/Sources/Domain/Review/DomainReviewPlaceHolder.swift

요기 `DomainReviewPlaceHolder.swift` 파일이 아직 남아있네요!
삭제 부탁드려요~!

2022-10-15 08:53 UTC, chaneeii commented on Projects/App/Sources/Domain/Place/Place.swift
> +//    let reviews: [Review]
✨반영
0d52c7b1d0f688b58956c6300461085aa7657774

2022-10-15 08:54 UTC, chaneeii commented on Projects/App/Sources/Domain/Place/Place.swift
> +    let name: String
✨ 반영
0d52c7b1d0f688b58956c6300461085aa7657774

2022-10-15 08:54 UTC, chaneeii commented on Projects/App/Sources/Domain/Review/Review.swift
> +    let place: Int
✨ 반영
-> 다른것도 반영
0d52c7b1d0f688b58956c6300461085aa7657774

2022-10-15 08:54 UTC, chaneeii commented on Projects/App/Sources/Domain/Review/Review.swift
> +//
killeedit ⚔️
0d52c7b1d0f688b58956c6300461085aa7657774

2022-10-15 08:56 UTC, Lia316 commented on Projects/App/Sources/Domain/Review/Review.swift
> +//
⚔️⚔️⚔️⚔️⚔️

2022-10-15 08:57 UTC, Lia316 approved these changes
이렇게 빠를 수가...🚀 버리 쉬시는 거 맞죠..?? 
반영해주셔서 감사합니다~!

2022-10-15 13:54 UTC, merged

2022-10-16 10:31 UTC, LentoAssai commented
놀고만있습니다