[Feat] 닉네임 검증 activityView UI 구현
DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY pull request #30
Opened 2022-10-17 12:32 UTC by Gobans

## 작업내용

- [x] 닉네임 검증 시 사용되는 activityView UI 구현 

|중복 닉네임 일떄|중복 닉네임 아닐때|
|:---:|:---:|
|<img width="250" src="https://user-images.githubusercontent.com/56781342/196165267-b05832b0-654b-44bb-aefa-925ccc342e74.gif">|<img width="250" src="https://user-images.githubusercontent.com/56781342/196165342-2694ae5f-d573-4154-a54a-656b9d609431.gif">|

### NickNameInputViewController
- 현재 50프로의 확률로 닉네임 중복 or 통과가 결정됩니다. 여러번 다음 버튼을 누르시면 spinner or 다음 뷰 이동을 볼 수 있어요.

### ShadowButton
- UIActivityIndicatorView 를 추가하여 스피너 동작을 구현하였습니다.
- activateIndicator, stopIndicator 메소드로 스피너 동작을 제어할 수 있습니다. 
- **사용시 주의사항:** button의 크기를 잡아주는 title 이나 imageView 혹은 constraint 가 필요합니다. (저는 title과 imageView를 hidden해서 사용했어요)

## 리뷰포인트

- combine 사용이 자연스러운지, 어색한점 or 개선점이 있다면 말씀해주시면 감사하겠습니다!

## Checklist
- [x] 브랜치를 가져와 작업한 경우 이전 브랜치에 PR을 보냈는지 확인
- [x] 빌드를 위해 SceneDelegate 수정한 것 PR로 올리지 않았는지 확인
- [x] 필요없는 주석, 프린트문 제거했는지 확인
- [x] 컨벤션 지켰는지 확인
- [x] final, private 제대로 넣었는지 확인

2022-10-18 02:12 UTC, YebinKim requested changes
고반 안녕하세요~
공통 컴포넌트 구현 고생 많으셨습니다!

리뷰 사항 몇 가지랑 UI 동작 버그가 하나 있어서 확인 부탁드려요 🙇

### 1. 이름 입력 시 `다음` 버튼 위아래로 움직이는 현상 발생

https://user-images.githubusercontent.com/38066039/196319180-d5c34a15-4aa5-4629-ad8d-a6a55af5deef.mov

2022-10-18 02:12 UTC, YebinKim commented on Projects/App/Sources/UI/User/Signup/ViewModel/NickNameInputViewModel.swift
> +        DispatchQueue.main.asyncAfter(deadline: .now() + 1.5) {
질문;

1.5초를 더하는 이유가 무엇인가요?? 🤔

2022-10-18 02:12 UTC, YebinKim commented on Projects/App/Sources/UI/User/Signup/ViewModel/NickNameInputViewModel.swift
> +                if self.shouldDisplayWarning {
p3;

두 번의 분기처리 구문이 연속되어 있는 것으로 보이는데, 하나로 합치는 것은 어떨까요?

2022-10-18 02:12 UTC, YebinKim commented on Projects/DesignSystem/Sources/Component/ShadowButtonView.swift
> +    }
p3;

`activateIndicator()` 메서드는 `stopIndicator()` 메서드의 네이밍과 세트인 느낌을 주기 위해 `startIndicator()` 로 이름을 설정하면 어떨까요?

그리고 두 메서드는 하나의 플래그에 따라 상태가 바뀌고(시작/멈춤), 현재는 중복 코드가 발생하는 것으로 보여서 매개변수를 통해 상태를 입력받는 방식으로 변경해보는 것은 어떨까요??

2022-10-18 02:25 UTC, Gobans commented on Projects/App/Sources/UI/User/Signup/ViewModel/NickNameInputViewModel.swift
> +        DispatchQueue.main.asyncAfter(deadline: .now() + 1.5) {
이건 뱅글뱅글 돌아가는 activityIndicator 를 테스트 하기 위해 적어놨습니다!

2022-10-18 02:49 UTC, Gobans commented on Projects/App/Sources/UI/User/Signup/ViewModel/NickNameInputViewModel.swift
> +                if self.shouldDisplayWarning {
아하 이게 optional 을 분기처리하는게 아니고 self.shouldDisplayWarning이 true 일때 분기처리를 하기위해 작성한 코드였습니다. 코드를 변경하여 true 를 명시하였습니다!
[79c0baf](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/30/commits/79c0baf519799e72ed84a816bd42c237ac65874f)

2022-10-18 02:49 UTC, Gobans commented on Projects/DesignSystem/Sources/Component/ShadowButtonView.swift
> +    }
startIndicator 로 변경 하였습니다! 
그런데 매개변수를 통해 상태를 입력받아 사용하는 방식은 사용할때에 뭔가 가시성이 떨어진다고 생각해서.. (저의 네이밍 실력 부족같기도 합니다🥲) 변경하지 않았습니다!

2022-10-18 03:21 UTC, tea-hkim commented on Projects/App/Sources/UI/User/Signup/View/NickNameInputViewController.swift
> +                    self.nextButtonView.setDisabled(true)
p4;
디자인대로 잘 구현하신 것을 봤습니다!
궁금했던 점은 nextButtonView의 활성화, 비활성화는 nickNameTextField에 텍스트의 유무로 정해지는 것 같습니다.
그렇게 되면 닉네임 중복 시, 텍스트는 존재하기 때문에 경고창만 띄우고 nextButtonView은 활성화가 되는 것이 사용자에게 직관적으로 다가올 것 같은데 어떻게 생각하시나요? with @Chaeho-Min

2022-10-18 07:36 UTC, Chaeho-Min commented on Projects/App/Sources/UI/User/Signup/View/NickNameInputViewController.swift
> +                    self.nextButtonView.setDisabled(true)
닉네임 중복 시 버튼을 비활성화한 이유는 불필요한 로딩을 줄이기 위해서였습니다. 중복일 때 다음 버튼을 실수로 혹은 중복임을 인지하지 못해서 눌렀다면, 이미 표시되어 있는 결과가 다시 나올때까지 로딩을 기다려야 하니까요.

또한 현재 닉네임 중복시 흔들리는 애니메이션이나 햅틱 피드백 등 충분한 피드백이 없고, 화면 전체를 비활성화하는 알림창이 아닌 그냥 화면에 텍스트 라벨이 하나 추가되는 형식이라 사용자가 경고문을 못 읽고 지나칠수도 있을 것 같아서 버튼 비활성화가 필요하다고 생각했습니다!

요약
1. 불필요한 로딩을 겪지 않도록 버튼을 못누르도록 강제함
2. 현재 닉네임이 사용 불가능함을 좀 더 확실하게 알려주기 위해 비활성화를 이용함

2022-10-18 07:48 UTC, YebinKim commented on Projects/App/Sources/UI/User/Signup/ViewModel/NickNameInputViewModel.swift
> +        DispatchQueue.main.asyncAfter(deadline: .now() + 1.5) {
테스트 코드였군요~! 확인했습니다 😄

2022-10-18 09:10 UTC, Gobans commented on Projects/App/Sources/UI/User/Signup/View/NickNameInputViewController.swift
> +                    self.nextButtonView.setDisabled(true)
저도 버튼 비활성화는 아보와 같은 이유로 있어야한다고 생각했습니다.

2022-10-18 09:21 UTC, Gobans commented
@YebinKim 
리뷰 감사합니다 비비!🙌
덜커덩 거리는 애니메이션이 조금 어색하다고 생각하긴 했는데, 
뭔가 잘 해결되지 않아서 일단 보류했다가 리뷰 받은김에 다른 방법을 찾아 해결했습니다!

<img width="240" src="https://user-images.githubusercontent.com/56781342/196389056-76e4b838-3af3-4943-bc42-48aab9e354e4.gif">

이전에는 view.keyboardLayoutGuide로 키보드 대응 constraints 만들었는데, 이떄 constraints를 계속 트랙킹하면서 constraints를 잡아서 덜커덩 거리는 애니메이션이 연출된 것 같습니다. 

이후 keyboardFrame을 구해 버튼의 y축을 올리고 내리는 식으로 constraints를 잡으려 했는데, 왠지모르게 키보드 타이핑시 버튼위치가 초기화 되더라구요... (이유를 아시는분 있나요?🥲👀)

그래서 현재는 방법을 달리하여 키보드 frame 구한 후, 해당 값으로 다시 constraints를 설정하는 방식으로 변경하였습니다.

현재 가장 궁금한 부분것은 왜 버튼이 날라가는지가 궁금하네요... 이건 나중에 연구한다면 꼭 Discussions에 올리겠습니다.

2022-10-19 02:49 UTC, Lia316 approved these changes
디테일까지 놓치지 않고 구현하셨네요~! 
수고 많으셨어요 고반!! 🙌🏻

2022-10-19 02:49 UTC, Lia316 commented on Projects/App/Sources/UI/User/Signup/ViewModel/NickNameInputViewModel.swift
> +                    self.shouldDisplayWarning = false
p4;

shouldDisplayWarning 은 Bool 타입이니 == true 를 작성하지 않으셔도 될 것 같습니다.

2022-10-19 02:49 UTC, Lia316 commented on Projects/App/Sources/UI/User/Signup/ViewModel/NickNameInputViewModel.swift
> +            }
p3;

weak self

2022-10-19 03:36 UTC, Gobans commented on Projects/App/Sources/UI/User/Signup/ViewModel/NickNameInputViewModel.swift
> +                    self.shouldDisplayWarning = false
가독성을 위해 수정하였습니다!
[4b08a1a](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/30/commits/4b08a1ab9fa3bfc0510cf7e351ebdaaa9bf5daea)

2022-10-19 03:36 UTC, Gobans commented on Projects/App/Sources/UI/User/Signup/ViewModel/NickNameInputViewModel.swift
> +            }
테스트 코드라 서버 통신 구현할때 수정하겠습니다!

2022-10-19 03:50 UTC, YebinKim approved these changes
키보드 덜커덩거리는 문제 해결되었네요!! 고생 많으셨습니다 고반 😆🙌

2022-10-19 03:53 UTC, merged