[FEAT] 대학교 리스트 화면 UI
DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY pull request #31
Opened 2022-10-17 16:31 UTC by tea-hkim

## 작업내용

- [x] 대학교 리스트 화면 UI 작업
- [x] 컴포넌트 shadowTextFieldView 추가
- [x]  대학교 이름 검색 기능 추가

|대학교 리스트 - 검색 전|대학교 리스트 - 검색 후|대학교 리스트 - 공백 포함 검색 후|
|:---:|:---:|:---:|
|<img width="250" src="https://user-images.githubusercontent.com/81206228/196221460-c61a1474-0e8b-4c93-8841-e754b3307e79.png">|<img width="250" src="https://user-images.githubusercontent.com/81206228/196221469-8f5f2ff9-0534-439c-bd55-14d025800a03.png">|<img width="250" src="https://user-images.githubusercontent.com/81206228/196232680-69b27d73-33b0-4069-9eb9-3ed1607ba547.png">|

### 1.  대학교 리스트 화면 UI 작업 
- 화면의 타이틀을 26이라는 고정값을 주었는데 디바이스의 글씨 크기에 따라 유동적으로 변하지 않아서 방법을 찾고 있습니다.
    나중에 다시 PR올리겠습니다.
- system 내부에 있는 color를 사용했습니다. 이 부분도 추후에 변경해서 디자인 변경 PR 올리겠습니다
- shadow를 가진 TextField는 추후에 사용될 가능성이 있어보여 컴포넌트로 만들었습니다.

### 2. 대학교 이름 검색 기능 e68529e
스페이스가 들어오는 상황을 예외 처리하기 위한 코드입니다.

1. 입력 값이 없다면 기본 대학 리스트를 띄운다.
2. 입력 값이 있고, 입력 값에 공백이 있다면
     1. 스페이스를 기준으로 하는 문자열 배열을 만든다.
     2. 문자열 내부에 있는 문자를 가진 대학교 이름들을 필터링 한다.
     3. 필터링 된 새로운 리스트를 띄운다.
4. 입력 값이 있고, 입력 값에 공백이 없다면 그대로 필터링을 한다.
    1. 필터링 된 새로운 리스트를 띄운다.

- 이렇게 작업을 한 이유는 유저가 띄어쓰기를 통해 2가지 이상의 단어를 검색하는 이유가 
   단어들의 교집합을 통해 필터링을 하려는 것이 아니라 3가지 단어를 전부 포함하고 있는 합집합을 찾으려고 한다 생각했기 때문입니다.
- 이후 생기는 예외 처리 상황들을 찾는다면 PR에 추가하도록 하겠습니다.

## 다음 작업 내용
- [ ] 대학교 이메일 입력 화면 UI 
- [ ] 대학교 리스트 cell 탭 시 대학교 이메일 입력 화면으로 전환

## 리뷰포인트

1. 대학교 이름 검색 기능 e68529e 을 만들었는데 아주 지저분한 코드가 되었습니다. 
    더 좋은 방법을 남겨주신다면 열심히 공부하겠습니다. (알고리즘 공부의 중요성을 느꼈습니다...)
3. 공부한 MVVM 패턴에선 지금의 ViewModel에서 로직을 분리해내어 UseCase를 만들어야 한다고 생각하는데
    ViewModel의 크기를 더 줄이는게 좋을까요??

## Checklist
- [x] 브랜치를 가져와 작업한 경우 이전 브랜치에 PR을 보냈는지 확인
- [x] 빌드를 위해 SceneDelegate 수정한 것 PR로 올리지 않았는지 확인
- [x] 필요없는 주석, 프린트문 제거했는지 확인
- [x] 컨벤션 지켰는지 확인
- [x] final, private 제대로 넣었는지 확인

2022-10-18 02:12 UTC, chaneeii approved these changes
👍 고생하셨습니다

2022-10-18 02:12 UTC, chaneeii commented on Projects/DesignSystem/Sources/Asset/Asset.swift
> +    case magnifyingglass
p2)
컨벤션 통일을 위함입니당
ic_magnifyingglass

2022-10-18 02:12 UTC, chaneeii commented on Projects/App/Sources/UI/Organization/OrganizationList/OrganizationListViewController.swift
> +    private var subscriptionSet = Set<AnyCancellable>()
p1)
저희 요부분 다같이 네이밍 통일하는게 좋을 것 같습니다..!

@tea-hkim @Lia316 @Gobans @italsehf @Chaeho-Min

2022-10-18 02:12 UTC, chaneeii commented on Projects/App/Sources/UI/Organization/OrganizationList/View/Cell/OrganizationListCell.swift
> +            make.left.equalTo(self.snp.left).inset(20)
p5)
.equalToSuperview() 를 사용하면 더 편리할것 같습니다! 추천!

2022-10-18 02:17 UTC, Gobans requested changes
고생하셨습니다 닉!
저도 그랬지만 템플릿에 맞춰 띄어쓰기, extension 분리를 다시 검토해보실 필요가 있을 것 같아요!
코드 리뷰 내용을 간략하게 남겼는데, 리뷰에 대한 자세한 설명이나 의견은 언제든지 말해주시면 좋을 것 같아요.
파이팅~!

2022-10-18 02:17 UTC, Gobans commented on Projects/App/Sources/UI/Organization/OrganizationList/OrganizationListViewController.swift
> +//  OrganizationListViewController.swift
p2
ViewController를 View 폴더안에 위치하도록 해주세요

2022-10-18 02:17 UTC, Gobans commented on Projects/App/Sources/UI/Organization/OrganizationList/OrganizationListViewController.swift
> +import DesignSystem
p3
퍼스트파티 -> 서드파티
알파벳 순으로 정렬해주세요

2022-10-18 02:17 UTC, Gobans commented on Projects/App/Sources/UI/Organization/OrganizationList/OrganizationListViewController.swift
> +    private var viewModel = OrganizationListViewModel()
p2
var -> let viewModel은 클래스입니다!

2022-10-18 02:17 UTC, Gobans commented on Projects/App/Sources/UI/Organization/OrganizationList/OrganizationListViewController.swift
> +    private func bindUI() {
p2
bindUI 를 extension으로 빼서 클래스 바로 밑에 위치로 옮겨주세요

2022-10-18 02:17 UTC, Gobans commented on Projects/App/Sources/UI/Organization/OrganizationList/OrganizationListViewController.swift
> +    // MARK: UI Function
p2
UI Function은 가장 아래에 위치해도 된다고 생각합니다. (bindUI -> delegate 등 기능의 중요도 순으로 배치하는게 좋을 것 같아요)

2022-10-18 02:17 UTC, Gobans commented on Projects/App/Sources/UI/Organization/OrganizationList/OrganizationListViewController.swift
> +        guard let cell = cell else { return UITableViewCell()}
p3
한칸 띄워주세요!
```suggestion
        guard let cell = cell else { return UITableViewCell() }
```

2022-10-18 02:17 UTC, Gobans commented on Projects/App/Sources/UI/Organization/OrganizationList/OrganizationListViewController.swift
> +        self.viewModel.$searchingArray.sink { orgNameArray in
p1
weak self 필요합니다!
```suggestion
        self.viewModel.$searchingArray
        .sink { [weak self ] orgNameArray in
        guard let self = self else { return }
```

2022-10-18 02:17 UTC, Gobans commented on Projects/App/Sources/UI/Organization/OrganizationList/OrganizationListViewController.swift
> +        }.store(in: &subscriptionSet)
p3
가독성을 위해 바꾸면 좋을 것 같아요
```suggestion
        }
        .store(in: &subscriptionSet)
```

2022-10-18 02:17 UTC, Gobans commented on Projects/App/Sources/UI/Organization/OrganizationList/OrganizationListViewController.swift
> +            .userInputTextPublisher
p2
extension에 UITextField의 publisher를 정의해놓았습니다. 바꿔주세요!

2022-10-18 02:17 UTC, Gobans commented on Projects/App/Sources/UI/Organization/OrganizationList/OrganizationListViewController.swift
> +        self.searchingTextField
p3
안써도 되는 self는 모두 지워주세요 (많은 swift convention guideline에서 필요없는 self는 지양하고 있습니다)

2022-10-18 02:17 UTC, Gobans commented on Projects/App/Sources/UI/Organization/OrganizationList/OrganizationListViewController.swift
> +        self.view.endEditing(true)
p3
self 삭제  부탁드립니다

2022-10-18 02:17 UTC, Gobans commented on Projects/App/Sources/UI/Organization/OrganizationList/OrganizationListViewController.swift
> +        .eraseToAnyPublisher()
p2
extension에 UITextField의 publisher를 정의해놓았습니다. 바꿔주세요!

2022-10-18 02:17 UTC, Gobans commented on Projects/App/Sources/UI/Organization/OrganizationList/View/Cell/OrganizationListCell.swift
> +        self.addSubviews([orgNameLabel, disclosureIndicator])
p3
이 파일안에 있는 self 들도 모두 교체해주세요!

2022-10-18 02:17 UTC, Gobans commented on Projects/App/Sources/UI/Organization/OrganizationList/View/Cell/OrganizationListCell.swift
> +            make.bottom.equalTo(self.snp.bottom).inset(16)
p4
에버리가 알려준 팁
```suggestion
            make.top.bottom.equalToSuperview().inset(16)
```

2022-10-18 02:17 UTC, Gobans commented on Projects/App/Sources/UI/Organization/OrganizationList/ViewModel/OrganizatinoListViewModel.swift
> +    }
p3
property observer를 combine으로 구현해보면 어떨까요?

2022-10-18 02:17 UTC, Gobans commented on Projects/App/Sources/UI/Organization/OrganizationList/ViewModel/OrganizatinoListViewModel.swift
> +extension OrganizationListViewModel {
[Q]
extension으로 나눈 이유는 무엇인가요?

2022-10-18 02:17 UTC, Gobans commented on Projects/App/Sources/UI/Organization/OrganizationList/OrganizationListViewController.swift
> +    private var orgNameArray: [String] = []
p1
ViewController가 가지고 있을 필요가 없어보입니다. View 는 viewModel이 가진 데이터에 따라 화면을 그려주는 역할만 하도록 해주세요

2022-10-18 02:17 UTC, Gobans commented on Projects/App/Sources/UI/Organization/OrganizationList/OrganizationListViewController.swift
> +        self.viewModel.$searchingArray.sink { orgNameArray in
++ viewModel의 searchingArray -> view의 orgNameArray 로 데이터를 가져오면 안될 것 같아요

2022-10-18 02:17 UTC, Gobans commented on Projects/App/Sources/UI/Organization/OrganizationList/ViewModel/OrganizatinoListViewModel.swift
> +    @Published var searchingArray: [String] = []
p2
searchedOrgArray 가 더 의미상 자연스러운 것 같아요

2022-10-18 02:17 UTC, Gobans commented on Projects/App/Sources/UI/Organization/OrganizationList/ViewModel/OrganizatinoListViewModel.swift
> +    private var orgNameArray: [String] = []
p3
Input output 구분은 Publisher에 해당할 때 적어주는게 좋을 것 같아요

2022-10-18 02:17 UTC, Gobans commented on Projects/DesignSystem/Sources/Component/ShadowTextFieldView.swift
> +        leftImage.image = UIImage(.magnifyingglass)
Q
SF symbol 말고 UIImage asset을 넣어 만든 이유가 무엇인가요?

2022-10-18 02:17 UTC, Gobans commented on Projects/DesignSystem/Sources/Component/ShadowTextFieldView.swift
> +        // TODO: addSubViews extension으로 교체하기
지금 교체해주세요!

2022-10-18 02:17 UTC, Gobans commented on Projects/DesignSystem/Sources/Component/ShadowTextFieldView.swift
> +    private let backgroundView = UIView()
p2
backgroundView가 딱히 필요없는 view 같습니다. 해당 뷰의 appearance를 ShadowTextFieldView (self)가 하면 안될까요?

2022-10-18 02:17 UTC, Gobans commented on Projects/App/Sources/UI/Organization/OrganizationList/ViewModel/OrganizatinoListViewModel.swift
> +    private func searchingInput(_ input: String) {
p3
searchInput 이 더 적절한 것 같습니다

2022-10-18 02:17 UTC, Gobans commented on Projects/App/Sources/UI/Organization/OrganizationList/ViewModel/OrganizatinoListViewModel.swift
> +    private func setSearchingData() {
p3
setInitialSearchedArray() 로 변수명을 짓고 아래
```swift
   if input.isEmpty {
             setInitialSearchedArray()
             return
         }
```
이렇게 써주는게 가독성이 더 좋을 것 같아요

2022-10-18 02:17 UTC, Gobans commented on Projects/App/Sources/UI/Organization/OrganizationList/ViewModel/OrganizatinoListViewModel.swift
> +    private var organizationArray: [Organization] = []
p2
org 나 organization 줄이거나 다 쓰거나 통일 하면 좋을 것 같아요

2022-10-18 02:17 UTC, Gobans commented on Projects/DesignSystem/Sources/Component/ShadowTextFieldView.swift
> +extension ShadowTextFieldView {
p3
extension 위 아래 한칸 띄워주세요

2022-10-18 02:17 UTC, Gobans commented on Projects/DesignSystem/Sources/Component/ShadowTextFieldView.swift
> +    }
p3
extension 위 아래 한칸 띄워주세요

2022-10-18 02:17 UTC, Gobans commented on Projects/App/Sources/UI/Organization/OrganizationList/View/Cell/OrganizationListCell.swift
> +    }
p3
extension 위 아래 한칸 띄워주세요

2022-10-18 02:17 UTC, Gobans commented on Projects/App/Sources/UI/Organization/OrganizationList/OrganizationListViewController.swift
> +extension OrganizationListViewController: UITextFieldDelegate {
p3
extension 위 아래 한칸 띄워주세요

2022-10-18 02:17 UTC, Gobans commented on Projects/App/Sources/UI/Organization/OrganizationList/OrganizationListViewController.swift
> +    }
p3
한칸 띄워주세요

2022-10-18 02:18 UTC, Gobans commented on Projects/App/Sources/UI/Organization/OrganizationList/OrganizationListViewController.swift
> +    private var subscriptionSet = Set<AnyCancellable>()
cancelBag 한표!

2022-10-18 02:25 UTC, tea-hkim commented on Projects/DesignSystem/Sources/Component/ShadowTextFieldView.swift
> +        leftImage.image = UIImage(.magnifyingglass)
SF symbol과 디자인에서 사용된 돋보기의 모양이 달라서 디자인에서 사용된 이미지를 사용하였습니다!

2022-10-18 02:52 UTC, tea-hkim commented on Projects/App/Sources/UI/Organization/OrganizationList/ViewModel/OrganizatinoListViewModel.swift
> +extension OrganizationListViewModel {
메서드 역할을 하는 것들을 나눠서 보기 쉽게 하려는 의도입니다!

2022-10-18 02:55 UTC, Lia316 commented on Projects/App/Sources/UI/Organization/OrganizationList/OrganizationListViewController.swift
> +    private var subscriptionSet = Set<AnyCancellable>()
cancelBag 두 표요

2022-10-18 02:59 UTC, Lia316 commented on Projects/App/Sources/UI/Organization/OrganizationList/ViewModel/OrganizatinoListViewModel.swift
> +    @Published var searchingArray: [String] = []
Org 넣는 거 찬성이요! 
Array는 취향 차이라서,, 저는 List를 더 선호하긴 합니다 😗➿🎶

2022-10-18 03:01 UTC, Lia316 commented on Projects/App/Sources/UI/Organization/OrganizationList/ViewModel/OrganizatinoListViewModel.swift
> +    private var orgNameArray: [String] = []
> Input output 구분은 Publisher에 해당할 때 적어주는게 좋을 것 같아요

고반! 이건 어떤 의미실까요? 👀

저는 뷰에게 받아서 가공해야할 정보는 input,
뷰에게 최종적으로 전달할 가공된 정보는 output이라고 생각하고 있습니다

2022-10-18 03:03 UTC, tea-hkim commented on Projects/App/Sources/UI/Organization/OrganizationList/ViewModel/OrganizatinoListViewModel.swift
> +    private var organizationArray: [Organization] = []
130dc01
약어를 쓰기보다 명시를 해주는 것이 나중을 위해서도 좋을 것 같아서 org -> organization으로 변경했습니다!

2022-10-18 03:03 UTC, tea-hkim commented on Projects/App/Sources/UI/Organization/OrganizationList/OrganizationListViewController.swift
> +    private var orgNameArray: [String] = []
130dc01 변경했습니다!

2022-10-18 03:03 UTC, tea-hkim commented on Projects/App/Sources/UI/Organization/OrganizationList/ViewModel/OrganizatinoListViewModel.swift
> +    @Published var searchingArray: [String] = []
130dc01 변경했습니다!

2022-10-18 03:03 UTC, tea-hkim commented on Projects/App/Sources/UI/Organization/OrganizationList/ViewModel/OrganizatinoListViewModel.swift
> +    private var orgNameArray: [String] = []
130dc01 변경했습니다!

2022-10-18 03:03 UTC, Lia316 commented on Projects/App/Sources/UI/Organization/OrganizationList/ViewModel/OrganizatinoListViewModel.swift
> +    private var organizationArray: [Organization] = []
통일하자는 의견 좋아요!!

변수명은 org 찬성, 모델명은 길게 그대로 가는 것 주장합니다!

2022-10-18 03:07 UTC, tea-hkim commented on Projects/App/Sources/UI/Organization/OrganizationList/OrganizationListViewController.swift
> +//  OrganizationListViewController.swift
130dc01 반영했습니다!

2022-10-18 03:19 UTC, tea-hkim commented on Projects/App/Sources/UI/Organization/OrganizationList/ViewModel/OrganizatinoListViewModel.swift
> +    private func searchingInput(_ input: String) {
130dc01 변경했습니다!

2022-10-18 03:20 UTC, tea-hkim commented on Projects/App/Sources/UI/Organization/OrganizationList/ViewModel/OrganizatinoListViewModel.swift
> +    private func setSearchingData() {
130dc01 변경했습니다!

2022-10-18 04:59 UTC, Chaeho-Min commented on Projects/DesignSystem/Sources/Component/ShadowTextFieldView.swift
> +        leftImage.image = UIImage(.magnifyingglass)
음...?! 저 SF Symbol 사용했습니다!

2022-10-18 05:32 UTC, tea-hkim commented on Projects/App/Sources/UI/Organization/OrganizationList/OrganizationListViewController.swift
> +import DesignSystem
e3e76df 반영했습니다!

2022-10-18 05:32 UTC, tea-hkim commented on Projects/App/Sources/UI/Organization/OrganizationList/OrganizationListViewController.swift
> +    private var viewModel = OrganizationListViewModel()
e3e76df 반영했습니다!

2022-10-18 05:32 UTC, tea-hkim commented on Projects/App/Sources/UI/Organization/OrganizationList/OrganizationListViewController.swift
> +    private var subscriptionSet = Set<AnyCancellable>()
e3e76df 변경했습니다!

2022-10-18 05:32 UTC, tea-hkim commented on Projects/App/Sources/UI/Organization/OrganizationList/OrganizationListViewController.swift
> +    private func bindUI() {
130dc01 반영했습니다!

2022-10-18 05:32 UTC, tea-hkim commented on Projects/App/Sources/UI/Organization/OrganizationList/OrganizationListViewController.swift
> +        self.viewModel.$searchingArray.sink { orgNameArray in
130dc01 반영했습니다! 현재는 빌드되어 돌아가도록 해놨는데 구현 부분에 있어서는 좀 더 생각을 해보고 리팩토링 하겠습니다!

2022-10-18 05:32 UTC, tea-hkim commented on Projects/App/Sources/UI/Organization/OrganizationList/OrganizationListViewController.swift
> +        }.store(in: &subscriptionSet)
130dc01 반영했습니다

2022-10-18 05:32 UTC, tea-hkim commented on Projects/App/Sources/UI/Organization/OrganizationList/OrganizationListViewController.swift
> +        self.searchingTextField
130dc01 반영했습니다!
VeiwController 내부의 self는 수정했는데 나머지 파일은 다른 commit에서 수정하도록 하겠습니다.

2022-10-18 05:32 UTC, tea-hkim commented on Projects/App/Sources/UI/Organization/OrganizationList/OrganizationListViewController.swift
> +    }
130dc01 반영했습니다!

2022-10-18 05:32 UTC, tea-hkim commented on Projects/App/Sources/UI/Organization/OrganizationList/OrganizationListViewController.swift
> +        guard let cell = cell else { return UITableViewCell()}
130dc01 반영했습니다!

2022-10-18 05:32 UTC, tea-hkim commented on Projects/App/Sources/UI/Organization/OrganizationList/OrganizationListViewController.swift
> +extension OrganizationListViewController: UITextFieldDelegate {
130dc01 반영했습니다!

2022-10-18 05:32 UTC, tea-hkim commented on Projects/App/Sources/UI/Organization/OrganizationList/OrganizationListViewController.swift
> +        self.view.endEditing(true)
130dc01 반영했습니다!

2022-10-18 06:00 UTC, chaneeii commented on Projects/App/Sources/UI/Organization/OrganizationList/OrganizationListViewController.swift
> +    private var subscriptionSet = Set<AnyCancellable>()
리액터킷 만든,, 한국 rx 장인이신 전수열님이 요런것도 만들어두셨더라구요..! 안쓰겠지만 있다고 공유하고싶었어요!
https://github.com/devxoul/CancelBag

2022-10-18 06:02 UTC, tea-hkim commented on Projects/DesignSystem/Sources/Component/ShadowTextFieldView.swift
> +        leftImage.image = UIImage(.magnifyingglass)
아 폰트 굵기가 달랐네요... 기호로 전환할 수 있는 방법을 찾아 commit 하겠습니다

2022-10-18 06:05 UTC, tea-hkim commented on Projects/App/Sources/UI/Organization/OrganizationList/OrganizationListViewController.swift
> +    // MARK: UI Function
ffd6d17 변경했습니다!
bindUI라는 mark 외에도 delegate라는 mark를 추가했습니다!

2022-10-18 06:18 UTC, tea-hkim commented on Projects/App/Sources/UI/Organization/OrganizationList/OrganizationListViewController.swift
> +        .eraseToAnyPublisher()
5493c11 수정했습니다!
제가 extension의 존재를 잊고있었네요...

2022-10-18 06:18 UTC, tea-hkim commented on Projects/App/Sources/UI/Organization/OrganizationList/OrganizationListViewController.swift
> +            .userInputTextPublisher
5493c11 수정했습니다!

2022-10-18 06:53 UTC, tea-hkim commented on Projects/App/Sources/UI/Organization/OrganizationList/View/Cell/OrganizationListCell.swift
> +        self.addSubviews([orgNameLabel, disclosureIndicator])
aec256c 수정했습니다!

2022-10-18 06:53 UTC, tea-hkim commented on Projects/App/Sources/UI/Organization/OrganizationList/View/Cell/OrganizationListCell.swift
> +            make.bottom.equalTo(self.snp.bottom).inset(16)
664db90 수정했습니다!
찾아보니 top과 bottom 모두 적용되는 `verticalEdges`라는 키워드가 있어서 이걸 사용하여 다음과 같이 변경하였습니다

```Swift

disclosureIndicator.snp.makeConstraints { make in
      make.right.equalTo(snp.right).inset(20)
      make.verticalEdges.equalToSuperview().inset(16)
}
```

2022-10-18 06:53 UTC, tea-hkim commented on Projects/App/Sources/UI/Organization/OrganizationList/View/Cell/OrganizationListCell.swift
> +    }
664db90 변경하였습니다!

2022-10-18 06:57 UTC, Gobans commented on Projects/App/Sources/UI/Organization/OrganizationList/OrganizationListViewController.swift
> +import DesignSystem
Design system도 서드파티 취급하기로 해서.. UIKit 밑에 놓아주세요!

2022-10-18 07:02 UTC, Gobans commented on Projects/App/Sources/UI/Organization/OrganizationList/OrganizationListViewController.swift
> +            .userInputTextPublisher
p4
```swift
searchingTextField.textDidEndEditingPublisher
                                .map
                                ...
                                ...
```


 로  publisher 밑에 명령어들로 라인을 주는게 가독성이 좋을 것 같아요

2022-10-18 07:09 UTC, Gobans commented on Projects/App/Sources/UI/Organization/OrganizationList/ViewModel/OrganizatinoListViewModel.swift
> +    private var orgNameArray: [String] = []
@Lia316 닉이 수정하신대로 프로퍼티와 publisher의 분리를 말씀 드린 것 입니다!!

2022-10-18 07:12 UTC, Gobans commented on Projects/App/Sources/UI/Organization/OrganizationList/ViewModel/OrganizatinoListViewModel.swift
> +    private var organizationArray: [Organization] = []
이거 아직 수정이 안된 것 같아요🥲

2022-10-18 08:58 UTC, tea-hkim commented on Projects/App/Sources/UI/Organization/OrganizationList/OrganizationListViewController.swift
> +import DesignSystem
eb677f8 반영했습니다!

2022-10-18 09:09 UTC, tea-hkim commented on Projects/App/Sources/UI/Organization/OrganizationList/OrganizationListViewController.swift
> +            .userInputTextPublisher
6b786e1 해결하였습니다! 확실히 가독성이 좋아졌네요

2022-10-18 09:09 UTC, tea-hkim commented on Projects/DesignSystem/Sources/Component/ShadowTextFieldView.swift
> +        // TODO: addSubViews extension으로 교체하기
6b786e1 교체하였습니다!

2022-10-18 09:13 UTC, tea-hkim commented on Projects/App/Sources/UI/Organization/OrganizationList/ViewModel/OrganizatinoListViewModel.swift
> +    private var organizationArray: [Organization] = []
dfdd6ea 수정하였습니다 변수명은 org로 통일했습니다!

2022-10-18 09:24 UTC, Gobans commented on Projects/App/Sources/UI/Organization/OrganizationList/OrganizationListViewController.swift
> +import DesignSystem
snapkit 서드파티입니다..! 알파벳순으로 정렬 해주세용🥲

2022-10-18 10:34 UTC, tea-hkim commented on Projects/App/Sources/UI/Organization/OrganizationList/OrganizationListViewController.swift
> +import DesignSystem
0e723b7 수정했습니다!

2022-10-19 03:27 UTC, tea-hkim commented on Projects/App/Sources/UI/Organization/OrganizationList/OrganizationListViewController.swift
> +        self.viewModel.$searchingArray.sink { orgNameArray in
555462d 변경하였습니다! 모든 로직이 ViewModel에서 돌아가도록 하였습니다

2022-10-19 03:29 UTC, tea-hkim commented on Projects/App/Sources/UI/Organization/OrganizationList/ViewModel/OrganizatinoListViewModel.swift
> +    }
555462d 변경하였습니다!!

2022-10-19 03:38 UTC, tea-hkim commented on Projects/DesignSystem/Sources/Component/ShadowTextFieldView.swift
> +    private let backgroundView = UIView()
ShadowTextFieldView는 도화지가 되는 View라고 생각합니다. 
그 위에 총 3개의 레이어가 필요하다고 생각했습니다.
1. leftImage, textField
2. backgoundView (하얀 배경의 width를 가지고 있는)
3. shadowView (그림자 역할을 하는)

이렇게 3개의 레이어를 둔 이유는 최상단이 textField만 있다면 메인 Appearance가 될 수 있겠지만,
같은 층에 leftImage를 가지고 있기 때문에 이 두 가지 컴포넌트의 배경이 될 View가 필요하다고 생각합니다.

2022-10-19 03:55 UTC, Gobans commented on Projects/DesignSystem/Sources/Component/ShadowTextFieldView.swift
> +    private let backgroundView = UIView()
그렇군요 상세한 설명 감사합니다!

2022-10-19 03:55 UTC, Gobans commented on Projects/DesignSystem/Sources/Component/ShadowTextFieldView.swift
> +        leftImage.image = UIImage(.magnifyingglass)
혹시 이 부분은 해결이 되었나요?

2022-10-19 04:51 UTC, tea-hkim commented on Projects/DesignSystem/Sources/Component/ShadowTextFieldView.swift
> +        leftImage.image = UIImage(.magnifyingglass)
해결 중에 있습니다 :) 해결하면 바로 commit 올리겠습니다

2022-10-19 07:29 UTC, tea-hkim commented on Projects/DesignSystem/Sources/Component/ShadowTextFieldView.swift
> +        leftImage.image = UIImage(.magnifyingglass)
555462d 변경하였습니다! 필요없는 이미지들은 삭제하고 system Image로 변경하였습니다

2022-10-19 08:38 UTC, Gobans approved these changes
수고하셨습니다!!! 👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍

2022-10-19 08:42 UTC, merged