[FEAT] 장소상세페이지 UI
DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY pull request #32
Opened 2022-10-18 01:55 UTC by chaneeii

## 작업내용

- [x] 장소상세페이지 UI 작업
- [x] 좌표에 맞춰 네이버 지도 및 카카오 지도 연결
- [x] 제보하기 - 메일보내기 연결

<img width="1000" alt="스크린샷 2022-10-18 오전 10 46 59" src="https://user-images.githubusercontent.com/63157395/196316130-82ee48d5-7048-42c7-93c2-70a4be8279a9.png">

https://user-images.githubusercontent.com/63157395/196316897-90acd426-055b-4eb2-a404-1460c8e2d52d.mov

## 리뷰포인트

- 각 지도 및 메일 확인은 시뮬레이터에서 안되고, 실제 기기에서 테스트해야합니다. 
- 비즈니스 로직을 제외한 ui 만 확인부탁드립니다

## Reference

## Checklist
- [x] 브랜치를 가져와 작업한 경우 이전 브랜치에 PR을 보냈는지 확인
- [x] 빌드를 위해 SceneDelegate 수정한 것 PR로 올리지 않았는지 확인
- [x] 필요없는 주석, 프린트문 제거했는지 확인
- [x] 컨벤션 지켰는지 확인
- [x] final, private 제대로 넣었는지 확인

2022-10-18 09:55 UTC, Gobans requested changes
고생하셨습니다 에버리! 👍
컨벤션, 접근 제어자 위주로 리뷰를 남겼으니 확인부탁드립니다.
그런데
<img width="240" alt="image" src="https://user-images.githubusercontent.com/56781342/196395663-33ef678c-149e-4a02-8f9f-632ba2e0ef1f.png">

많은 constraints 깨짐 오류가 뜨는데 확인부탁드립니다. (구동기기: iPhone 14 Pro Max)

2022-10-18 09:55 UTC, Gobans commented on Projects/App/Sources/Global/Utility/UrlUtils.swift
> +        }
p2
저희 iOS 15부터 지원인데, 필요없는 분기처리 같습니다.

2022-10-18 09:55 UTC, Gobans commented on Projects/App/Sources/UI/Place/PlaceDetail/View/Cell/CategoryCell.swift
> +    func configureUI() {
p2
private!

2022-10-18 09:55 UTC, Gobans commented on Projects/App/Sources/UI/Place/PlaceDetail/View/Cell/CategoryCell.swift
> +    func createLayout() {
p2
private!

2022-10-18 09:55 UTC, Gobans commented on Projects/App/Sources/Global/Utility/UrlUtils.swift
> +    static func openExternalLink(urlStr: String, _ handler:(() -> Void)? = nil) {
p3
Lint 체크 부탁드립니다
```suggestion
    static func openExternalLink(urlStr: String, _ handler: (() -> Void)? = nil) {
```

2022-10-18 09:55 UTC, Gobans commented on Projects/App/Sources/UI/Place/PlaceDetail/View/Cell/ReviewCell.swift
> +        $0.font = .systemFont(ofSize: 12, weight: .regular)
p3
.cation 이면 될 것 같습니다

2022-10-18 09:55 UTC, Gobans commented on Projects/App/Sources/UI/Place/PlaceDetail/View/Cell/ReviewCell.swift
> +        $0.font = .systemFont(ofSize: 11, weight: .regular)
p3
.cation2 이면 될 것 같습니다

2022-10-18 09:55 UTC, Gobans commented on Projects/App/Sources/UI/Place/PlaceDetail/View/Cell/ReviewCell.swift
> +    // MARK: Properties
p2
MARK: - 작대기가 없어요 (모든 파일)

2022-10-18 09:55 UTC, Gobans commented on Projects/App/Sources/UI/Place/PlaceDetail/View/Cell/ReviewCell.swift
> +    // MARK: UI Function
p3
저희 MARK를 extension 바로 위쪽으로 빼기로 했어요

2022-10-18 09:55 UTC, Gobans commented on Projects/App/Sources/UI/Place/PlaceDetail/View/Cell/ReviewCell.swift
> +    }
p3
안쓰는 function은 지워도 될 것 같아요

2022-10-18 09:55 UTC, Gobans commented on Projects/App/Sources/UI/Place/PlaceDetail/View/Cell/ReviewCell.swift
> +    func createLayout() {
p2
private!

2022-10-18 09:55 UTC, Gobans commented on Projects/App/Sources/UI/Place/PlaceDetail/View/Views/EvaluationItemView.swift
> +    }
p3
공백 위치가 바뀐 것 같아요

2022-10-18 09:55 UTC, Gobans commented on Projects/App/Sources/UI/Place/PlaceDetail/View/Views/EvaluationItemView.swift
> +        self.bringSubviewToFront(countLabel)
p3
self 안써도 될 것 같아요

2022-10-20 01:01 UTC, chaneeii commented
디자인 전체 수정으로 인한 PR 클로즈

살려줘,,,,,,,,,

2022-10-20 01:02 UTC, chaneeii commented
다시 살린다

2022-10-20 01:09 UTC, chaneeii commented on Projects/App/Sources/Global/Utility/UrlUtils.swift
> +        }
싫어요...옛날이 좋아요🔥

2022-10-20 01:10 UTC, chaneeii commented on Projects/App/Sources/UI/Place/PlaceDetail/View/Cell/CategoryCell.swift
> +    func configureUI() {
cell configure 라서 private 하면 쓰는쪽에서 configure 를 못합니다

2022-10-20 01:11 UTC, chaneeii commented on Projects/App/Sources/UI/Place/PlaceDetail/View/Cell/ReviewCell.swift
> +        $0.font = .systemFont(ofSize: 12, weight: .regular)
ui 대공사 예정
🥹 ui문의사절 🥹

2022-10-20 01:11 UTC, chaneeii commented on Projects/App/Sources/UI/Place/PlaceDetail/View/Cell/ReviewCell.swift
> +        $0.font = .systemFont(ofSize: 11, weight: .regular)
ui 대공사 예정
🥹 ui문의사절 🥹

2022-10-20 01:11 UTC, chaneeii commented on Projects/App/Sources/UI/Place/PlaceDetail/View/Cell/ReviewCell.swift
> +    // MARK: Properties
고반이 옛날 안넣어줬자나요..............🥹

2022-10-20 01:27 UTC, tea-hkim approved these changes

2022-10-20 05:54 UTC, chaneeii commented on Projects/App/Sources/Global/Utility/UrlUtils.swift
> +        }
util 이라서 우선 다 대응가능하도록 두겠습니당

2022-10-20 11:47 UTC, chaneeii commented on Projects/App/Sources/Global/Utility/UrlUtils.swift
> +    static func openExternalLink(urlStr: String, _ handler:(() -> Void)? = nil) {
<img width="593" alt="스크린샷 2022-10-20 오후 8 47 00" src="https://user-images.githubusercontent.com/63157395/196940159-a9697c77-3084-4233-a0d6-8e026d97ea9c.png">


안걸려요요..!

하지만 수정

2022-10-20 11:48 UTC, chaneeii commented on Projects/App/Sources/UI/Place/PlaceDetail/View/Views/EvaluationItemView.swift
> +        self.bringSubviewToFront(countLabel)
bringSubviewToFront 에서 앞에 들어가는 뷰가 중요해서 명시적으로 작성햇습니다

2022-10-20 12:00 UTC, italsehf approved these changes
무지성 어프로브단 출동

2022-10-20 12:01 UTC, merged