[Design] 리뷰 등록 UI
DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY pull request #45
Opened 2022-10-23 14:08 UTC by Lia316

## 작업내용

- [x] 리뷰 평가하기 화면
- [x] 리뷰 사진 추가하기 화면
- [x] 메뉴 텍스트필드 키보드 여부에 따른 레이아웃 동적 변화

| iPhone SE 3rd| iPhone  13 | iPhone  13 Pro | iPhone  14 Pro |
|:---:|:---:|:---:|:---:|
|<img width="180" src="https://user-images.githubusercontent.com/73650994/197396401-e71b87a1-b70b-463a-805a-e62429767182.gif">|<img width="180" src="https://user-images.githubusercontent.com/73650994/197396360-3dad24a7-03e8-4a12-ab12-c9fa79c4fc64.gif">|<img width="180" src="https://user-images.githubusercontent.com/73650994/197396361-dc860b4c-a7cf-47a0-a1ec-6405bb28cfa7.gif">|<img width="180" src="https://user-images.githubusercontent.com/73650994/197396364-71e55ef8-8d5b-439a-a7c3-8bbe1c1824eb.gif">|

## 리뷰포인트
- 고민
<img width="200" alt="image" src="https://user-images.githubusercontent.com/73650994/197396601-b5eab22a-2f5c-4f13-9b6a-ab88b17c84b6.png">
2줄 레이아웃을 프로 맥스 시리즈에서도 적용해야할까요?
- 현재 텍스트필드를 그냥 누르면 키보드가 올라가지 않더라도 타이틀뷰에 애니메이션이 적용됩니다. (디바이스 별 상이)
  - 실 기기에서는 ..거의 손으로 누르고 키보드가 나오니까 괜찮지... 않을까요?
 

## Reference

- [SnapKit에서 SafeArea 사용하기](https://velog.io/@heyksw/iOS-SnapKit-NavigationBar-Constraint)
- [SnapKit의 constraints를 다루는 코드 설명 (updateConstraints와 remakeConstraints의 차이)](https://ios-development.tistory.com/609)
- [터치하면 키보드 내리는 법](https://incoffee.tistory.com/1)
- [뷰 isHidden 애니메이션 적용하는 법 - 스택오버플로우](https://stackoverflow.com/questions/44198487/animating-uiview-ishidden-subviews)

## Checklist
- [x] 브랜치를 가져와 작업한 경우 이전 브랜치에 PR을 보냈는지 확인
- [x] 빌드를 위해 SceneDelegate 수정한 것 PR로 올리지 않았는지 확인
- [x] 필요없는 주석, 프린트문 제거했는지 확인
- [x] 컨벤션 지켰는지 확인
- [x] final, private 제대로 넣었는지 확인
- [x] 다양한 디바이스에 레이아웃이 대응되는지 확인
  - [x] iPhone SE
  - [x] iPhone 13
  - [x] iPhone 13 Pro Max
  - [x] iPhone 14 Pro

2022-10-24 09:57 UTC, tea-hkim approved these changes
오 코드가 잘 정리되어 있어서 보기 편하네요 :) 
덕분에 키보드 height에 따라 뷰를 변경하는 코드를 잘 썼습니다 ㅎㅎ

2022-10-24 12:20 UTC, Gobans requested changes
고생하셨습니다 리아!
아주 영감을 주는 코드네요

그런데 키보드가 올라가지도 않았는데 sink가 되서 저 타이틀 애니메이션이 실행되는군요?? 처음 알았네요
테스트 해보니 textfield 터치할 떄 키보드가 안나오면  hide로 인식이 되네요.
그럼 아예 endFrameHeight를 viewController의 property (nil) 로 가지고 있다가 키보드가 나타나면 값을 주고, 이를 분기처리에 사용하면 이 사소한 버그를 처리할 수 있을 것 같네요


```swift
// viewController
private var endFrameHeight: CGFloat?

// keyboardwillshow publisher
guard let endFrame = notification.userInfo?[UIResponder.keyboardFrameEndUserInfoKey] as? NSValue else { return }
self.endFrameHeight = endFrame.cgRectValue.height

// updateLayout
if endFrameHeight!= nil {
    titleView.willShow(with: 1)
}
```

2022-10-24 12:20 UTC, Gobans commented on Projects/App/Sources/UI/Review/ReviewRegisterViewController.swift
> +            $0.horizontalEdges.bottom.equalToSuperview().inset(20)
p1
bottom 이 view bottom의 20 으로 잡혀있어서 아주 딱 붙어있어요
<img width="250" alt="image" src="https://user-images.githubusercontent.com/56781342/197518328-36a80adf-b15f-47c5-a584-db182260c124.png">
bottom 은 safeLayoutGuide로 따로 constraints를 지정해줘야하지 않나 싶습니다
(update constraints 도 동일!)

2022-10-24 12:20 UTC, Gobans commented on Projects/App/Sources/UI/Review/ReviewRegisterViewController.swift
> +                UIView.animate(withDuration: 2) {
p2
animate 는 필요없는 코드 같습니다. 자연스럽게 레이아웃이 변경되는 것은 ` self.view.layoutIfNeeded()` 이 코드 덕분인 것 같네요. animate는 딱히 역할을 안하는듯요??

2022-10-24 12:20 UTC, Gobans commented on Projects/DesignSystem/Sources/Extension/UIView+.swift
> +    func willHide(with duration: CGFloat) {
👍

2022-10-24 12:20 UTC, Gobans commented on Projects/App/Sources/UI/Review/Views/EvaluationButton.swift
> +    enum EvaluationType {
이렇게 하는거군요 👍

2022-10-24 12:20 UTC, Gobans commented on Projects/App/Sources/UI/Place/PlaceDetail/View/Cell/ReviewCell.swift
> +//        $0.image = UIImage(.img_good_circle)
Q
요거는 나중에 쓰는 코드인가요?

2022-10-24 12:20 UTC, Gobans commented on Projects/App/Sources/UI/Place/PlaceDetail/View/Cell/ReviewCell.swift
> +//        }
Q
요거는 나중에 쓰는 코드인가요?

2022-10-24 12:23 UTC, Lia316 commented on Projects/App/Sources/UI/Place/PlaceDetail/View/Cell/ReviewCell.swift
> +//        $0.image = UIImage(.img_good_circle)
저건 버리가 나중에 삭제해주실 거라,,

제가 이미지를 삭제해버려서 저 코드를 주석처리하지 않으면 빌드가 되지 않아서 주석 처리 했습니다.
제가 작성한 코드는 아니기에 차마 삭제하지는 못했습니다.

2022-10-24 12:23 UTC, Lia316 commented on Projects/App/Sources/UI/Place/PlaceDetail/View/Cell/ReviewCell.swift
> +//        }
동일한 이유입니다 ㅠㅠㅠ 제가 작성하지 않아서 차마 삭제하지 못했습니다.

2022-10-24 12:34 UTC, Lia316 commented on Projects/App/Sources/UI/Review/ReviewRegisterViewController.swift
> +            $0.horizontalEdges.bottom.equalToSuperview().inset(20)
652af336114c41fbe36deb2a4c75d396a0508f59 깜박하고 있었는데 잡아주셔서 감사합니다~!

2022-10-24 12:35 UTC, Lia316 commented on Projects/App/Sources/UI/Review/ReviewRegisterViewController.swift
> +                UIView.animate(withDuration: 2) {
호오... 몰랐네요..!! 9cc3a189356f476325b221ca6446bf4faf560f9d 반영 완료했습니다.
고반은 직접 삭제해보시면서 알게 되신 건가요?? ✨👀

2022-10-24 12:47 UTC, Gobans commented on Projects/App/Sources/UI/Review/ReviewRegisterViewController.swift
> +                UIView.animate(withDuration: 2) {
https://zeddios.tistory.com/359
여기 글을 읽었었는데, 생각이나서 테스트해보니 알게되었습니다!

2022-10-24 12:49 UTC, Lia316 commented on Projects/App/Sources/UI/Review/ReviewRegisterViewController.swift
> +                UIView.animate(withDuration: 2) {
오 그렇군요! 감사합니다

2022-10-24 12:54 UTC, chaneeii requested changes
Preveiw 목적으로 사용하는 SwiftUI 전체 디버깅 처리해주세요!

저는 UI 코드는 자율성을 높게 드리고 싶어서 + 시간이 없어서 요렇게만 하도록 하겠습니다

고생하셨습니다

2022-10-24 12:54 UTC, chaneeii commented on Projects/App/Sources/UI/Place/PlaceDetail/View/Cell/ReviewCell.swift
> +//        $0.image = UIImage(.img_good_circle)
나중에 저파일을 일괄적으로 삭제할예정인데 삭제하셔버렸군요...?
머지할때 돌려놔 주세요!
=> 제 코드 우선으로 머지해주세요... 저기 바뀌었을것같네요

타인의 코드에 적용되는 어셋은 충돌이 날수있기때문에 크리티컬한 일이 아닌이상 협의 없이 삭제하지 않도록 부탁드립니다 ㅠ

2022-10-24 12:54 UTC, chaneeii commented on Projects/App/Sources/UI/Place/PlaceDetail/View/Cell/ReviewCell.swift
> +//        }
마찬가지 입니다.

2022-10-24 12:54 UTC, chaneeii commented on Projects/App/Sources/UI/Place/PlaceDetail/View/Views/EvaluationItemView.swift
> +            imageView.image = UIImage(.img_reviewfriends_bad)
💬
전 아직 이친구들로 안바꿨는데 어떻게 하나요?
SVG 하나로 통일하기로 확정한건가요? 공유부탁드립니다

2022-10-24 12:54 UTC, chaneeii commented on Projects/App/Sources/UI/Review/EvaluationViewController.swift
> +import SnapKit
p1
스유 preview 용이면 if - debug 처리 바랍니다!
배포코드에 들어가면 좋지않습니다 🥲

2022-10-24 12:54 UTC, chaneeii commented on Projects/App/Sources/UI/Review/EvaluationViewController.swift
> +            $0.height.equalTo(evaluationStackView.snp.width).multipliedBy(0.45)
💬
리아가 multipliedBy 를 사용하는 방식을 저도 따라해보려고 했는데,
가독성이 좋지않아서 사실 잘 이해가 안가서 사용하는데 고민이 많더라구요
(숫자계산법도 추측해야하고, height 이나 offset 중 어디에 적용해야하는지 등)

혹시 나중에 리아가 저 숫자를 계산+ 적용하는 포인트 같은 방식을 공유해주신다면 팀원모두 이해하는데 도움이 될 것 같습니다

2022-10-24 13:33 UTC, Lia316 commented
@chaneeii 일단 에셋 코드 모두 복구 완료했습니다!

2022-10-24 13:37 UTC, Lia316 commented on Projects/App/Sources/UI/Place/PlaceDetail/View/Views/EvaluationItemView.swift
> +            imageView.image = UIImage(.img_reviewfriends_bad)
그때 아보랑 같이 이야기했을 때는 svg 하나로 해도 괜찮을 것 같다고만 이야기해서
확정은 다 함께 이야기해봐야할 것 같아요..!
@Chaeho-Min @chaneeii 
일단 버리 코드 복구 완료요

2022-10-24 13:44 UTC, Lia316 commented on Projects/App/Sources/UI/Review/EvaluationViewController.swift
> +import SnapKit
232fc681764b1d7dc1531d80b1099cdb2e1c2643 반영 완료요!

2022-10-24 13:51 UTC, Lia316 commented
> 고생하셨습니다 리아! 아주 영감을 주는 코드네요
> 
> 그런데 키보드가 올라가지도 않았는데 sink가 되서 저 타이틀 애니메이션이 실행되는군요?? 처음 알았네요 테스트 해보니 textfield 터치할 떄 키보드가 안나오면 hide로 인식이 되네요. 그럼 아예 endFrameHeight를 viewController의 property (nil) 로 가지고 있다가 키보드가 나타나면 값을 주고, 이를 분기처리에 사용하면 이 사소한 버그를 처리할 수 있을 것 같네요
> 
> ```swift
> // viewController
> private var endFrameHeight: CGFloat?
> 
> // keyboardwillshow publisher
> guard let endFrame = notification.userInfo?[UIResponder.keyboardFrameEndUserInfoKey] as? NSValue else { return }
> self.endFrameHeight = endFrame.cgRectValue.height
> 
> // updateLayout
> if endFrameHeight!= nil {
>     titleView.willShow(with: 1)
> }
> ```

제안해주셔서 감사드립니다! 
그런데 해당 버그는 처음에만 발생하는 게 아니라,
텍스트필드를 선택했는데도 키보드가 올라오지 않을 때마다 발생해서, 이 방법은 임시 방편인 것 같습니다 🥲

실제 기기에서는 웬만하면 텍스트필드를 터치할 때마다 키보드가 올라와서 괜찮을 것 같아요,,

2022-10-24 13:56 UTC, Chaeho-Min requested changes
Uploading Simulator Screen Recording - iPhone 14 - 2022-10-24 at 21.13.14.mp4…

제가 막 던져놓기만 한 디자인을 기기별로 대응 가능하게 레이아웃짜느라 정말 고생 많으셨습니다ㅠㅠ
여기 코드리뷰하면서 디자인에 기기별로 어떻게 대응해야 하는지를 꼭 적어놔야 겠다는걸 깨달았습니다... 안 적어놓으니까 개발 생산성도 떨어지고 코드리뷰도 오래 걸리고 여러모로 안 좋네요...ㅠㅜ
디자인 의도와 다른 부분을 코멘트 남겨놨으니 확인하시고 반영 부탁드립니다!

2022-10-24 13:56 UTC, Chaeho-Min commented on Projects/App/Sources/UI/Review/Views/EvaluationButton.swift
> +        evaluationStackView.spacing = 16
p1;

<img width="511" alt="image" src="https://user-images.githubusercontent.com/75792767/197531980-c7594cd3-f1ea-41ab-b9b1-919241ee7f4e.png">

여기 간격 10입니다!

2022-10-24 13:56 UTC, Chaeho-Min commented on Projects/App/Sources/UI/Review/Views/EvaluationButton.swift
> +        evaluationIcon.image = type.image
p1;

아이콘이 UIImage로 들어가기 때문에 contentMode를 지정해줘야 합니다!
기본으로 .scaleToFit으로 되어있는것 같아서 비율이 깨질 수도 있네요.

```suggestion
        evaluationIcon.image = type.image
        evaluationIcon.contentMode = .scaleAspectFit
```

2022-10-24 13:56 UTC, Chaeho-Min commented on Projects/App/Sources/UI/Review/Views/EvaluationButton.swift
> +    }
디자인 할 때 디자인 의도를 다 적어놨어야 됐는데, 죄송합니다😭

<img width="344" alt="image" src="https://user-images.githubusercontent.com/75792767/197539073-de4e2786-aba0-433d-a6ba-f4b82c1b0c6c.png">

원래 의도는 회색 셀 내부 inset을 모두 20으로 잡고, 회색 셀은 100x128로 고정하는 것이었습니다.
그런데 지금 생각해보니 이러면 Pro Max에서 너무 작아보일거 같아서 지금 짠 레이아웃에서 inset 20만 고치고 이대로 가려고 했는데, multipliedBy를 쓰다보니까 기기마다 비율이 달라지게 돼서 좀 찝찝하더라고요😅

<img width="1149" alt="image" src="https://user-images.githubusercontent.com/75792767/197538056-e0906a3e-613f-400b-8847-c510034759a1.png">

그래서 고민해봤는데 그냥 버튼 세 개 크기를 고정시키는게 나을 것 같습니다...

<img width="1162" alt="image" src="https://user-images.githubusercontent.com/75792767/197536236-75fd4c6e-849d-4f6a-9f74-cecf57d561f4.png">

```swift
    private func createLayout() {
        addSubviews([backgroundView, evaluationStackView, button])
        
        backgroundView.snp.makeConstraints {
            $0.edges.equalToSuperview()
            $0.width.equalTo(100) // 회색 셀 크기 고정
            $0.height.equalTo(128) // 회색 셀 크기 고정
        }
        evaluationStackView.snp.makeConstraints {
            $0.edges.equalTo(backgroundView).inset(20) // 원래 디자인 의도대로 회색 셀과 내부 컨텐츠의 inset을 20을 줌
        }
        evaluationStackView.addArrangedSubviews([evaluationIcon, evaluationLabel])
        evaluationIcon.snp.makeConstraints {
            $0.centerX.equalToSuperview()
            $0.width.height.equalTo(60) // 아이콘 크기 60x60으로 고정
        }
        evaluationLabel.snp.makeConstraints {
            $0.centerX.equalToSuperview()
            $0.width.greaterThanOrEqualTo(30)
        }
        button.snp.makeConstraints {
            $0.edges.equalToSuperview()
        }
    }
```

2022-10-24 13:56 UTC, Chaeho-Min commented on Projects/App/Sources/UI/Review/EvaluationViewController.swift
> +        evaluationStackView.spacing = 10
p1;

<img width="553" alt="image" src="https://user-images.githubusercontent.com/75792767/197540441-d14e02cb-8e9d-4e49-8479-9a5bd3bb86b8.png">

여기 간격 15입니다!

```suggestion
        evaluationStackView.spacing = 15
```

2022-10-24 13:56 UTC, Chaeho-Min commented on Projects/App/Sources/UI/Review/EvaluationViewController.swift
> +            $0.height.equalTo(evaluationStackView.snp.width).multipliedBy(0.45)
p1;

앞에서 말한 버튼 세 개를 고정크기로 가기로 했다면 이렇게 바꿔주시고, 아니면 안바꾸셔도 됩니다!

```suggestion
            $0.centerX.centerY.equalToSuperview()
```

2022-10-24 13:56 UTC, Chaeho-Min commented on Projects/App/Sources/UI/Review/ReviewRegisterViewController.swift
> +        safeArea.trailingAnchor.constraint(equalTo: guide.trailingAnchor).isActive = true
p4;

이 코드 필요한가요? snapKit에서 safeArea 필요하면 그냥 view.safeAreaLayoutGuide 썼던 것 같아서요

2022-10-24 13:56 UTC, Chaeho-Min commented on Projects/App/Sources/UI/Review/ReviewRegisterViewController.swift
> +            $0.trailing.equalToSuperview().inset(40)
p2;

요 inset(40)은 뭔가요?
특별한 이유가 없다면 없애주세요!

2022-10-24 14:09 UTC, Gobans approved these changes
@Lia316 TextField를 선택하여 키보드가 올라오지 않을때마다 발생하기 떄문에 분기처리가 가능할 듯 보입니다!!
1. TextField를 선택할때 계속 키보드가 올라오지 않음 (계속 눌러도 keyboardHidePublisher만 호출, endFrameHeight에 값이 입력되지 않음)
2. 키보드가 올라오면 그떄부터는 endFrameHeight에 값이 들어가며 정상 동작
이런 흐름인데, 크게 문제될 것 같진 않아서 리아의 판단에 따라 코드 추가하시면 될 것 같습니다👍

2022-10-24 14:16 UTC, Lia316 commented on Projects/App/Sources/UI/Review/ReviewRegisterViewController.swift
> +        safeArea.trailingAnchor.constraint(equalTo: guide.trailingAnchor).isActive = true
요거 버리한테 피드백 받고 다음 PR에서 고쳐놨습니다,, 
나중에 머지되면 반영될 듯 해요!

2022-10-24 14:17 UTC, Lia316 commented on Projects/App/Sources/UI/Review/ReviewRegisterViewController.swift
> +            $0.trailing.equalToSuperview().inset(40)
없으면..
<img width="348" alt="image" src="https://user-images.githubusercontent.com/73650994/197547943-4a7dceae-b36f-4f54-b5f5-bbe32e16c299.png">
요렇게 생기지 않아서 추가했습니다 🥲
설마 저거 텍스트로 줄바꿈 때려박는 건가요...???

2022-10-24 14:20 UTC, Chaeho-Min commented on Projects/App/Sources/UI/Review/ReviewRegisterViewController.swift
> +            $0.trailing.equalToSuperview().inset(40)
아 없으면 줄넘김이 되지 않아서 추가했다는 말씀이신가요?
저는 식당이름 길이가 어떻게 될지 모르니까 그냥 텍스트에 \n 넣어서 줄바꿈하는걸 생각하고 있긴 했습니다!

2022-10-24 14:24 UTC, Lia316 commented on Projects/App/Sources/UI/Review/Views/EvaluationButton.swift
> +        evaluationIcon.image = type.image
아 오토레이아웃으로 비율 고정해놔서 상관 없을 줄 알았는데
나중에 이미지 어셋이 바뀔 수도 있으니까 해두는 게 좋겠네요!

2022-10-24 14:42 UTC, Lia316 commented on Projects/App/Sources/UI/Review/ReviewRegisterViewController.swift
> +            $0.trailing.equalToSuperview().inset(40)
보니까 줄바꿈이 낫네요,, 9a5214929a64a8203485870f4a8d812d2989f655 반영했습니다!

2022-10-24 14:43 UTC, Lia316 commented on Projects/App/Sources/UI/Review/Views/EvaluationButton.swift
> +        evaluationIcon.image = type.image
9a5214929a64a8203485870f4a8d812d2989f655 반영 완료요~

2022-10-24 14:43 UTC, Lia316 commented on Projects/App/Sources/UI/Review/Views/EvaluationButton.swift
> +        evaluationStackView.spacing = 16
9a5214929a64a8203485870f4a8d812d2989f655 반영!

2022-10-24 14:44 UTC, Lia316 commented on Projects/App/Sources/UI/Review/EvaluationViewController.swift
> +        evaluationStackView.spacing = 10
9a5214929a64a8203485870f4a8d812d2989f655 반영 완료~

2022-10-24 14:56 UTC, Lia316 commented on Projects/App/Sources/UI/Review/Views/EvaluationButton.swift
> +    }
2a4bb6e36b19acedf77f6b4dfb7f4de51deaf780 반영 완료요~

아보가 주신 코드랑 차이가 하나 있다면, 
backgroundView에 크기 고정하는 게 이상해서 저 뷰 자체를 크기 고정했습니다!

2022-10-24 14:56 UTC, Lia316 commented on Projects/App/Sources/UI/Review/EvaluationViewController.swift
> +            $0.height.equalTo(evaluationStackView.snp.width).multipliedBy(0.45)
2a4bb6e36b19acedf77f6b4dfb7f4de51deaf780 옙 변경 완료요!

2022-10-24 15:06 UTC, Lia316 commented
> TextField를 선택하여 키보드가 올라오지 않을때마다 발생하기 떄문에 분기처리가 가능할 듯 보입니다!!
> 
> 1. TextField를 선택할때 계속 키보드가 올라오지 않음 (계속 눌러도 keyboardHidePublisher만 호출, endFrameHeight에 값이 입력되지 않음)
> 2. 키보드가 올라오면 그떄부터는 endFrameHeight에 값이 들어가며 정상 동작
>    이런 흐름인데, 크게 문제될 것 같진 않아서 리아의 판단에 따라 코드 추가하시면 될 것 같습니다👍

해당 버그가 대부분 첫 인터렉션에서 등장해서, 첫 인터렉션 부분은 해결 가능하나,
이후 인터렉션에서는 여전히 버그가 발생하게 됩니다 😂

2022-10-24 15:12 UTC, Lia316 commented
@chaneeii  @Chaeho-Min 리뷰 반영 완료했습니다!

2022-10-25 01:24 UTC, Chaeho-Min approved these changes
🚀🚀🚀

2022-10-25 03:08 UTC, chaneeii approved these changes
고생하셧습니다!

2022-10-25 08:38 UTC, merged