[Feat] review card UI
DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY pull request #49
Opened 2022-10-24 11:30 UTC by Lia316

## 작업내용

- [x] review card view UI
- [x] navigation bar button custom
- [x] viewController 간 전환
- [x] 메뉴 사진 여부에 따른 UI 변화

|iPhone SE 3rd|iPhone 13|iPhone 13 Pro Max|
|:---:|:---:|:---:|
|<img width="250" src="https://user-images.githubusercontent.com/73650994/197514860-6732f163-49cd-400e-ac38-9ab2a68220e2.png">|<img width="250" src="https://user-images.githubusercontent.com/73650994/197514916-fbdab3bf-e6c9-492b-ace8-b6d66f7f4f32.png">|<img width="250" src="https://user-images.githubusercontent.com/73650994/197514947-2fea6a80-68a4-4e1b-ae0a-f7bdcb3fc565.png">|

## 리뷰포인트

## Reference

- [view에 padding 주기](https://ios-development.tistory.com/698)
- [뷰 전환 로직 - 여러 개의 뷰컨트롤러 Pop하기](https://www.darrengillman.com/index.php/2019/10/22/pop-multiple-view-controllers-from-the-navigation-stack/)
- [네비게이션 바 back button custom](https://sarunw.com/posts/how-to-change-back-button-image/)
- [bold / italic font 바로 먹이기](https://spin.atomicobject.com/2018/02/02/swift-scaled-font-bold-italic/)

## Checklist
- [x] 브랜치를 가져와 작업한 경우 이전 브랜치에 PR을 보냈는지 확인
- [x] 빌드를 위해 SceneDelegate 수정한 것 PR로 올리지 않았는지 확인
- [x] 필요없는 주석, 프린트문 제거했는지 확인
- [x] 컨벤션 지켰는지 확인
- [x] final, private 제대로 넣었는지 확인
- [x] 다양한 디바이스에 레이아웃이 대응되는지 확인
  - [x] iPhone SE
  - [x] iPhone 13
  - [x] iPhone 13 Pro Max

2022-10-24 13:14 UTC, chaneeii approved these changes
고생하셨습니다 🔥

2022-10-24 13:14 UTC, chaneeii commented on Projects/App/Sources/UI/Review/EvaluationViewController.swift
> +        safeArea.trailingAnchor.constraint(equalTo: guide.trailingAnchor).isActive = true
p3)
.top.equalTo(view.safeAreaLayoutGuide.snp.top)
요런식으로 사용할수있습니다!

2022-10-24 13:14 UTC, chaneeii commented on Projects/App/Sources/UI/Review/ReviewCardViewController.swift
> +    }
👍
Generic 까지 사용해서 만들어서 Util 로 빼서 다같이 사용해도 좋을 것 같네요!

2022-10-24 13:14 UTC, chaneeii commented on Projects/App/Sources/UI/Review/ReviewCardViewController.swift
> +        navigationController?.navigationBar.backIndicatorTransitionMaskImage = backImage
p5)
요기는 정말 사람마다 스타일이 다 다르네요
나중에 따로 컴포넌트화 시킵시다 @Chaeho-Min 그래야겠죠...?

2022-10-24 13:14 UTC, chaneeii commented on Projects/App/Sources/UI/Review/ReviewCardViewController.swift
>  }
p1 )
스유코드는 if-debug 처리부탁드립니다

2022-10-24 13:14 UTC, chaneeii commented on Projects/DesignSystem/Sources/Component/PaddingLabel.swift
> +final public class PaddingLabel: UILabel {
p5
요거 저도 비슷한거 만들어 놨는데 1.0 이후에 한번 통일해요!

2022-10-24 13:14 UTC, chaneeii commented on Projects/DesignSystem/Sources/Extension/UIFont+.swift
> +}
👍
유용한게 생겼군요!

2022-10-24 13:14 UTC, chaneeii commented on Projects/DesignSystem/Sources/Extension/UIView+.swift
> +    }
p5)
이것도 만들어 뒀는데 우선 1.0 이 급하니 요거 이후에 통일합니당

2022-10-24 13:53 UTC, Gobans reviewed
고생하셨습니다 리아!!!! 달리시는군요
**버그가 있어요!**
navigationController 로 뷰 이동을 하다가 pop 으로 돌아가서 다시 뷰 이동을 하면 x버튼이 생겨요 🥲
<img width="250" alt="image" src="https://user-images.githubusercontent.com/56781342/197538963-51e3df98-2d96-4bf1-bba9-4abcd9cd54d1.gif">

근데 이게 후에 문제가 안되는 버그라면 상관없을 것 같습니다~!

2022-10-24 13:56 UTC, Lia316 commented
> 고생하셨습니다 리아!!!! 달리시는군요 **버그가 있어요!** navigationController 로 뷰 이동을 하다가 pop 으로 돌아가서 다시 뷰 이동을 하면 x버튼이 생겨요 🥲 ![image](https://user-images.githubusercontent.com/56781342/197538963-51e3df98-2d96-4bf1-bba9-4abcd9cd54d1.gif) [ ![image](https://user-images.githubusercontent.com/56781342/197538963-51e3df98-2d96-4bf1-bba9-4abcd9cd54d1.gif) ](https://user-images.githubusercontent.com/56781342/197538963-51e3df98-2d96-4bf1-bba9-4abcd9cd54d1.gif) [ ](https://user-images.githubusercontent.com/56781342/197538963-51e3df98-2d96-4bf1-bba9-4abcd9cd54d1.gif)
> 
> 근데 이게 후에 문제가 안되는 버그라면 상관없을 것 같습니다~!

후후 이미 알고 있었습니다 😎
원래는 저 뷰로 돌아가는 게 아니라 아예 맛집 상세 뷰로 돌아가기 때문에 
해당 버그는 지나쳐도 괜찮습니다!

2022-10-24 13:57 UTC, Lia316 commented on Projects/App/Sources/UI/Review/EvaluationViewController.swift
> +        safeArea.trailingAnchor.constraint(equalTo: guide.trailingAnchor).isActive = true
헐... 아니 이런 걸 왜 아무도 안 알려줬죠..?
저 코드 나름 같은 고민을 하신 분의 블로그에서 본 거였는데,,,,,,,,
ㅠㅠㅠㅠ 감사합니다

2022-10-24 14:10 UTC, Lia316 commented on Projects/App/Sources/UI/Review/EvaluationViewController.swift
> +        safeArea.trailingAnchor.constraint(equalTo: guide.trailingAnchor).isActive = true
[7139b25](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/49/commits/7139b254e2ae12c48d876cd8bf2c51dfe4bcbecc) 반영했습니다!

2022-10-24 14:13 UTC, Lia316 commented on Projects/App/Sources/UI/Review/ReviewCardViewController.swift
>  }
이전 PR에서 반영했습니다!
이전 브랜치 머지해서 현재 반영되어 있습니다. [21bca4d](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/49/commits/21bca4d28a63302665fc0ceee68a4a839cf5f846)

2022-10-24 14:17 UTC, Chaeho-Min commented on Projects/App/Sources/UI/Review/ReviewCardViewController.swift
> +        navigationController?.navigationBar.backIndicatorTransitionMaskImage = backImage
무조건해야죠

2022-10-24 16:11 UTC, chaneeii commented on Projects/App/Sources/UI/Review/ReviewCardViewController.swift
> +        navigationController?.navigationBar.backIndicatorTransitionMaskImage = backImage
해줘
<img src="https://user-images.githubusercontent.com/63157395/197574076-c2d1f9db-4d77-4a71-9006-925a087ce011.png" width="200">

2022-10-25 01:13 UTC, Chaeho-Min requested changes
기기별 대응 잘 하셨네요 코드 잘 봤습니다!
피그마랑 값이 다른 부분이 몇 군데 있어서 여기만 수정 요청드릴게요!

2022-10-25 01:13 UTC, Chaeho-Min commented on Projects/App/Sources/UI/Review/Views/ReviewCardView.swift
> +        backgroundView.layer.opacity = 0.6
p1;

<img width="161" alt="image" src="https://user-images.githubusercontent.com/75792767/197557879-4cf99e04-1f52-4019-a79c-74d076f5fb48.png">

오잉 여기도 수정됐었나? 검은색 레이어 opacity값 0.4입니다!

2022-10-25 01:13 UTC, Chaeho-Min commented on Projects/App/Sources/UI/Review/Views/ReviewCardView.swift
> +        ])
p2;

<img width="397" alt="image" src="https://user-images.githubusercontent.com/75792767/197557340-634d89ee-c09d-490e-8088-33cda9c4c20c.png">

nicknameStaticLabel과 nicknameLabel 사이 간격은 4인데, nicknameLabel과 dateStaticLabel 사이 간격은 10입니다.
StackView를 나누거나 StackView를 쓰지 않고 레이아웃을 잡아야겠네요.

2022-10-25 01:13 UTC, Chaeho-Min commented on Projects/App/Sources/UI/Review/Views/ReviewCardView.swift
> +        placeNameLabel.numberOfLines = 2
p2;

식당 이름하고 주소는 글자 수가 얼마나 될지 몰라서 웬만하면 안 잘리게 하고 싶습니다.
리뷰 카드에서 userStackView와 categoryLabel 사이 여백이 SE에서도 커가지고 라인 수 제한 없애도 큰 문제는 없을 것 같습니다!

2022-10-25 01:13 UTC, Chaeho-Min commented on Projects/App/Sources/UI/Review/Views/ReviewCardView.swift
> +            $0.width.greaterThanOrEqualTo(33)
질문;

저 궁금한게 Label은 폰트 크기와 글자 수에 따라 이미 정해진 크기가 있는데 오토레이아웃에서도 이렇게 너비랑 높이를 다 지정해줘야 하나요?
그리고 이 너비랑 높이 값은 피그마에서 가져오신건가요? 확실하진 않는데 텍스트는 아마 Xcode 상에서의 크기랑 피그마에서의 크기랑 좀 다를 것 같습니다 피그마 믿을 수가 없어서;;

2022-10-25 01:13 UTC, Chaeho-Min commented on Projects/App/Sources/UI/Review/ReviewCardViewController.swift
> +            $0.top.equalTo(cardView.snp.bottom).offset(30)
p1;

리뷰카드랑 saveButton 간격 20입니다!

2022-10-25 01:13 UTC, Chaeho-Min commented on Projects/DesignSystem/Sources/Component/PaddingLabel.swift
> +    private var padding = UIEdgeInsets(top: 6.0, left: 10.0, bottom: 6.0, right: 10.0)
p2;

ReviewCardView에서 categoryLabel의 높이를 20으로 지정해주기 때문에 상하 패딩은 의미가 없을 것 같습니다.
그리고 Xcode로 좀 만져봤는데 좌우 패딩값은 8이 제일 나은거 같네요 변경해주시면 감사하겠습니다🙇‍♂️

```suggestion
    private var padding = UIEdgeInsets(top: 0, left: 8.0, bottom: 0, right: 8.0)
```

2022-10-25 03:13 UTC, Lia316 commented on Projects/App/Sources/UI/Review/Views/ReviewCardView.swift
> +        backgroundView.layer.opacity = 0.6
저건,, 제가 피그마 보는 방법을 몰라서 임의로 설정했습니다,, 고치겠습니다

2022-10-25 03:17 UTC, Lia316 commented on Projects/App/Sources/UI/Review/Views/ReviewCardView.swift
> +            $0.width.greaterThanOrEqualTo(33)
저렇게 지정해주지 않으면 
나중에 간격 모자랄 때 언제든지 라벨이 짜부될 수 있어서 설정해줬습니다.

피그마에서 가져오긴 했습니다,, 근데 피그마를 못 믿으면 어떤 걸 보고 설정해야하나요😭❓

2022-10-25 03:31 UTC, Lia316 commented on Projects/DesignSystem/Sources/Component/PaddingLabel.swift
> +    private var padding = UIEdgeInsets(top: 6.0, left: 10.0, bottom: 6.0, right: 10.0)
[2a6a088](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/49/commits/2a6a0886a08a21d596fdeec1c5e4999b47979211) 반영 완료!

2022-10-25 03:31 UTC, Lia316 commented on Projects/App/Sources/UI/Review/ReviewCardViewController.swift
> +            $0.top.equalTo(cardView.snp.bottom).offset(30)
[2a6a088](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/49/commits/2a6a0886a08a21d596fdeec1c5e4999b47979211) 반영 완료!

2022-10-25 03:31 UTC, Lia316 commented on Projects/App/Sources/UI/Review/Views/ReviewCardView.swift
> +        placeNameLabel.numberOfLines = 2
[2a6a088](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/49/commits/2a6a0886a08a21d596fdeec1c5e4999b47979211) 반영 완료!

2022-10-25 03:31 UTC, Lia316 commented on Projects/App/Sources/UI/Review/Views/ReviewCardView.swift
> +        ])
[2a6a088](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/49/commits/2a6a0886a08a21d596fdeec1c5e4999b47979211) 반영 완료!

2022-10-25 03:31 UTC, Lia316 commented on Projects/App/Sources/UI/Review/Views/ReviewCardView.swift
> +        backgroundView.layer.opacity = 0.6
[2a6a088](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/49/commits/2a6a0886a08a21d596fdeec1c5e4999b47979211) 반영 완료!

2022-10-25 08:13 UTC, Chaeho-Min commented on Projects/App/Sources/UI/Review/Views/ReviewCardView.swift
> +            $0.width.greaterThanOrEqualTo(33)
간격이 모자랄 때 라벨이 짜부될 수 있는게 어떤 얘기일까요?
저는 UILabel 같은 경우는 intrinsic content size를 갖기 때문에 오토레이아웃에 너비와 높이를 설정해주지 않아도 이미 정해져있는것과 마찬가지라서 문제가 생기지 않고, 오히려 높이와 너비를 따로 지정해주게 되면 실제 텍스트 크기와 설정된 프레임의 크기가 맞지 않아 발생하는 문제가 더 많다고 생각합니다. (나중에 폰트 크기나 내용을 변경할 때마다 오토레이아웃을 다시 잡아줘야 하고, 우리 앱과는 상관 없지만 Dynamic Type으로 글자 크기가 변하면 프레임을 벗어나게 돼서 텍스트가 잘리거나, 등등...)
'greaterThanOrEqualTo를 사용하면 되지 않나!'라고 생각할 수도 있는데 greaterThanOrEqualTo에서 지정된 값을 넘어가게 되면 결국 intrinsic content size를 사용하게 되는거니까 애초에 설정할 필요가 없다고 생각합니다.

UILabel의 높이와 너비를 꼭 지정해줘야 되는지에 대한 글을 찾고 싶었는데 찾질 못해서 명확한 근거는 대지 못하겠네요😅 그런데 한 번도 지정해주는걸 본적이 없어서 이에 대한 의견이 궁금합니다!

2022-10-25 08:23 UTC, Lia316 commented on Projects/App/Sources/UI/Review/Views/ReviewCardView.swift
> +            $0.width.greaterThanOrEqualTo(33)
생각해보니까 제가 생각했던 짜부되는 모습은 글자가 아니라 라벨의 여백이었던 것 같긴 하네요,,
글자가 잘리지 않는 것이 더 중요하니 수정하도록 하겠습니다

2022-10-25 08:30 UTC, Lia316 commented on Projects/App/Sources/UI/Review/Views/ReviewCardView.swift
> +            $0.width.greaterThanOrEqualTo(33)
e2b3e27159d090e6fe4d5bed37ee1898c0e27c58 반영했습니다! ✨

2022-10-25 08:35 UTC, Chaeho-Min approved these changes
리뷰 반영 감사드립니다 출격 가시죠! 🚀🚀

2022-10-25 08:38 UTC, merged