[Design] placeListCell UI
DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY pull request #55
Opened 2022-10-25 17:08 UTC by tea-hkim

## 작업내용

- [x] 맛집/ 선정 맛집 리스트에서 사용할 PlaceListCell 추가
- [x] 그라데이션 뷰 추가
- [x] 이모지 스텍 뷰 추가
- [x] PlaceCellVeiwModel 추가

|리뷰 사진이 없는 경(경계 유)우|리뷰 사진이 있는 경우(경계 무)| |
|:---:|:---:|:---:|
|<img width="250" src="https://user-images.githubusercontent.com/81206228/197836787-e363a5a3-48a2-46fb-b7d8-0664d5e5b7cc.png">|<img width="250" src="https://user-images.githubusercontent.com/81206228/197836897-256769d4-018c-4022-8384-49c3fca80bf3.png">|
|iPhone 13| iPhone 13 pro max| iPhone se3 |
|<img width="250" src="https://user-images.githubusercontent.com/81206228/197836620-607d036f-574e-4268-a47f-47ea216fae98.png">|<img width="250" src="https://user-images.githubusercontent.com/81206228/197836656-f1ec480d-6c23-4214-9c52-e1e9a5ae709a.png">|<img width="250" src="https://user-images.githubusercontent.com/81206228/197836704-d41c08bc-f720-4716-be96-b87d24194ca2.png">|

## 리뷰포인트

### PlaceCell
1. 그라데이션
   <img width="250" src="https://user-images.githubusercontent.com/81206228/197837316-bef185f8-ff6b-48f8-8acb-a044f8534485.png">
   - 그라데이션이 애매하게 들어가는 것 같습니다... 어떻게 해야 피그마처럼 예쁘게 들어갈까요
   - 어떻게 구현되어있는지 보려면 `UI/Place/View/Views/GradientVeiw`로 가시면 됩니다
2. 이모지 StackVeiw의 사잇값
   - 디자인대로 spacing 값을 준 결과 디자인과 다르게 나왔습니다. 
   - 이모지 이미지 내부에 패딩이 들어가 있어서 spacing 값에서 3씩 줄여줬습니다.
  
## Reference

## Checklist
- [x] 브랜치를 가져와 작업한 경우 이전 브랜치에 PR을 보냈는지 확인
- [x] 빌드를 위해 SceneDelegate 수정한 것 PR로 올리지 않았는지 확인
- [x] 필요없는 주석, 프린트문 제거했는지 확인
- [x] 컨벤션 지켰는지 확인
- [x] final, private 제대로 넣었는지 확인
- [x] 다양한 디바이스에 레이아웃이 대응되는지 확인
  - [x] iPhone SE
  - [x] iPhone 13
  - [x] iPhone 13 Pro Max

2022-10-26 07:16 UTC, Lia316 requested changes
수고하셨어요 닉!!

✅ 뷰모델은 지금 상태에선 없어도 될 것 같고
✅ 컴포넌트로 뺀 뷰는 생성 시에 꼭 텍스트를 초기화하도록 강제하지 않는 게 좋을 것 같아요!

2022-10-26 07:16 UTC, Lia316 commented on Projects/App/Sources/UI/Place/PlaceList/View/Cell/PlaceCell.swift
> +    private let viewModel = PlaceCellVeiwModel(placeName: "쌀국수 집을 하려다가 망한\n소바집인데 쌀국수가 잘팔리는 곳", category: Category(id: 2, name: "일식"), goodCount: 17, sosoCount: 2, badCount: 4, menuName: nil, reviewIm
p2;

해당 부분은 뷰모델로 셀에게 모델을 전달하기보다는 
`setup(with: Place)` 처럼 메서드를 통해 초기화해주는 게 
추후에 셀 마다 데이터를 전달하기에 더 용이할 것 같습니다!

2022-10-26 07:16 UTC, Lia316 commented on Projects/App/Sources/UI/Place/PlaceList/View/Cell/PlaceCell.swift
> +    private lazy var badEmojiStackView = EmojiCountStackView(emojiCount: viewModel.badCount, emoji: UIImage(.img_reviewfriends_bad_30)!)
p2;

오 아예 스택뷰를 따로 만드셨군요! 중복 코드도 제거되고 좋은 것 같습니다 👍🏻
다만, 서버에서 정보를 패치함에 따라 평가 개수가 달라질 수 있기 때문에
초기에 세팅하기보다는 접근제어를 풀어서
EmojiCountStackView의 countLabel에 직접 수정할 수 있게 해주는 것이 더 좋을 것 같아요!

2022-10-26 07:16 UTC, Lia316 commented on Projects/App/Sources/UI/Place/PlaceList/View/Cell/PlaceCell.swift
> +
p3;

identifier은 직접 관리할 수도 있지만 

```swift

// ReuseIdentifierable.swift
protocol ReuseIdentifierable: AnyObject {
}

extension ReuseIdentifierable {
    static var reuseIdentifier: String {
            return String(describing: self)
        }
}

// IssueCell.swift

final class IssueCell: UITableViewCell, ReuseIdentifierable {    
}
```

과 같이 자동으로 관리해줘도 좋을 것 같아요!

2022-10-26 07:16 UTC, Lia316 commented on Projects/App/Sources/UI/Place/PlaceList/View/Cell/PlaceCell.swift
> +    }
p5;

이 부분은 스토리보드에서 해당 셀을 사용할 때 사용할 init인데,
나중에 스토리보드에서 해당 셀을 사용하게 된다면  
위의 init처럼 createLayout()이나 configureUI()가 존재하지 않으니까 아무것도 그려지지 않게 돼요.
 
그럴 바에는 다른 개발자가 알 수 있겠금 오히려 fatal error을 띄워주는 게 더 좋을 수도 있을 것 같아요!

저도 닉처럼 작성한 코드가 남아있기는 한데, 앞으로는 바꿔서 쓰려고요.

2022-10-26 07:16 UTC, Lia316 commented on Projects/App/Sources/UI/Place/PlaceList/View/Cell/PlaceCell.swift
> +        }
P3;

height를 추론하지 않아도 될 것 같아요. bottom만 고정해도 될 듯요?

<img width="100" alt="image" src="https://user-images.githubusercontent.com/73650994/197958391-fa1e0025-0a1f-44f6-8400-506dabcec264.png">

2022-10-26 07:16 UTC, Lia316 commented on Projects/App/Sources/UI/Place/PlaceList/View/Views/EmojiCountStackView.swift
> +        super.init(frame: .zero)
p2;

위에서 언급한 것과 같이, 서버의 데이터를 넣어주려면 생성할 때 값을 넣어주지 않아도 되도록 설계하는 게 더 좋을 것 같아요!

2022-10-26 07:16 UTC, Lia316 commented on Projects/App/Sources/UI/Place/PlaceList/View/Views/GradientView.swift
> +    private let gradient: CAGradientLayer = CAGradientLayer()
p3;

줄바꿈 부탁드려요!

2022-10-26 07:16 UTC, Lia316 commented on Projects/App/Sources/UI/Place/PlaceList/View/Views/GradientView.swift
> +}
p3;

줄바꿈 부탁드려요!

2022-10-26 07:16 UTC, Lia316 commented on Projects/App/Sources/UI/Place/PlaceList/ViewModel/PlaceCellVeiwModel.swift
> +final class PlaceCellVeiwModel {
p3;

줄바꿈 부탁드려요!

2022-10-26 07:16 UTC, Lia316 commented on Projects/App/Sources/UI/Place/PlaceList/View/SubPlaceListViewControllerViewController.swift
> +    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
p3;

줄바꿈 부탁드려요!

2022-10-26 07:16 UTC, Lia316 commented on Projects/App/Sources/UI/Place/PlaceList/View/SubPlaceListViewControllerViewController.swift
> +    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
p3;

줄바꿈 부탁드려요! 22

2022-10-26 07:16 UTC, Lia316 commented on Projects/App/Sources/UI/Place/PlaceList/View/SubPlaceListViewControllerViewController.swift
> +}
p2;

요기에는 디버그 모드로 작성되어 있지 않네요? 
의도된걸까요? 👀

2022-10-26 09:22 UTC, Chaeho-Min requested changes
아픈 와중에 코딩 정말 고생하셨습니다... 건강 잘 챙기세요 닉ㅠㅜ
제가 테이블뷰를 잘 몰라서 제약조건 잘 넣었는지를 꼼꼼히 확인을 못하겠네요 일단 몇 가지 코멘트 남겨놨으니 확인해주세요!

2022-10-26 09:22 UTC, Chaeho-Min commented on Projects/App/Sources/UI/Place/PlaceList/View/Cell/PlaceCell.swift
> +        reviewImageView.contentMode = .scaleAspectFit
p1;

<img width="268" alt="image" src="https://user-images.githubusercontent.com/75792767/197982920-09c3b202-172f-44e4-8373-74666b304f6b.png"><img width="265" alt="image" src="https://user-images.githubusercontent.com/75792767/197983130-03a5e1fc-6551-4f3b-b99c-4ac1a8fada74.png">


.scaleAspectFit은 사진이 잘리질 않으니 사진이 잘려서라도 꽉 채울 수 있도록 .scaleAspectFill을 써주세요!

2022-10-26 09:22 UTC, Chaeho-Min commented on Projects/App/Sources/UI/Place/PlaceList/View/Cell/PlaceCell.swift
> +        placeNameLabel.textColor = .zestyColor(.whiteEBEBF5)
p1;

<img width="657" alt="image" src="https://user-images.githubusercontent.com/75792767/197983367-4826c55d-0d5a-4b34-b9ae-e4342b906672.png">

식당 이름 흰색입니다!

2022-10-26 09:22 UTC, Chaeho-Min commented on Projects/App/Sources/UI/Place/PlaceList/View/Cell/PlaceCell.swift
> +            make.bottom.equalToSuperview().inset(20)
여기 top과 bottom inset은 무슨 값인가요?

2022-10-26 09:22 UTC, Chaeho-Min commented on Projects/App/Sources/UI/Place/PlaceList/View/Cell/PlaceCell.swift
> +        }
p1;

<img width="411" alt="image" src="https://user-images.githubusercontent.com/75792767/197983983-8439e838-680c-43d2-8c96-2f198ee752cc.png">

그라디언트와 menuLabel이 있는 middelView는 사진과 겹쳐있어야 합니다.
지금 상태로는 사진과 겹쳐있지 않아서 수정 부탁드립니다!

2022-10-26 09:22 UTC, Chaeho-Min commented on Projects/App/Sources/UI/Place/PlaceList/View/Views/EmojiCountStackView.swift
> +        spacing = 2
p4;

이게 간격이 디자인 시안대로 했을 때 이상한 이유가 지금 피그마에서 svg로 export 했을 때 아이콘 크기가 작아지는 이슈가 있어서 그런겁니다.
에셋을 아마 png로 바꾸거나 svg를 손봐서 크기를 다시 맞출 것 같은데, 그때 되면 이 값대로라면 간격이 너무 좁아보일 수 있어서
1. 에셋 바꿀 때 같이 바꾸기
2. 에셋 어차피 바뀔테니까 지금 바꿔놓기
둘 중에 하나를 선택하시면 될 것 같아요~

2022-10-26 09:22 UTC, Chaeho-Min commented on Projects/App/Sources/UI/Place/PlaceList/View/Views/EmojiCountStackView.swift
> +class EmojiCountStackView: UIStackView {
p4;

상세페이지에도 쓰이는 컴포넌트라 에이버리가 만들어놨을 수도 있습니다.
나중에 하나로 통일할 필요가 있어보입니다!

2022-10-26 09:22 UTC, Chaeho-Min commented on Projects/App/Sources/UI/Place/PlaceList/View/Cell/PlaceCell.swift
> +        }
p1;

<img width="409" alt="image" src="https://user-images.githubusercontent.com/75792767/197987700-e0c2c457-fbbd-4054-8c96-b04602faf195.png">

리뷰 없을 땐 middelView도 사라집니다!

2022-10-26 09:22 UTC, Chaeho-Min commented on Projects/App/Sources/UI/Place/PlaceList/View/Cell/PlaceCell.swift
> +        mainStackView.layer.masksToBounds = true
p1;

<img width="409" alt="image" src="https://user-images.githubusercontent.com/75792767/197988246-abad5ffa-338e-44cb-a35b-37a1e8b1317c.png">

셀에 그림자가 적용되어 있어서 mainStackView나 contentView에 버리가 만들어놓은 applyFigmaShadow 메서드 적용해주시면 될겁니다!
그런데 지금 파일에 없어서 아마 풀 받아야 할듯요.

2022-10-26 09:51 UTC, tea-hkim commented on Projects/App/Sources/UI/Place/PlaceList/View/Cell/PlaceCell.swift
> +
Q.
제가 예시 코드만으로는 이해가 안가서 그런데 어떻게 자동으로 관리가 되는건가요??? 
궁금합니다!

2022-10-26 09:56 UTC, tea-hkim commented on Projects/App/Sources/UI/Place/PlaceList/View/Cell/PlaceCell.swift
> +    private lazy var badEmojiStackView = EmojiCountStackView(emojiCount: viewModel.badCount, emoji: UIImage(.img_reviewfriends_bad_30)!)
변경했습니다!  59e8db

2022-10-26 09:57 UTC, tea-hkim commented on Projects/App/Sources/UI/Place/PlaceList/View/Cell/PlaceCell.swift
> +    }
변경했습니다!! 그 부분까지는 생각 못했는데 알려주셔서 감사합니다 :)
57b42d8465949a9472feca1a1f77ca4c7f83c530

2022-10-26 09:57 UTC, tea-hkim commented on Projects/App/Sources/UI/Place/PlaceList/View/Cell/PlaceCell.swift
> +        }
변경했습니다 ! 4f2b057d2ce0e7355bb0785b5ec327fa3f37b47f

2022-10-26 09:57 UTC, tea-hkim commented on Projects/App/Sources/UI/Place/PlaceList/View/Views/EmojiCountStackView.swift
> +        super.init(frame: .zero)
변경했습니다 ! 351faa82f659f64acce56c9f4319019b812c1ba5

2022-10-26 09:58 UTC, tea-hkim commented on Projects/App/Sources/UI/Place/PlaceList/View/SubPlaceListViewControllerViewController.swift
> +    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
변경했습니다 !! 7b6f969db5c9eaffe699b27a473ee312b2267988

2022-10-26 09:58 UTC, tea-hkim commented on Projects/App/Sources/UI/Place/PlaceList/View/SubPlaceListViewControllerViewController.swift
> +}
변경했습니다 !! 7b6f969db5c9eaffe699b27a473ee312b2267988

2022-10-26 09:58 UTC, tea-hkim commented on Projects/App/Sources/UI/Place/PlaceList/View/SubPlaceListViewControllerViewController.swift
> +    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
변경했습니다 !! 7b6f969db5c9eaffe699b27a473ee312b2267988

2022-10-26 09:58 UTC, tea-hkim commented on Projects/App/Sources/UI/Place/PlaceList/ViewModel/PlaceCellVeiwModel.swift
> +final class PlaceCellVeiwModel {
변경했습니다! fb1b64307a157d206c21ab1960caed0426cf8e4c

2022-10-26 09:58 UTC, tea-hkim commented on Projects/App/Sources/UI/Place/PlaceList/View/Views/GradientView.swift
> +}
변경했습니다! fb1b64307a157d206c21ab1960caed0426cf8e4c

2022-10-26 09:58 UTC, tea-hkim commented on Projects/App/Sources/UI/Place/PlaceList/View/Views/GradientView.swift
> +    private let gradient: CAGradientLayer = CAGradientLayer()
변경했습니다! fb1b64307a157d206c21ab1960caed0426cf8e4c

2022-10-26 10:05 UTC, tea-hkim commented on Projects/App/Sources/UI/Place/PlaceList/View/Cell/PlaceCell.swift
> +    private let viewModel = PlaceCellVeiwModel(placeName: "쌀국수 집을 하려다가 망한\n소바집인데 쌀국수가 잘팔리는 곳", category: Category(id: 2, name: "일식"), goodCount: 17, sosoCount: 2, badCount: 4, menuName: nil, reviewIm
아하 Place와 화면에서 전달되어지는 데이터의 형태가 차이가 있어보이는 데도 그렇게 하는 편이 좋은 걸까요?
Cell에서는 데이터의 변화가 많지 않기 때문인 것인지 궁금합니다 :)

2022-10-26 10:06 UTC, Lia316 commented on Projects/App/Sources/UI/Place/PlaceList/View/Cell/PlaceCell.swift
> +
프로토콜의 extension으로 reuseIdentifier 프로퍼티를 작성했으므로 
해당 프로토콜을 채택하기만 해도 reuseIdentifier 프로퍼티를 채택한 객체가 소유하게 됩니다.

String(describing: self)를 통해 자기 자신과 동일한 이름의 String 값을 계산합니다.

**결론**
요 파일 추가하고,
```swift
// ReuseIdentifierable.swift
protocol ReuseIdentifierable: AnyObject {
}

extension ReuseIdentifierable {
    static var reuseIdentifier: String {
            return String(describing: self)
        }
}
```

셀 파일에다
```swift

class PlaceCell: UITableViewCell, ReuseIdentifierable {
... // 작성하시던 코드
}
```
만 해주고 다른 코드 추가 안해도

```swift
cell.reuseIdentifier // "PlaceCell"
```
이 가능합니다!

2022-10-26 10:10 UTC, Lia316 commented on Projects/App/Sources/UI/Place/PlaceList/View/Cell/PlaceCell.swift
> +            make.height.equalTo(screenWidth - horizontalPadding * 2)
p4;

뭔가 107번째 줄
높이 = 너비를 의도하신 것 같은데 그런 의도라면 요렇게 작성하는 것을 추천드립니다!


```suggestion
            make.height.equalTo(reviewImageView.snp.width)
        }
```

2022-10-26 11:36 UTC, tea-hkim commented on Projects/App/Sources/UI/Place/PlaceList/View/Cell/PlaceCell.swift
> +            make.bottom.equalToSuperview().inset(20)
위 아래 여백을 계산한 값입니다! 위의 세그먼트 컨트롤과는 10이 차이나고 아래와는 30이 차이나서 모든 cell에 위는 10 아래는 20을 줬습니다!

2022-10-26 11:40 UTC, tea-hkim commented on Projects/App/Sources/UI/Place/PlaceList/View/Cell/PlaceCell.swift
> +            make.height.equalTo(screenWidth - horizontalPadding * 2)
이런 방법이 있었네요!
변경했습니다! da34967acb00d3f040eaebb1bb3c5f726c4f6efc

2022-10-26 11:58 UTC, Chaeho-Min commented on Projects/App/Sources/UI/Place/PlaceList/View/Cell/PlaceCell.swift
> +            make.bottom.equalToSuperview().inset(20)
이 값은 나중에 테이블뷰 적용한 메인화면 나왔을때 다시 한 번 봐야겠네요 지금은 실제로 어떻게 나오는질 모르겠네요!

2022-10-26 12:03 UTC, tea-hkim commented on Projects/App/Sources/UI/Place/PlaceList/View/Cell/PlaceCell.swift
> +        reviewImageView.contentMode = .scaleAspectFit
변경했습니다! 7735f824ac03ddf43d649c21fdd9c29f0de3f561

2022-10-26 12:03 UTC, tea-hkim commented on Projects/App/Sources/UI/Place/PlaceList/View/Cell/PlaceCell.swift
> +        }
변경했습니다! 5c4c0e77384f2d52d360a3086b0d40402c0ea1de

2022-10-26 12:22 UTC, tea-hkim commented on Projects/App/Sources/UI/Place/PlaceList/View/Cell/PlaceCell.swift
> +        placeNameLabel.textColor = .zestyColor(.whiteEBEBF5)
반영했습니다! b4f64371fad80f846515cf9782a2ab7e4eb2e3ac

2022-10-26 12:23 UTC, tea-hkim commented on Projects/App/Sources/UI/Place/PlaceList/View/Views/EmojiCountStackView.swift
> +        spacing = 2
아하 이게 그 문제였군요...
변경했습니다! f8ee36bed2f094ec83e3c09d47016cf152025b12

2022-10-26 13:07 UTC, tea-hkim commented on Projects/App/Sources/UI/Place/PlaceList/View/Cell/PlaceCell.swift
> +        }
반영했습니다! 03d9b66e19ae10d60ed2bea70eedc8b9ba0e41ea
리뷰가 없을 경우 메뉴이름에 빈 배열이 들어가게되고, 빈배열이라면 그라디언트 뷰를 사라지도록 하였습니다

2022-10-26 13:53 UTC, Lia316 commented on Projects/App/Sources/UI/Place/PlaceList/View/Cell/PlaceCell.swift
> +    private let viewModel = PlaceCellVeiwModel(placeName: "쌀국수 집을 하려다가 망한\n소바집인데 쌀국수가 잘팔리는 곳", category: Category(id: 2, name: "일식"), goodCount: 17, sosoCount: 2, badCount: 4, menuName: nil, reviewIm
일단 제가 생각했을 때 
컬렉션 뷰나 테이블 뷰에서 배열 형태로 받은 데이터를 indexPath에 따라 셀에게 데이터를 전달하고,
셀은 그 데이터로 뷰를 그려야한다고 생각해요.

즉, 생각하신 데이터의 형태의 차이는 
셀보다 상위인 컬렉션 뷰나 뷰컨트롤러 단계에서 뷰모델이 매핑을 해줘서 해결할 수 있고,
이게 나중에 서버 연결하고 usecase 및 viewmodel 작성할 때 더 좋지 않을까 싶어서 말씀드렸습니다!

2022-10-26 14:14 UTC, Lia316 commented on Projects/App/Sources/UI/Place/PlaceList/View/Cell/PlaceCell.swift
> +    private let viewModel = PlaceCellVeiwModel(placeName: "쌀국수 집을 하려다가 망한\n소바집인데 쌀국수가 잘팔리는 곳", category: Category(id: 2, name: "일식"), goodCount: 17, sosoCount: 2, badCount: 4, menuName: nil, reviewIm
@tea-hkim 나중에 제가 연결 작업할 때 필요해서 수정할 수도 있을 것 같아요..! 😂

2022-10-26 14:14 UTC, Lia316 approved these changes

2022-10-26 15:00 UTC, tea-hkim commented on Projects/App/Sources/UI/Place/PlaceList/View/Cell/PlaceCell.swift
> +    private let viewModel = PlaceCellVeiwModel(placeName: "쌀국수 집을 하려다가 망한\n소바집인데 쌀국수가 잘팔리는 곳", category: Category(id: 2, name: "일식"), goodCount: 17, sosoCount: 2, badCount: 4, menuName: nil, reviewIm
아하 resolve 되어 있어서 지금 봤습니다 ㅠ 변경하고 있었는데 리아가 연결하시는 거 보고 어떤 형태로 해야 하는지 확인하겠습니다!

2022-10-26 16:52 UTC, tea-hkim commented on Projects/App/Sources/UI/Place/PlaceList/View/Cell/PlaceCell.swift
> +        mainStackView.layer.masksToBounds = true
89b9b65a76ab72e51998ba829a2afa17e4363289 변경하였습니다!

2022-10-27 00:34 UTC, Chaeho-Min approved these changes
🚀🚀

2022-10-27 00:36 UTC, merged