[Design] 대학교 이메일 입력 뷰 UI
DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY pull request #83
Opened 2022-11-01 10:39 UTC by tea-hkim

## 작업내용

- [x] 대학교 이메일 입력 뷰 추가
- [x] 키보드의 높이에 따라 입력 뷰의 레이아웃이 변경되도록 수정
- [x] arrowButton을 컴포넌트로 변경

|이메일 입력 전|이메일 입력 후|
|:---:|:---:|
|<img width="250" src="https://user-images.githubusercontent.com/81206228/199213664-6185ef12-7cb3-4f45-8b89-a2da5b102873.png">|<img width="250" src="https://user-images.githubusercontent.com/81206228/199213733-0d76b6a3-f61b-4f6e-9308-a34d164d57e8.png">|
|iPhone se 3|iPhone13 pro max|
|<img width="250" src="https://user-images.githubusercontent.com/81206228/199213773-c6a3ab40-b8fa-4f20-964e-8ab124f19cad.png">|<img width="250" src="https://user-images.githubusercontent.com/81206228/199213801-a734b065-60c0-48dd-a378-aca7952fbea8.png">|

## 리뷰포인트

### 8027977 레이아웃 에러

```Swift
(
    "<SnapKit.LayoutConstraint:0x6000003a32a0@DomainSettingViewController.swift#165 UIView:0x138f32d70.bottom == UIView:0x138f06c00.bottom>",
    "<SnapKit.LayoutConstraint:0x6000003a9c80@DomainSettingViewController.swift#173 UIView:0x138f32d70.bottom == UIView:0x138f06c00.bottom - 260.0>"
)
```
위와 같은 에러가 발생하는 현상이 있습니다. 이는 keyboard의 높이를 감지하는 뷰의 레이아웃이 2번 입력되어 발생하는 에러입니다.
이를 불가피하게 사용한 이유는 
```
    private func remakeConstraintsByKeyboard(keyboardHeight: CGFloat? = nil) {
        guard let keyboardHeight = keyboardHeight else {
            keyboardSafeArea.snp.makeConstraints { make in
                make.top.equalTo(mainTitleView.snp.bottom)
                make.horizontalEdges.equalToSuperview()
                make.bottom.equalToSuperview()
            }
            return
        }
        
        keyboardSafeArea.snp.makeConstraints { make in
            make.top.equalTo(mainTitleView.snp.bottom)
            make.horizontalEdges.equalToSuperview()
            make.bottom.equalToSuperview().inset(keyboardHeight)
        }
    }
```
guard let 구분 안에 기본 레이아웃을 적용하지 않을 경우 layout이 없는 keyboardSafeArea는 최상단에 아무렇게나 띄워지게 됩니다.
push로 뷰에 진입 시, keyboardSafeArea 안에 있는 컴포넌트들이 위에서 날아오는 애니메이션이 발생합니다.

따라서 레이아웃 경고가 뜨는 대신 기본 레이아웃을 설정하여 뷰에 진입 시 이메일을 입력하는 부분이 아래에서 키보드가 생김에 따라 위로 올라오게 되는 자연스러운 애니메이션을 가지게 하였습니다.

## Reference

## Checklist
- [x] 브랜치를 가져와 작업한 경우 이전 브랜치에 PR을 보냈는지 확인
- [x] 빌드를 위해 SceneDelegate 수정한 것 PR로 올리지 않았는지 확인
- [x] 필요없는 주석, 프린트문 제거했는지 확인
- [x] 컨벤션 지켰는지 확인
- [x] final, private 제대로 넣었는지 확인
- [x] 다양한 디바이스에 레이아웃이 대응되는지 확인
  - [x] iPhone SE
  - [x] iPhone 13
  - [x] iPhone 13 Pro Max

2022-11-02 02:31 UTC, Chaeho-Min requested changes
10초컷 수정사항 3개 남겨놓습니다~~😛

2022-11-02 02:31 UTC, Chaeho-Min commented on Projects/App/Sources/UI/Organization/DomainSetting/View/DomainSettingViewController.swift
> +        emailTextField.keyboardType = .asciiCapable
p2;

이메일에 `.`을 넣는 사람도 있으니까 `.`입력이 편한 .emailAddress가 더 좋을 것 같아요!

2022-11-02 02:31 UTC, Chaeho-Min commented on Projects/App/Sources/UI/Organization/DomainSetting/View/DomainSettingViewController.swift
> +        emailTextField.keyboardType = .asciiCapable
p1;

지금 키보드가 떴을 때 자동대문자가 되는데 자동대문자 없애주세요~
```swift
emailTextField.autocapitalizationType = .none
```

2022-11-02 02:31 UTC, Chaeho-Min commented on Projects/App/Sources/UI/Organization/DomainSetting/View/DomainSettingViewController.swift
> +        arrowButton.setImage(arrowImage, for: .normal)
p2;

arrowButton 컴포넌트에 이미 해당 코드가 있습니다!
아마 컴포넌트 사용하기 이전에 작성한 코드같은데 이제 arrowButton을 컴포넌트로 교체했으니 지워도 될 것 같네요~

2022-11-02 07:47 UTC, Gobans requested changes
고생하셨습니다 닉
레이아웃이 꺠지고 애니메이션이 이상한 이유는 아마 keyboardSafeArea라는 뷰를 만들고 여기에 각각의 뷰를 추가하고 constarints를 재설정해서 나타는게 아닐까 생각이 드는데요, 현재 화면은 뷰 전체가 위로 올라가는 동작이 필요한게 아니고 두개의 컴포넌트만 위 아래로 위치 이동만 필요하기 떄문에 다르게 구현을 해야할 것 같습니다.
 NickNameInputViewController 에서 키보드 keyboardWillShowNotification과 keyboardWillHideNotification 를 이용하여 Constraints를 재설정 하는 코드가 있는데, 이것을 참고하면 충분히 레이아웃 깨짐없이 해당 동작을 구현할 수 있을듯합니다.

2022-11-02 11:09 UTC, tea-hkim commented on Projects/App/Sources/UI/Organization/DomainSetting/View/DomainSettingViewController.swift
> +        emailTextField.keyboardType = .asciiCapable
그 생각은 못했네요!
변경했습니다! ef69dcfe3bd23560bd36f6dae37ea8aa438782e1

2022-11-02 11:09 UTC, tea-hkim commented on Projects/App/Sources/UI/Organization/DomainSetting/View/DomainSettingViewController.swift
> +        emailTextField.keyboardType = .asciiCapable
아하 이 부분도 생각을 못했습니다...
변경했습니다! 40db77c818bd74857c7b75c06fe48a13383bd902

2022-11-02 11:09 UTC, tea-hkim commented on Projects/App/Sources/UI/Organization/DomainSetting/View/DomainSettingViewController.swift
> +        arrowButton.setImage(arrowImage, for: .normal)
삭제했습니다! a9baa05d042bd6c62d6dc9e48bc2eb3e6b9dd8e4

2022-11-02 11:44 UTC, Chaeho-Min approved these changes
어프룹

2022-11-04 07:02 UTC, Gobans approved these changes
다 해결된 것 같네요! 굿👍🚀

2022-11-04 07:21 UTC, merged