[Feat] 애플 로그인 및 자동 로그인 기능 구현
DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY pull request #85
Opened 2022-11-03 08:38 UTC by Gobans

## 작업내용

- [x] 애플 로그인 및 자동 로그인 기능을 구현하였습니다.

현재 로그인 프로세스는 아래와 같습니다.

![LoginProcess drawio-2](https://user-images.githubusercontent.com/56781342/199675474-de56e642-e771-4f94-8d0c-eac93b3f32bd.png)

- PostThirdPartyLogin 요청을 보내면 곧바로 서버에 회원등록이 되기 떄문에 isAlreadyRegistered 로 회원가입 여부를 체킹하여 저장해놓습니다.  그 후 마지막 분기 처리를 하여 PlaceListView로 이동시킬지, NicknameInputView로 이동시킬지 결정하였습니다. (닉네임을 설정해놓지 않은 경우도 동일)

- 현재 애플 로그인의 프로필 조회가 잘 되지 않는 문제가 있기 떄문에 서버에 요청을 드렸고, 문제가 해결된 후 머지할 생각입니다.

## 리뷰포인트
- 아마 바뀔 부분이 거의 없기 떄문에 마음 놓고 코드리뷰 해주시면 감사하겠습니다.
- 로그인 프로세스 이해를 돕기위해 다이어 그램을 그려봤는데 어떤가요?👀

## Checklist
- [x] 브랜치를 가져와 작업한 경우 이전 브랜치에 PR을 보냈는지 확인
- [x] 빌드를 위해 SceneDelegate 수정한 것 PR로 올리지 않았는지 확인
- [x] 필요없는 주석, 프린트문 제거했는지 확인
- [x] 컨벤션 지켰는지 확인
- [x] final, private 제대로 넣었는지 확인
- [x] 다양한 디바이스에 레이아웃이 대응되는지 확인
  - [x] iPhone SE
  - [x] iPhone 13
  - [x] iPhone 13 Pro Max

2022-11-04 07:59 UTC, tea-hkim approved these changes
드디어 로그인과 회원가입 부분의 끝이..!
수고하셨습니다~

2022-11-04 12:46 UTC, Lia316 requested changes
수고하셨어요 고반!
역시 고반은 어려운 코드도 묵묵히 뚝딱 해내시네요 🙌🏻
특히 도메인 파트에서 input과 output을 깔끔하게 구분해서 짜신 것 보고 많이 배웠습니다!

꼭 수정하셔야 하는 부분은 키체인 밖에 없고 
나머지는 함께 이야기 해보면 좋을 것 같은 부분을 코멘트로 달아놨어요!

수고 많으셨습니다~🥳

2022-11-04 12:46 UTC, Lia316 commented on Projects/App/Sources/Global/Extension/UserDefaults+.swift
> +            guard let authToken = UserDefaults.standard.value(forKey: UserInfoKeys.authToken.rawValue) as? String else {
Q

authToken은 보안 상 신경 쓰지 않아도 되는 수준의 정보인지 좀 헷갈려서 질문 드려요!
저는 authToken 정도면 사용자를 인증하는 수단이 되니까 
키체인 같은 곳에 은밀히 숨겨야하지 않을까 싶은 생각이 드는데
그 정도로 숨기지 않아도 되는지 궁금합니다..!

2022-11-04 12:46 UTC, Lia316 commented on Projects/App/Sources/UI/User/Login/ViewModel/ThirdPartyLoginViewModel.swift
> +                guard let provider = self.provider else { return }
p5;

guard let 구문을 하나로 통합해도 좋을 것 같아요!

2022-11-04 12:46 UTC, Lia316 commented on Projects/App/Sources/Global/Extension/UserDefaults+.swift
> +            guard let userName = UserDefaults.standard.value(forKey: UserInfoKeys.userNickname.rawValue) as? String else {
p3;

현재 유저에 대한 정보들이 UserDefaults에 각각 존재하고 있는데,
이를 하나로 통합해서 관리하면 더 관리하기 좋을 것 같아요

2022-11-04 12:46 UTC, Lia316 commented on Projects/App/Sources/Global/Extension/UserDefaults+.swift
> +            guard let authToken = UserDefaults.standard.value(forKey: UserInfoKeys.authToken.rawValue) as? String else {
p2;

함께 이야기해보고 나니 키체인에 숨겨두는 게 맞을 것 같다는 생각이 들어요
UserDefaults는 비교적 쉽게 접근할 수 있는 정보이기에 
거의 비밀번호 급인 authToken을 두는 건 적절하지 않은 것 같습니다.

2022-11-04 12:46 UTC, Lia316 commented on Projects/App/Sources/UI/User/Login/ViewModel/ThirdPartyLoginViewModel.swift
> +                    self.shouldSetNicknameSubject.send(true)
Q

if와 if else의 조건이 같아 보이는데 의도하신걸까요👀 
그럴리가 없겠죠...???

2022-11-04 12:46 UTC, Lia316 commented on Projects/App/Sources/UI/User/Login/ViewModel/ThirdPartyLoginViewModel.swift
> +                        }
p5;

저도 코드 작성하면서 느끼는 건데,,
뭔가 저희 뷰모델에 로직이 너무 많이 있는 것 같아요

제가 느끼기엔 
```swift
func kakaoLogin()
private func kakaoLoginWithApp()
private func kakaoLoginWithAccount()
func appleLogin(authorization: ASAuthorization)
```
이 친구들 전부 로직에 해당된다고 생각하는데 고반은 어떻게 생각하고 계시는지 궁금해요!

2022-11-04 12:46 UTC, Lia316 commented on Projects/App/App.entitlements
> +</plist>
Q

오 이건 애플 로그인을 위한 파일인가요? 👀

2022-11-05 10:44 UTC, Gobans commented on Projects/App/Sources/Global/Extension/UserDefaults+.swift
> +            guard let authToken = UserDefaults.standard.value(forKey: UserInfoKeys.authToken.rawValue) as? String else {
@Gobans
[Refactor♻️: authToken keyChain에 저장하도록 변경](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/91/commits/1eea105e533a711b9f4bc113856277b092697f68)
요거는 로그인, 로그아웃 기능에도 변경이 필요해서 다른 브랜치에서 작업해서 커밋했습니다!

2022-11-05 10:48 UTC, Lia316 commented on Projects/App/Sources/Global/Extension/UserDefaults+.swift
> +            guard let authToken = UserDefaults.standard.value(forKey: UserInfoKeys.authToken.rawValue) as? String else {
lgtm

2022-11-05 11:19 UTC, Gobans commented on Projects/App/Sources/UI/User/Login/ViewModel/ThirdPartyLoginViewModel.swift
> +                        }
엇 viewModel에서 로직 같고 있는 것 아닌가용?
그리고 useCase로 옮긴다면 너무 번잡해질 것 같은 우려가 있습니다..

2022-11-05 11:19 UTC, Gobans commented on Projects/App/App.entitlements
> +</plist>
네 맞아요..! 저도 처음 알았습니다👀

2022-11-05 11:23 UTC, Gobans commented on Projects/App/Sources/Global/Extension/UserDefaults+.swift
> +            guard let userName = UserDefaults.standard.value(forKey: UserInfoKeys.userNickname.rawValue) as? String else {
요거는 혹시 그냥 클래스 하나 만들어서 그 안에 
```swift
class UserInfo {
    
    private enum UserInfoKeys: String, CaseIterable {
        case authIdentifier
        case userNickname
        case userID
        case userOrganization
    }
    
    var authIdentifier: String? {
        get {
            guard let authIdentifier = UserDefaults.standard.value(forKey: UserInfoKeys.authIdentifier.rawValue) as? String else {
                return nil
            }
            return authIdentifier
        }
        set {
            UserDefaults.standard.set(newValue, forKey: UserInfoKeys.authIdentifier.rawValue)
        }
    }

}

```
이런 식으로 존재하면 좋겠다는 말씀이실까요?

2022-11-05 11:25 UTC, Gobans commented on Projects/App/Sources/UI/User/Login/ViewModel/ThirdPartyLoginViewModel.swift
> +                guard let provider = self.provider else { return }
요것도 혹시 몰라서 최신 작업한 브랜치에서 수정하였습니다!
[d274826](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/91/commits/d274826418cf32c80081f4f8d214f155d5a3d293)

2022-11-05 11:26 UTC, Gobans commented on Projects/App/Sources/UI/User/Login/ViewModel/ThirdPartyLoginViewModel.swift
> +                    self.shouldSetNicknameSubject.send(true)
잘못처리했네요😂 감사합니다
[d274826](https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/91/commits/d274826418cf32c80081f4f8d214f155d5a3d293)

2022-11-05 11:27 UTC, Lia316 commented on Projects/App/Sources/UI/User/Login/ViewModel/ThirdPartyLoginViewModel.swift
> +                guard let provider = self.provider else { return }
엥 고반 다른 커밋을 올려주셨어요!

2022-11-05 11:28 UTC, Gobans commented on Projects/App/Sources/UI/User/Login/ViewModel/ThirdPartyLoginViewModel.swift
> +                guard let provider = self.provider else { return }
수정하였습니다!! 🙏

2022-11-05 11:30 UTC, Lia316 commented on Projects/App/Sources/UI/User/Login/ViewModel/ThirdPartyLoginViewModel.swift
> +                        }
제가 생각하는 뷰모델의 역할은 뷰가 보여줄 데이터를 가공해서 보여주는 정도로만 생각했습니다.
UseCase는 특정 기능을 제공해주기 위해 필요한 로직이라고 생각했습니다.

그래서 지금 저는 오히려 저희의 전반적인 뷰모델이 번잡해진 것 같다는 고민을 하고 있는데,,, 
고반은 뷰모델과 유즈케이스의 역할을 어떻게 생각하고 계시나요?

2022-11-05 11:42 UTC, Lia316 commented on Projects/App/Sources/Global/Extension/UserDefaults+.swift
> +            guard let userName = UserDefaults.standard.value(forKey: UserInfoKeys.userNickname.rawValue) as? String else {
음 제가 생각했던 방식은 아예 객체 전체를 통째로 저장하고 불러오는 거였어요!
https://www.hackingwithswift.com/example-code/system/how-to-load-and-save-a-struct-in-userdefaults-using-codable
이런 느낌으로요

```swift
struct UserInfo: Codable {
   authIdentifier: String?
   userNickname: String?
   userID: String?
   userOrganization: String?
}

extension UserDefaults {
   func save(with userInfo: UserInfo) {
      if let encoded = try? JSONEncoder().encode(taylor) {
          UserDefaults.standard.set(encoded, forKey: "SavedPerson")
       }
   }
}
```

일단 대충 이런 느낌이라 돌아가는지는 확인해보지 않았습니다.
근데 이러면 아예 키체인 처럼 매니저를 만드는 것도 좋을 것 같긴 하네요. 요건 선택!

2022-11-05 11:43 UTC, Gobans commented on Projects/App/Sources/UI/User/Login/ViewModel/ThirdPartyLoginViewModel.swift
> +                        }
저는 useCase가 데이터를 보내고 가져오는 역할을 주요로 하고 모델 매핑, 데이터 저장의 기능을 한다고 생각했어요 (데이터 처리 전반)
viewModel은  그 사이에서 로직도 처리도하고 useCase에서 필요한 데이터를 처리하는 역할도 가능하지 않을까 생각했어요.
근데 지금 생각해보니 데이터 처리니까 useCase에서 하는게 맞는 것 같기도하고😂
 이건 제가 리팩토링 사항으로 생각하고 한번 로직들을 useCase로 옮겨보고 따로 PR올릴게요

2022-11-05 11:52 UTC, Lia316 commented on Projects/App/Sources/UI/User/Login/ViewModel/ThirdPartyLoginViewModel.swift
> +                        }
[Clean Architecture - 2. 클린 아키텍쳐의 핵심: Use Case (티스토리 블로그)](https://alphahackerhan.tistory.com/28)
클린 아키텍쳐에서 말하는 유즈케이스는 서비스에서 제공하는 기능 같은 거라고 저는 이해했습니다.
말씀하신 데이터를 내보내고 매핑하는 역할은 레포지토리 및 데이터 매퍼가 해줄 수 있다고 생각했고요! 

아무튼 이 부분은 말씀하신 대로 급한 건 아니고 선택적 리팩토링이라서 함께 아키텍쳐에 대해 이야기해보면서 결정해도 좋을 것 같네요!

2022-11-05 14:07 UTC, Gobans commented on Projects/App/Sources/Global/Extension/UserDefaults+.swift
> +            guard let userName = UserDefaults.standard.value(forKey: UserInfoKeys.userNickname.rawValue) as? String else {
만들어왔습니다! 간편하게 
```swift
// 유저 정보 전체 불러오기
let userInfo = UserInfoManager.userInfo
// 유저 정보 하나만 불러오기
let userID = UserInfoManager.userInfo.userID
// 유저 정보 갱신
UserInfoManager.userInfo.userID = 3
```
이런식으로 사용할 수 있습니다!
0f3bb48906498214b8b049b27b161bc5cba5bc62 449d98ee5ba11b956e37c87f7cb64d5f1f9ab4e7

2022-11-05 15:22 UTC, Lia316 commented on Projects/App/Sources/Global/Extension/UserDefaults+.swift
> +            guard let userName = UserDefaults.standard.value(forKey: UserInfoKeys.userNickname.rawValue) as? String else {
오호! 2가지 장점 모두 호로록 하셨군요! 
리뷰 반영 감사드립니다! 😆

2022-11-05 15:23 UTC, Lia316 approved these changes
리뷰 반영 감사드립니다~!

2022-11-06 07:17 UTC, merged