[Fix] 맛집 리스트 crash 현상 및 레이아웃 깨짐 이슈 해결
DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY pull request #87
Opened 2022-11-03 11:13 UTC by Lia316

## 작업내용

- [x] cell의 개수를 몰라도 되는 Diffable Datasource 방식으로 변경
- [x] 테이블뷰에서 컬렉션뷰로 리팩토링
- [x] 디퍼블 전환에 따른, header view 분리, 헤더 고정
- [x] 맛집 추가 버튼 누를 시, 맛집 추가 뷰로 넘어가게 함
- [x] Xcode command 창을 더럽히던 레이아웃 깨짐 이슈 해결
- [x] 서버 api에 따라, 마지막 index를 기준으로 prefetch 하도록 수정
- [x] 마구잡이 fetch 코드 개선 

|작업 전|작업 후|
|:---:|:---:|
|<img width="250" src="">|<img width="250" src="https://user-images.githubusercontent.com/73650994/199705099-fffb9a0d-bca1-44df-922a-311ff0a1c05a.gif">|

## 리뷰포인트
- @Chaeho-Min 헤더 고정하니까 뭔가 네비게이션 바랑 안 어울리는 것 같고 이상해요...
 한 번 봐주시면 감사하겠습니다 🙏🏻

<img width="536" alt="image" src="https://user-images.githubusercontent.com/73650994/199696240-d6572c2a-d83f-441e-8096-ec83d052d687.png">

- PlaceCell.swift 에서 스크롤뷰를 감싸고 있는 `containerView`에 보라색 전구 아이콘이 뜹니다..
무슨 의미이고, 어떻게 해결할 지 몰라 방치하고 있습니다.
보라색 느낌표는 레이아웃 이슈일 때인데, 아이콘이 다른 걸 보아 일단 그 이슈는 아닌 것 같습니다.

# Reference

## Checklist
- [x] 브랜치를 가져와 작업한 경우 이전 브랜치에 PR을 보냈는지 확인
- [x] 빌드를 위해 SceneDelegate 수정한 것 PR로 올리지 않았는지 확인
- [x] 필요없는 주석, 프린트문 제거했는지 확인
- [x] 컨벤션 지켰는지 확인
- [x] final, private 제대로 넣었는지 확인
- [x] 다양한 디바이스에 레이아웃이 대응되는지 확인
  - [x] iPhone SE
  - [x] iPhone 13
  - [x] iPhone 13 Pro Max

2022-11-03 11:51 UTC, Lia316 commented on Projects/App/Sources/UI/Place/PlaceList/View/Views/ReviewPageView.swift
> +            $0.height.equalTo(58)
여기는 UI view hierarchy에서 해당 constraint가 ambiguous하다고 하여 수정했습니다

2022-11-03 11:51 UTC, Lia316 commented on Projects/App/Sources/Domain/Place/Place.swift
> +    let uuid = UUID()
Diffable Datasource 사용을 위한 Hashable 채택 및 uuid입니다.
각 itemIdentifier은 고유해야해서 문제 발생을 줄이기 위해 이와 같이 세팅했습니다.

2022-11-03 11:51 UTC, Lia316 commented on Projects/App/Sources/UI/Place/PlaceList/View/Cell/PlaceCell.swift
> +            make.top.equalTo(scrollView.snp.bottom).priority(.medium)
원인은 잘 모르겠으나 collectionView의 estimated height을 적용하는 과정에서 constraint 깨짐 이슈가 발생했습니다.
Xcode command 창에서 제안하는 대로, 깨진 constraint의 priority를 낮춰 해결했습니다.
[스택오버플로우 참고](https://stackoverflow.com/questions/25059443/what-is-nslayoutconstraint-uiview-encapsulated-layout-height-and-how-should-i)

2022-11-03 11:57 UTC, Lia316 commented
@tea-hkim 

혹시 이 주석의 의미 알 수 있을까요? 👀
완료된 작업이면 삭제하고자 합니다!

 <img width="634" alt="image" src="https://user-images.githubusercontent.com/73650994/199714239-56faec07-cf77-43e5-87fc-b2e0bf399698.png">

2022-11-03 13:06 UTC, Gobans requested changes
고생하셨습니다 리아!
어려운 뷰를 맡았지만 아주 멋지게 해내시는군요
리아 코드를 보고 많이 배웁니다🙇‍♂️
몇가지 사항만 리뷰로 남겼으니 확인해주시면 감사하겠습니다
1.
<img width="928" alt="image" src="https://user-images.githubusercontent.com/56781342/199727465-801b06d1-1207-450b-9fd2-97ab1cb50374.png">
첫번쨰 cell을 누르면 crash가 나는데, 혹시 원인을 아시나요??👀

2.
<img width="250" alt="image" src="https://user-images.githubusercontent.com/56781342/199727953-8e16d6c8-f428-4ff1-8c75-2c9dd79f8eb6.gif">
@Chaeho-Min 상단 네비게이션 바가 투명이라 상당히 어색한 느낌이 듭니다. 불투명 처리하는게 어떨까요?👀

2022-11-03 13:06 UTC, Gobans commented on Projects/App/Sources/UI/Place/PlaceList/View/Cell/PlaceCell.swift
> +            make.top.equalTo(scrollView.snp.bottom).priority(.medium)
조금 오래 들여다 봤는데 왜그런지 잘 모르겠네요.. 음.. 😱

2022-11-03 13:06 UTC, Gobans commented on Projects/App/Sources/UI/Place/PlaceList/View/Views/SegmentHeaderView.swift
> +            segmentIndicator.snp.makeConstraints { make in
p1
remake 안써서 레이아웃 깨짐 오류가 뜨네용

2022-11-03 13:06 UTC, Gobans commented on Projects/App/Sources/UI/Place/PlaceList/View/PlaceListViewController.swift
> +            supplementaryView.addPlaceDelegate = self
Q
SegmentHeaderView의 viewModel은 initialize 된 이유가 무엇인가요?
addPlaceDelegate와 같이 똑같이 외부에서 주입 받는다면 weak 로 타입 선언만 하는게 좋을 것 같다는 생각이듭니다.

2022-11-03 13:06 UTC, Gobans commented on Projects/DesignSystem/Resources/Assets.xcassets/img_reviewfriends/img_reviewfriends_bad.imageset/Contents.json
> +      "filename" : "Bad.svg",
요거는 asset name 따라서 bad라 파일 이름 변경하는게 좋을 것 같아요

2022-11-03 13:16 UTC, Lia316 commented
> 1. 
> <img alt="image" width="928" src="https://user-images.githubusercontent.com/56781342/199727465-801b06d1-1207-450b-9fd2-97ab1cb50374.png"> 첫번쨰 cell을 누르면 crash가 나는데, 혹시 원인을 아시나요??👀
> 

요거 crash되는 이유는 제가 어제 무지성으로 카카오아이디 넣은 데이터가 실제 카카오아이디랑 안 맞아서 생기는 걸로 보여요,,,
로치님께 해당 데이터 삭제를 요청 드려서 곧 괜찮아질 것으로 보입니다!
⇒ 코드 문제는 아니고 데이터 문제

2022-11-03 13:17 UTC, Lia316 commented on Projects/DesignSystem/Resources/Assets.xcassets/img_reviewfriends/img_reviewfriends_bad.imageset/Contents.json
> +      "filename" : "Bad.svg",
아하 자꾸 집 나간 이유가 이건가 보네요 감사합니다!

2022-11-03 13:21 UTC, Lia316 commented on Projects/App/Sources/UI/Place/PlaceList/View/Views/SegmentHeaderView.swift
> +            segmentIndicator.snp.makeConstraints { make in
오잉 이걸 위에 것만 remake 적용했네요
감사합니다!!

2022-11-03 13:29 UTC, Lia316 commented on Projects/App/Sources/UI/Place/PlaceList/View/Views/SegmentHeaderView.swift
> +            segmentIndicator.snp.makeConstraints { make in
908373d9765c605face40b1ce78ee9558d20b43d

2022-11-03 13:30 UTC, Lia316 commented on Projects/App/Sources/UI/Place/PlaceList/View/PlaceListViewController.swift
> +            supplementaryView.addPlaceDelegate = self
전체 맛집의 데이터를 보여줄 것인지, 선정 맛집의 데이터를 보여줄 건인지를 Segment Control이 결정하기 때문에
뷰모델에게 알려주기 위해 주입하게 되었습니다.
해당 부분은 말씀하신대로 weak로 변경하였습니다! d98c85903f71ca2ebd82749510173cbd8a2fe890
감사합니다!!

2022-11-03 13:33 UTC, Gobans approved these changes
빠른 수정 감사합니다 🚀🚀🚀🚀🚀

2022-11-03 13:34 UTC, Lia316 commented on Projects/DesignSystem/Resources/Assets.xcassets/img_reviewfriends/img_reviewfriends_bad.imageset/Contents.json
> +      "filename" : "Bad.svg",
320fb04932631e2843cc883eacc9573a5991eb65

2022-11-03 13:50 UTC, Chaeho-Min requested changes
콜렉션뷰는 역시 너무 어렵네요... 대단하십니다 저는 뷰 제약조건만 슥 보고 갑니다😅

내비게이션바가 이상한거는 iOS15부터 내비게이션바/탭바가 스크롤이 되면 유리 재질로 뒷배경이 보이는게 디폴트가 돼서 그런데, 이 설정을 없애야 될 것 같습니다.
- https://www.zehye.kr/ios/2021/10/19/iOS_ios15_navigation_bar/
- https://gist.github.com/TuenTuenna/3382ce64d1d0833b5d5127b26d324594

이 페이지들 참고하시면 될 것 같아요~

2022-11-03 13:50 UTC, Chaeho-Min commented on Projects/App/Sources/UI/Place/PlaceList/View/Views/ReviewPageView.swift
> +            $0.height.equalTo(58)
p1;

<img width="585" alt="image" src="https://user-images.githubusercontent.com/75792767/199734234-c4eb9aef-abb2-4165-ba8e-45ef58fbb69d.png">

여기는 menuLabel과 40 띄워지도록 의도해서 제약조건을 menuLabel에 둬도 되는데, 어차피 menuLabel을 한 줄로 제한할거라 고정값을 줘도 상관은 없어보입니다.

```swift
        gradientView.snp.makeConstraints {
            $0.horizontalEdges.equalToSuperview()
            $0.bottom.equalToSuperview()
            $0.top.equalTo(menuLabel.snp.top).offset(40) // 권장사항 얘는 p5
        }
```

대신 menuLabel을 한 줄로 제한하는 코드 추가해주세요!

```swift
        menuLabel.numberOfLines = 1 // 얘가 p1!
```

2022-11-03 13:50 UTC, Chaeho-Min commented on Projects/App/Sources/UI/Place/PlaceList/View/Views/ReviewPageView.swift
>          menuLabel.snp.makeConstraints {
p1;

<img width="557" alt="image" src="https://user-images.githubusercontent.com/75792767/199734325-5afb3bca-affb-4434-ae24-636035b03af2.png">

추가적으로 밑에 코드도 보니까 리뷰 안 된 부분이 있어서 여기다 코멘트 남깁니다.
menuLabel은 pageControl이랑 20의 간격을 두는것을 의도했었는데 지금 뷰 구조 상 둘 사이에 제약조건을 두기 어려워보여서 여기도 고정값 적당히 줘도 될 것 같네요.
menuLabel이 길어져도 pageControl과 안 겹치고 말줄임표 표시가 되도록!

```swift
        menuLabel.snp.makeConstraints {
            $0.left.equalToSuperview().inset(20)
            $0.bottom.equalToSuperview()
            $0.trailing.equalToSuperview().inset(적당히! pageControl과 안 겹치도록!)
        }
```

2022-11-03 13:50 UTC, Chaeho-Min commented on Projects/App/Sources/UI/Place/PlaceList/View/Views/SegmentHeaderView.swift
> +        segmentIndicator.backgroundColor = .black
p1;

여기 저번에 닉 PR에서 빼먹은 부분인데 라운드 추가 부탁드립니다🙇‍♂️

```suggestion
        segmentIndicator.backgroundColor = .black
        segmentIndicator.layer.cornerRadius = 1
        segmentIndicator.layer.masksToBounds = true
```

2022-11-04 02:50 UTC, Lia316 commented on Projects/App/Sources/UI/Place/PlaceList/View/Views/ReviewPageView.swift
>          menuLabel.snp.makeConstraints {
23f8dc663fb16ba4e60df4204c85ab8a63dfe2c9 반영했습니다! 
겹치는 걸 생각 못했었네요 감사합니다

2022-11-04 02:50 UTC, Lia316 commented on Projects/App/Sources/UI/Place/PlaceList/View/Views/SegmentHeaderView.swift
> +        segmentIndicator.backgroundColor = .black
6de1644156365e42a2085a256102ad0df8a01944 추가했습니다 ✨

2022-11-04 03:11 UTC, Chaeho-Min approved these changes
🚀

2022-11-04 03:12 UTC, merged