[Design] 대학교 이메일 인증 뷰 UI
DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY pull request #88
Opened 2022-11-03 12:22 UTC by tea-hkim

## 작업내용

- [x] OTPScreen 추가
- [x] 토스트 애니메이션 추가
- [x] MainTitleView의 subtitle에 SFsymbol 넣는 기능 추가

|iPhone 13| 에러메세지 및 로딩|
|:---:|:---:|
|<img width="250" src="https://user-images.githubusercontent.com/81206228/199717626-107bd194-9762-47a0-89ea-eaeb570b77ca.png">|<img width="250" src="https://user-images.githubusercontent.com/81206228/199717713-bcc47fa9-c583-4a99-8203-d8d883f12856.png">|
|iPhone 13 pro max| iPhone se 3|
|<img width="250" src="https://user-images.githubusercontent.com/81206228/199718029-52a5b191-8d08-4cf3-99be-e31aac5bfa87.png">|<img width="250" src="https://user-images.githubusercontent.com/81206228/199718190-1275b9ba-ea11-4413-a775-0910e2dac9df.png">|

## 리뷰포인트

### autolayout이 깨지는 현상 23da1b5703a30d291064ebeeb655efd852fdb9ea
```
(
    "<SnapKit.LayoutConstraint:0x6000009afc60@VerifingCodeViewController.swift#178 DesignSystem.ArrowButton:0x15770e900.bottom == UIView:0x158c08910.bottom - 20.0>",
    "<SnapKit.LayoutConstraint:0x60000098a1c0@VerifingCodeViewController.swift#193 DesignSystem.ArrowButton:0x15770e900.bottom == UIView:0x158c08910.bottom - 236.0>"
)
```
위와 같이 오토레이아웃이 깨지는 현상이 있습니다. 현재 코드는 고반의 NicknameInputViewController처럼 변경한 상태입니다.
레이아웃이 아예 그려지지 않는 것이 아니라 키보드이 height가 그려지면서 생기는 문제 같은데 조금 더 고민을 해봐야 할 것 같습니다...

## Reference

## Checklist
- [x] 브랜치를 가져와 작업한 경우 이전 브랜치에 PR을 보냈는지 확인
- [x] 빌드를 위해 SceneDelegate 수정한 것 PR로 올리지 않았는지 확인
- [x] 필요없는 주석, 프린트문 제거했는지 확인
- [x] 컨벤션 지켰는지 확인
- [x] final, private 제대로 넣었는지 확인
- [x] 다양한 디바이스에 레이아웃이 대응되는지 확인
  - [x] iPhone SE
  - [x] iPhone 13
  - [x] iPhone 13 Pro Max

2022-11-03 13:48 UTC, Gobans reviewed
고생하셨습니다 닉! 코드 입력창이 아주 예쁘네요
그런데 테스트하려는데 코드를 다 입력해도 arrowButton이 안뜨네요?? 
뜨는 조건이 무엇인가요? 조금 살펴보니 OTPStackView의 delegate 설정이 안되있는 것 같은데
혹시 지금 커밋 최신화가 안된걸까요?
++ 레이아웃 깨짐은 remakeConstraints를 안써서 그런 것 같습니다

2022-11-03 14:28 UTC, Chaeho-Min requested changes
토스트메시지 나쁘지 않네요 MainTitleView 변경까지...!! 수고하셨습니다😄

<img width="250" src="https://user-images.githubusercontent.com/75792767/199744799-097be01b-a0f9-410c-8c30-63d0ac9ec9e6.gif">

그런데 지금 코드를 지웠을 때의 동작이 이상합니다!
코드를 지우고 숫자를 다시 누르면 현재 비어있는 칸이 채워져야 하는데, 지금은 채워진 칸 중 제일 마지막 칸의 숫자가 변경됩니다.

그리고 중간 칸까지만 채운 후 지우기 버튼을 누르면 숫자가 안 지워집니다 (실제로는 값이 지워졌는데 뷰가 업데이트 안되는것 같네요)

2022-11-03 14:28 UTC, Chaeho-Min commented on Projects/App/Sources/UI/Organization/VerifyCode/View/VerifingCodeViewController.swift
> +        toastLabel.text = "메일을  다시 보냈어요"
p1;

'메일을'과 '다시' 사이에 공백이 두 개나 있어요😈

```suggestion
        toastLabel.text = "메일을 다시 보냈어요"
```

2022-11-03 14:28 UTC, Chaeho-Min commented on Projects/App/Sources/UI/Organization/VerifyCode/View/VerifingCodeViewController.swift
> +            make.top.equalTo(view.snp.top).offset(-50)
p4;

이거 그냥 toastLabel의 bottom을 view.snp.top에 맞추면 되지 않나요?
이렇게 하는게 toastLabel의 높이가 변경됐을 때 수정할 곳이 하나가 줄어서 더 낫다고 생각합니다!

```suggestion
            make.bottom.equalTo(view.snp.top)
```

2022-11-03 15:35 UTC, chaneeii approved these changes
닉의 ui는 항상 깔끔해서 좋네요!
이미 아보가 잡아줘서 dependency 겁니다!

LGTM

2022-11-03 15:35 UTC, chaneeii commented on Projects/App/Sources/UI/Organization/VerifyCode/View/VerifingCodeViewController.swift
> +        toastLabel.text = "메일을  다시 보냈어요"
아보 정말 앙마네요

2022-11-04 01:36 UTC, tea-hkim commented on Projects/App/Sources/UI/Organization/VerifyCode/View/VerifingCodeViewController.swift
> +        toastLabel.text = "메일을  다시 보냈어요"
수정했습니다! fc0fc403c24a0bf12811d8733c129b81b2004e36

2022-11-04 01:37 UTC, tea-hkim commented on Projects/App/Sources/UI/Organization/VerifyCode/View/VerifingCodeViewController.swift
> +            make.top.equalTo(view.snp.top).offset(-50)
오 그 생각은 못했네요! 
수정했습니다 ! 68e59759c17a26db1eaaecf055e79a3fc7b178fa

2022-11-04 01:40 UTC, tea-hkim commented on Projects/App/Sources/UI/Organization/VerifyCode/View/VerifingCodeViewController.swift
> +            make.top.equalTo(view.snp.top).offset(-50)
코드를 지울 때 이상한 부분을 해결하였습니다! 
텍스트필드가 비어있는 경우에 대한 예외처리가 안되어있어서 추가하였습니다!
68e59759c17a26db1eaaecf055e79a3fc7b178fa

2022-11-04 06:19 UTC, Chaeho-Min approved these changes
<img width="250" src="https://user-images.githubusercontent.com/75792767/199903737-cba77eef-4d3c-40e4-a84e-99984829fa4d.gif">

아직 코드 지울 때 이상한 부분 해결이 덜 돼서 코드가 꽉 찬 이후로 지웠을 때 이상한데, 나중에 실제 코드 인증이 될 때는 코드가 꽉 차면 자동으로 코드 검증 API가 돌아가고, 정상적인 코드라면 화면이 넘어가고 잘못된 코드면 코드가 모두 지워질테니 상관 없겠죠?😁

2022-11-04 07:00 UTC, merged