[Fix] 리뷰 중복 추가 수정
DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY pull request #95
Opened 2022-11-04 17:43 UTC by Lia316

## 작업내용

- [x] 리뷰 등록 뷰 레이아웃 깨짐 현상 최소화
- [x] 리뷰 이중 post 현상 해결
- [x] 리뷰 저장 시트 띄우기 추가
- [x] 전반적인 UI 및 도메인 코드 리팩토링
- [x] KingFisher string to image → url to image 로 변경

|작업 전|작업 후|
|:---:|:---:|
|<img width="250" src="">|<img width="250" src="https://user-images.githubusercontent.com/73650994/200040587-3b789b70-459d-43b0-b3bd-1db1d8daafc9.gif">|

## 리뷰포인트
- 레이아웃 깨짐 현상은 주로 테이블뷰나 컬렉션뷰 같은 셀에서 발생하는데,
그 이유가 가장 상위 뷰의 레이아웃을 잡는 방법과 내부 레이아웃을 잡는 방법이 달라서 인 것으로 추측 중입니다.
일단 임시로 cell의 contentView에 손대서 해결했는데, 그 경우에도 커멘드 창의 경고가 뜨긴 하지만
경고의 양이 줄어들어서 이 방법을 채택했습니다.
- 원래는 리뷰 등록이 느린 현상을 수정하려고 했는데,,
어디서 느린가 로그 찍어보면서 살펴보니까 `AWSS3ImageManager`의 `requestUpload(data: Data?)`의 completionHandler에서 넘겨주는데에서 네트워크 상태에 따라 약 2-10초 정도 걸리더라구요,,, 
이건 어떻게 수정하나 싶어서 일단 뒀습니다.

## Reference

## Checklist
- [x] 브랜치를 가져와 작업한 경우 이전 브랜치에 PR을 보냈는지 확인
- [x] 빌드를 위해 SceneDelegate 수정한 것 PR로 올리지 않았는지 확인
- [x] 필요없는 주석, 프린트문 제거했는지 확인
- [x] 컨벤션 지켰는지 확인
- [x] final, private 제대로 넣었는지 확인
- [x] 다양한 디바이스에 레이아웃이 대응되는지 확인
  - [x] iPhone SE
  - [x] iPhone 13
  - [x] iPhone 13 Pro Max

2022-11-07 01:19 UTC, chaneeii requested changes
수정하고 알려주시면 어프로브 하러 돌아올게요☺️
![09](https://user-images.githubusercontent.com/63157395/200207528-83378a27-115c-435d-a85f-261c823f40b5.png)

2022-11-07 01:19 UTC, chaneeii commented on Projects/App/Sources/Domain/Review/Review.swift
> +    let imageURL: URL?
Q
요부분을 URL 로 한 이유가 있을까요?
일반적인것같지 않아 궁금하네요 👀

2022-11-07 01:19 UTC, chaneeii commented on Projects/App/Sources/UI/Review/ViewModel/ReviewRegisterViewModel.swift
> +    let imageSubject = PassthroughSubject<String, Error>()
Q
@Published 에서 subject로 바꾼 이유가 궁금합니다..!
저는 @Published로 옮겨가고 싶은 입장이라

2022-11-07 01:19 UTC, chaneeii commented on Projects/App/Sources/UI/Review/ViewModel/ReviewRegisterViewModel.swift
> +
p1)
우리의 돈은 소중하다
압축 부탁드립니다! + 이렇게 하니 속도 문제가 개선이 되었습니다 🥳

일단 0.2로 가고 사진 손실이 많이나면 올립시다
(야간모드, 인물사진, raw 파일을 모두 고려한 내용입니다)
```suggestion
        let imageData = image?.jpegData(compressionQuality: 0.2)
```

2022-11-07 01:19 UTC, chaneeii commented on Projects/App/Sources/UI/Review/ViewModel/ReviewRegisterViewModel.swift
> +
p2)
이미지를 업로드하고 업로드가 잘 되었는지 체크가 필요할것같습니다!
or 
미래에 여기 이미지 업로드 관련 ux 개선을 위한 ui 가 들어가야할듯!

2022-11-07 01:19 UTC, chaneeii commented on Projects/App/Sources/UI/Review/ViewModel/ReviewRegisterViewModel.swift
>                  case .finished: break
p2)
현재 이미지 업로드 성공률이 낮기 때문에
실패시에는 요기서 print 출력말고 사용자한테 보여지는 알람이 필요할것같습니다 
(그리고 다음페이지로 안넘어가게)

현재는 업로드가 안되었는데도 리뷰등록 완료!!!! 하고 축하해주니깐 이상하네요ㅠ

2022-11-07 01:19 UTC, chaneeii commented on Projects/App/Sources/UI/Review/View/ReviewCardViewController.swift
>  }
p1)
리뷰등록완료 페이지 뒤로가기 스와이프 막아주세요

2022-11-07 01:19 UTC, chaneeii commented on Projects/App/Sources/UI/Review/ViewModel/ReviewRegisterViewModel.swift
> +
그리고 압축코드를 네트워크 레이어에 넣는게 좋을 것 같아요

2022-11-07 01:43 UTC, Lia316 commented on Projects/App/Sources/Domain/Review/Review.swift
> +    let imageURL: URL?
https://github.com/DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY/pull/57#discussion_r1005565372

의 리뷰에 따라 도메인에서 raw한 string 대신에 URL을 갖도록 수정했습니다.

2022-11-07 01:52 UTC, Lia316 commented on Projects/App/Sources/UI/Review/ViewModel/ReviewRegisterViewModel.swift
> +
7570abb3fded86409195e0846e782bc65cc2af85
압축 코드 추가 및 코드 usecase로 이동 완료했습니다!

2022-11-07 01:57 UTC, Lia316 commented on Projects/App/Sources/UI/Review/View/ReviewCardViewController.swift
>  }
44b47fc14b8622a4b4a523e9786a7c6285b15d4f 반영했습니다!

2022-11-07 02:08 UTC, Gobans requested changes
고생하셨습니다 리아!
그런데 ReviewRegisterViewController -> ReviewCardViewController 플로우에서 ReviewRegisterViewController 에서 progressView 로 이미지 업로드를 기다리고 그 다음 화면을 전환을 하는게 더 UX에 좋은 것 같은 생각이 듭니다. 현재는 조금 뜬금없는 캐릭터가 나와서 의미를 잘 모르겠어요! 유저가 이 화면을 처음 보면기다려야 하는지도 모를 것 같기도 하고..!
@Chaeho-Min 의 생각도 궁금하네요
추가로 남긴 코드리뷰 몇개 확인 해주시면 감사하겠습니다!!

2022-11-07 02:08 UTC, Gobans commented on Projects/App/Sources/Domain/Review/Review.swift
>      let reviewer: User?
p1
요거 reviewer 라는 struct model을 따로 만들어서 사용하는게 좋을 것 같아요
현재는 reviewer 필요없는 provider nickname 등 정보들이 많이 있기도 하고
User 정보는 UserInfoManager를 사용하니까요! User struct model 삭제해도 될 것 같습니다

2022-11-07 02:08 UTC, Gobans commented on Projects/App/Sources/UI/Review/View/ReviewCardViewController.swift
>      @objc func saveButtonTouched() {
p2
여기 뷰 컨트롤러에 private 들이 잘 설정이 안되있네요
backButtonTouched completeButtonTouched 등등

2022-11-07 02:08 UTC, Gobans commented on Projects/App/Sources/UI/Review/View/Views/ReviewCardView.swift
> +            .dropFirst()
p2
dropFrist 이거 저번에도 의견을 나눴었는데, 좀 지양을 하는게 좋을 것 같다고 느낀 이유를 이번에 좀 정리해서 말씀 드릴게요.
1. 상위 스트림 (useCase 의 published result) 의 변경을 자유롭게 할 수 없고 하위 스트림 (viewModel) 과 연결되어 동작상의 코드 의존성이 생긴다.
2. API -> useCase -> viewModel 로 이어지는 스트림에서 현재 useCase에서 result 값을 가지고 있을 이유가 없다. 그렇다면 passthroughSubject를 쓰는게 더 맞지 않을까 생각합니다.
3. 현재 로직상 모델을 viewController 에 넘겨주는 역할을 하고 있는데 이후에 에러 처리를 하여 분기에 따라 viewController 에서 화면을 보여줄 떄 @Published 는 에러타입을 함께 넘겨줄 수 없다. (에러에 따른 분기처리가 불가능하다)

그래서 result를 subject 로 바꾸고 dropFirst를 없애자는 의견입니다.
리아의 의견이 궁금합니다👀

2022-11-07 02:10 UTC, Lia316 commented on Projects/App/Sources/UI/Review/ViewModel/ReviewRegisterViewModel.swift
> +    let imageSubject = PassthroughSubject<String, Error>()
@published 같은 경우에는 dropfirst()를 사용해야하는 등, 초기값에 신경을 좀 써야해서 
맘 편하게 값이 들어올 때만 쓸 수 있는 subject로 바꿨습니다~!

2022-11-07 02:15 UTC, Lia316 commented on Projects/App/Sources/UI/Review/View/Views/ReviewCardView.swift
> +            .dropFirst()
1번 2번 동의합니다.
3번은, 어차피 에러는 뷰모델에서 처리해야한다고 생각해서, 굳이 에러타입은 넘겨줄 필요가 없다고 생각하긴 해요!

저도 이번에 코드 작성하면서 코드 의존성을 체감해서 passthroughSubject로 변경하겠습니다~!

2022-11-07 02:17 UTC, Lia316 commented on Projects/App/Sources/UI/Review/View/ReviewCardViewController.swift
>      @objc func saveButtonTouched() {
e6ac698f8ac75452f3763350755d7f866dc6cb32 다른 파일의 private 설정도 추가했습니다! 감사합니다

2022-11-07 02:49 UTC, Lia316 commented on Projects/App/Sources/Domain/Review/Review.swift
>      let reviewer: User?
80ec4201185d78356306c39e786016241f71fabe 
유저는 Place에서도 사용하는 정보라서 이름을 변경하진 않았고,
함께 합의한 대로 닉네임과 아이디만 남겨놨습니다~!

2022-11-07 02:53 UTC, Lia316 commented on Projects/App/Sources/UI/Review/View/Views/ReviewCardView.swift
> +            .dropFirst()
8dd66c11774afdb10900172efc345d9d4c9580d5 변경 완료!

2022-11-07 03:31 UTC, Gobans approved these changes

2022-11-07 11:24 UTC, chaneeii commented on Projects/App/Sources/UI/Review/ViewModel/ReviewRegisterViewModel.swift
> +    let imageSubject = PassthroughSubject<String, Error>()
아하!

2022-11-07 11:25 UTC, chaneeii approved these changes

2022-11-08 04:49 UTC, Lia316 commented on Projects/App/Sources/UI/Review/ViewModel/ReviewRegisterViewModel.swift
>                  case .finished: break
c160944b9ac080a1eb1ff4de72383b462259cdd8 이미지 업로드 실패 시 alert를 띄우도록 변경했습니다!
더불어 이미지 업로드가 완료되지 않으면 메뉴 등록 버튼을 비활성화해서 다음 뷰로 넘어가지 못하게 막았습니다.

근데 생각해보니까 메뉴 사진이 자꾸 업로드에 실패해서 그냥 사진 없이 리뷰 등록하려는 사람에게는.. 치명적일 듯요..?? 😱

2022-11-08 07:08 UTC, merged