[Feat] 대학교 리스트 검색 도메인 & 네트워킹]
DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY pull request #97
Opened 2022-11-07 00:54 UTC by tea-hkim

## 작업내용

- [x] 대학교 리스트 fetch
- [x] 검색 버튼과 모델 연결

|'서울' 검색|'애플'검색|
|:---:|:---:|
|<img width="250" src="https://user-images.githubusercontent.com/81206228/200205299-ea2f6248-3ed6-4037-a453-addb045ff4a0.png">|<img width="250" src="https://user-images.githubusercontent.com/81206228/200205339-0608abe3-b124-4051-aa91-2da2aa299c1b.png">|

## 리뷰포인트

### ViewModel의 역할에 대한 고민
 - 로직을 변경한 이유는 cell 내부의 UI component들에 대한 접근 권한을 private 하게 관리하기 위함입니다.
   변경 전 코드에는 cell 내부의 UILabel의 text에 직접 전달을 했습니다.
   하지만 bind라는 함수를 사용해서 외부에서 데이터를 받아와 UILabel을 그려주는 방식으로 변경하였습니다.
 - searchedOrgArray라는 변수명의 역할을 명확하게 하기 위해 orgNameArrary에서 필터링하는 방식이 아닌 orgArray에서 바로 필터링하는 방식으로 변경했습니다.
 - 또한 다음 뷰에서는 organization의 이름과 도메인이 필요하기 때문에 직접 organization 데이터를 전달하는 편이 효율적이라고 생각되어 변경했습니다.

 고민인 부분
 - View와 직접적인 관계가 있는 데이터를 가지고 있는 것이 ViewModel의 역할이라고 생각합니다.
   하지만 제가 구현한 방식은 OrganizatinoListView에서 원하는 데이터인 조직 이름 리스트가 아니라 조직의 리스트를 가지고 있고 이 방식이 과연 맞는 방식인지에 대한 의문이 남았습니다.

   전에 구현하던 방식(조직 이름 리스트만 가지고 있는 방식)이 ViewModel의 역할을 제대로 수행하고 있다고 생각합니다. 
View에 띄워야 하는 데이터만을 가지고 있기 때문입니다. 
하지만 이 방식에서 문제라고 생각되는 부분은 cell이 탭되어 다른 뷰로 넘어갔을 경우 ViewModel에서 orgArray에서 해당 조직의 이름과 같은 organization을 찾아 넘겨줘야 한다는 부분에서 비효율적이라는 생각이 들었습니다. 
이 경우에는 이런 역할을 수행하는 함수를 따로 만들어서 cell이 탭이 되어 뷰가 전환될 때 함수를 실행해줘야 할까요?

## Checklist
- [x] 브랜치를 가져와 작업한 경우 이전 브랜치에 PR을 보냈는지 확인
- [x] 빌드를 위해 SceneDelegate 수정한 것 PR로 올리지 않았는지 확인
- [x] 필요없는 주석, 프린트문 제거했는지 확인
- [x] 컨벤션 지켰는지 확인
- [x] final, private 제대로 넣었는지 확인
- [x] 다양한 디바이스에 레이아웃이 대응되는지 확인
  - [x] iPhone SE
  - [x] iPhone 13
  - [x] iPhone 13 Pro Max

2022-11-07 04:20 UTC, Gobans requested changes
고생하셨습니다 닉!
고민하신 부분은 다시 보고 리뷰 남길게요
일단 리뷰 하나 단거 먼저 확인해주세요

2022-11-07 04:20 UTC, Gobans commented on Projects/App/Sources/UI/Organization/OrganizationList/ViewModel/OrganizatinoListViewModel.swift
> +    let isSearchText = PassthroughSubject<String, Never>()
p1
요거 불필요한 중복 바인딩인 것 같습니다.
userTextInput 하나만 사용하고 searchButtonTapped 했을 떄
` searchingTextField.resignFirstResponder()` 하는게 동작이 더 자연스러운 것 같네요

2022-11-07 08:57 UTC, tea-hkim commented on Projects/App/Sources/UI/Organization/OrganizationList/ViewModel/OrganizatinoListViewModel.swift
> +    let isSearchText = PassthroughSubject<String, Never>()
이 방법이 있었네요!
4601a6200444efd19800947dd41f0c591b726b6a 변경했습니다!

2022-11-07 10:05 UTC, chaneeii approved these changes
고생하셨습니다..!
이제 컴바인 사용이 왜죠 엄청 잘쓰시는거같아 보이는거같ㅇ요...!🥳

2022-11-07 10:05 UTC, chaneeii commented on Projects/App/Sources/UI/Organization/DomainSetting/ViewModel/DomainSettingViewModel.swift
> +            .store(in: &cancelBag)
p5)
init 이 너무 길어져서 함수를 따로 파도 좋을 것 같아요!

2022-11-08 07:13 UTC, Gobans approved these changes

2022-11-08 08:48 UTC, merged